(function () {
  "use strict";
  const R = window.COMPOSITE_RUNTIME;
  const app = document.getElementById("app");
  const modalRoot = document.getElementById("modal-root");
  let route = (location.hash || "#home").replace(/^#/, "") || "home";
  const ICONS = { home: "⌂", database: "◫", network: "⌘", sparkles: "✦", target: "◎", bot: "◌", file: "▤", chart: "▥", arrow: "→", close: "×", play: "▶", refresh: "↻", reset: "↺", layers: "◈" };
  const esc = (value) => String(value ?? "").replace(/[&<>"']/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#039;" }[char]));
  const icon = (name, cls = "") => `<span class="ofw-icon ${cls}" aria-hidden="true">${ICONS[name] || "·"}</span>`;
  const scenario = (id) => R.getScenario(id);
  const record = (id) => R.getState(id);
  const activeRoute = () => route === "home" ? "home" : route.startsWith("detail/") ? route.split("/")[1] : route.split("/")[0];
  const progressText = (item) => item.runStatus === "running" ? `${item.stepIndex}/${scenario(item.scenarioId).total}` : item.runStatus === "completed" ? `${scenario(item.scenarioId).total}/${scenario(item.scenarioId).total}` : `0/${scenario(item.scenarioId).total}`;

  function nav() {
    return `<aside class="composite-nav"><div class="nav-brand"><span class="brand-mark">OF</span><div><strong>智财问策</strong><small>Ontology Financial World</small></div></div><div class="nav-caption">统一工作区</div><button class="nav-item ${activeRoute() === "home" ? "active" : ""}" data-route="home">${icon("home")}<span>总览</span></button>${R.modules.map((item) => `<button class="nav-item ${activeRoute() === item.id ? "active" : ""}" data-route="${item.id}">${icon(item.icon)}<span>${item.name}</span></button>`).join("")}<div class="nav-foot"><span class="status-dot"></span><span>四场景组合 · ${R.completedCount()}/4 已完成</span><small>统一 Shell · 单层导航</small></div></aside>`;
  }
  function topbar() {
    return `<header class="composite-topbar"><div><span class="eyebrow">四场景组合总装</span><h1>${route === "home" ? "统一业务工作区" : esc(R.modules.find((item) => item.id === activeRoute())?.name || "统一业务工作区")}</h1></div><div class="top-actions"><span class="version-chip">v1.1.0-rc.1</span><span class="baseline-chip">治理基线 v1.0.3</span><button class="icon-btn" data-action="refresh" title="重新读取">${icon("refresh")}</button></div></header>`;
  }
  function scenarioStatusCard(item) {
    const s = scenario(item.scenarioId); const status = R.statusLabel(item); const tone = item.runStatus === "completed" ? "success" : item.runStatus === "running" ? "info" : item.runStatus === "failed" ? "danger" : "muted";
    return `<article class="scenario-card tone-${s.color}"><div class="scenario-card-head"><div><span class="scenario-kicker">${esc(s.id)} · ${esc(s.domain)}</span><h3>${esc(s.name)}</h3></div><span class="status-pill ${tone}">${status}</span></div><p>${esc(s.highlights[0])} · ${esc(s.highlights[1])}</p><div class="scenario-progress"><div><strong>${progressText(item)}</strong><span>${item.runStatus === "running" ? esc(item.currentStep || "处理中") : item.runStatus === "completed" ? "链路已完成" : "等待启动"}</span></div><i><b style="width:${Math.round((item.stepIndex / s.total) * 100)}%"></b></i></div><dl class="scenario-facts"><div><dt>场景版本</dt><dd>${esc(s.version)}</dd></div><div><dt>数据截至</dt><dd>${esc(s.asOf)}</dd></div><div><dt>运行轮次</dt><dd>${esc(item.scenarioRunId || "尚未形成")}</dd></div></dl><div class="scenario-card-actions">${item.runStatus === "running" ? `<button class="btn soft" disabled>处理中</button>` : item.runStatus === "completed" ? `<button class="btn" data-action="view-scenario" data-id="${s.id}">查看运行</button><button class="btn ghost" data-action="reset-scenario" data-id="${s.id}">重置本轮</button>` : `<button class="btn primary" data-action="run-scenario" data-id="${s.id}">开始运行</button>`}</div></article>`;
  }
  function homeView() {
    const all = R.SCENARIOS.map((s) => record(s.id)); const completed = R.completedCount(); const running = all.find((item) => item.runStatus === "running"); const recent = R.loadState().state.activity.slice(0, 5);
    return `<div class="page home-page"><section class="hero-band"><div><span class="eyebrow">ONTOLOGY FINANCIAL WORLD · 统一业务工作区</span><h2>数据、语义、决策与行动，统一在一套工作台内运行</h2><p>四个业务场景共享平台能力，数据工程、本体、问数、决策、Agent、报告和仪表盘按场景聚合展示；场景身份只存在于业务记录和运行结果中，不再切换产品壳。</p></div><div class="hero-actions"><button class="btn primary large" data-action="run-all" ${running ? "disabled" : ""}>${icon("play")} ${running ? "正在运行" : "顺序运行四个场景"}</button><span class="hero-note">${completed}/4 场景已完成 · 运行结果由操作产生</span></div></section><section class="summary-strip"><div><span>组合进度</span><strong>${completed}/4</strong><small>场景运行完成</small></div><div><span>当前基线</span><strong>v1.0.7</strong><small>治理基线 v1.0.3</small></div><div><span>数据资产</span><strong>16</strong><small>跨场景登记资产与版本</small></div><div><span>Published 本体</span><strong>4</strong><small>按场景版本管理</small></div></section><section class="section-head"><div><span class="eyebrow">场景运行</span><h2>四个业务场景</h2><p>在同一工作区内查看和运行，不再打开第二套产品导航。</p></div><button class="btn ghost" data-route="dashboard">查看组合驾驶舱</button></section><div class="scenario-grid">${all.map(scenarioStatusCard).join("")}</div><section class="activity-panel"><div class="section-head compact"><div><span class="eyebrow">运行记录</span><h2>最近操作</h2></div><span class="muted-copy">所有记录绑定各自场景运行轮次</span></div>${recent.length ? `<div class="activity-list">${recent.map((item) => `<div class="activity-row"><span class="activity-dot"></span><div><strong>${esc(item.text)}</strong><small>${esc(item.scenarioId)} · ${new Date(item.at).toLocaleString("zh-CN", { hour12: false })}</small></div></div>`).join("")}</div>` : `<div class="empty-state">${icon("layers", "lg")}<strong>还没有本轮运行记录</strong><span>点击任一场景的“开始运行”，按顺序产生完整链路结果。</span></div>`}</section></div>`;
  }
  function dataRows() { return R.SCENARIOS.map((s) => { const r = record(s.id); return { scene: s.id, name: s.name, source: s.source, asset: s.asset, asOf: s.asOf, status: r.runStatus === "completed" ? "可消费" : "待运行", version: r.scenarioRunId || "未形成", members: s.id === "S001" ? "4 个成员 / 3 条关系" : s.id === "S002" ? "14 个成员 / 2 条管道" : s.id === "S003" ? "财务数据 / 调节因子" : "财务报告 / 贷前资料" }; }); }
  function ontologyRows() { return R.SCENARIOS.map((s) => ({ scene: s.id, name: s.name, version: s.ontology, scope: s.id === "S001" ? "4 Object / 3 Link / 7 Metric / 3 Rule" : s.id === "S002" ? "7 Object / 9 Metric / 5 Rule / 6 Action Type" : s.id === "S003" ? "风险模型 / 15 指标 / 亮灯 Rule" : "贷前调查 Published 资源", status: record(s.id).runStatus === "completed" ? "已发布" : "已登记 · 待运行" })); }
  function queryRows() { return R.SCENARIOS.map((s) => ({ scene: s.id, name: s.name, agent: s.id === "S001" ? "融资问数 Agent" : s.id === "S002" ? "预算问数 Agent" : s.id === "S003" ? "风险监测问数 Agent" : "报告伴读 Agent", question: s.query, status: record(s.id).runStatus === "completed" ? "可运行" : "等待场景运行" })); }
  function decisionRows() { return R.SCENARIOS.map((s) => ({ scene: s.id, name: s.name, requests: s.id === "S001" ? "3 条 Action Request" : s.id === "S002" ? "0 条 · 当前范围关闭" : s.id === "S003" ? "9 条候选 · 待人工确认" : "0 条 · 不适用", owner: s.id === "S001" ? "融资负责人001" : s.id === "S003" ? "成员单位接口人" : "—", status: record(s.id).runStatus === "completed" ? "可查看" : "待运行" })); }
  function agentRows() { return R.SCENARIOS.map((s) => ({ scene: s.id, name: s.name, agent: s.id === "S001" ? "报告伴读与数据核验助手" : s.id === "S002" ? "预算异常分析 Agent / 预算报告草稿 Agent" : s.id === "S003" ? "风险分析 Agent / 报告伴读 Agent" : "贷前调查报告伴读 Agent", evidence: s.evidence, status: record(s.id).runStatus === "completed" ? "可运行" : "待运行" })); }
  function reportRows() { return R.SCENARIOS.map((s) => ({ scene: s.id, name: s.name, definition: s.id === "S001" ? "集团融资经营分析" : s.id === "S002" ? "预算监督专题报告" : s.id === "S003" ? "企业债务风险评估报告" : "财务公司贷款贷前调查报告", output: s.report, status: record(s.id).runStatus === "completed" ? "已形成候选产物" : "等待运行" })); }
  function tablePage(moduleId, title, intro, columns, rows) { return `<div class="page module-page"><section class="module-header"><div><span class="eyebrow">${esc(R.modules.find((m) => m.id === moduleId)?.name || "平台模块")} · 四场景聚合</span><h2>${esc(title)}</h2><p>${esc(intro)}</p></div><div class="module-header-actions"><button class="btn ghost" data-route="home">${icon("home")}返回总览</button><button class="btn" data-action="refresh">${icon("refresh")}重新读取</button></div></section><section class="aggregate-toolbar"><div><strong>所有场景</strong><span>共 ${rows.length} 条场景记录</span></div><input data-filter="table" placeholder="搜索场景、名称或版本" aria-label="搜索场景、名称或版本"></section><section class="table-card"><table><thead><tr>${columns.map((col) => `<th>${esc(col.label)}</th>`).join("")}<th>操作</th></tr></thead><tbody>${rows.map((row, index) => `<tr data-row-text="${esc(Object.values(row).join(" "))}">${columns.map((col) => `<td>${col.render ? col.render(row) : esc(row[col.key])}</td>`).join("")}<td><button class="text-btn" data-action="open-detail" data-module="${moduleId}" data-scene="${esc(row.scene)}">进入完整功能 ${icon("arrow")}</button></td></tr>`).join("")}</tbody></table></section></div>`; }
  function moduleView(moduleId) {
    if (moduleId === "data") return tablePage("data", "数据资产目录", "所有场景的数据源、快照、管道和已发布资产在同一目录中管理，场景只作为业务列和筛选条件。", [{ label: "场景", key: "scene", render: (r) => `<span class="scene-tag">${esc(r.scene)}</span>` }, { label: "业务名称", key: "name" }, { label: "数据来源", key: "source" }, { label: "数据资产版本", key: "asset" }, { label: "成员与关系", key: "members" }, { label: "截至时间", key: "asOf" }, { label: "当前状态", key: "status", render: (r) => `<span class="status-pill ${r.status === "可消费" ? "success" : "muted"}">${esc(r.status)}</span>` }], dataRows());
    if (moduleId === "ontology") return tablePage("ontology", "Published 本体目录", "所有场景的已发布本体、对象、指标、规则和行动类型统一展示，版本和消费绑定按场景保留。", [{ label: "场景", key: "scene", render: (r) => `<span class="scene-tag">${esc(r.scene)}</span>` }, { label: "业务本体", key: "name" }, { label: "Published 版本", key: "version" }, { label: "资源范围", key: "scope" }, { label: "当前状态", key: "status", render: (r) => `<span class="status-pill ${r.status === "已发布" ? "success" : "muted"}">${esc(r.status)}</span>` }], ontologyRows());
    if (moduleId === "query") return tablePage("query", "智能问数工作台", "问数 Agent、推荐问题和固定结果按场景聚合；提问时会绑定当前场景最新完成运行。", [{ label: "场景", key: "scene", render: (r) => `<span class="scene-tag">${esc(r.scene)}</span>` }, { label: "问数 Agent", key: "agent" }, { label: "推荐问题范围", key: "question" }, { label: "当前状态", key: "status", render: (r) => `<span class="status-pill ${r.status === "可运行" ? "success" : "muted"}">${esc(r.status)}</span>` }], queryRows());
    if (moduleId === "decision") return tablePage("decision", "决策工作台", "四个场景的 Action Request、人工确认和负责人待办共用决策中心；每条运行事实保留场景身份。", [{ label: "场景", key: "scene", render: (r) => `<span class="scene-tag">${esc(r.scene)}</span>` }, { label: "决策事项", key: "requests" }, { label: "负责人范围", key: "owner" }, { label: "当前状态", key: "status", render: (r) => `<span class="status-pill ${r.status === "可查看" ? "success" : "muted"}">${esc(r.status)}</span>` }], decisionRows());
    if (moduleId === "agent") return tablePage("agent", "Agent 应用目录", "报告伴读、异常分析和报告草稿 Agent 统一管理，运行和证据按场景绑定。", [{ label: "场景", key: "scene", render: (r) => `<span class="scene-tag">${esc(r.scene)}</span>` }, { label: "Agent 能力", key: "agent" }, { label: "证据来源", key: "evidence" }, { label: "当前状态", key: "status", render: (r) => `<span class="status-pill ${r.status === "可运行" ? "success" : "muted"}">${esc(r.status)}</span>` }], agentRows());
    if (moduleId === "report") return tablePage("report", "报告与仪表盘目录", "报告定义、仪表盘、HTML/PDF、核验和当前比较统一在报告中心管理，不再嵌入另一套场景导航。", [{ label: "场景", key: "scene", render: (r) => `<span class="scene-tag">${esc(r.scene)}</span>` }, { label: "业务名称", key: "name" }, { label: "报告定义", key: "definition" }, { label: "当前产物", key: "output" }, { label: "状态", key: "status", render: (r) => `<span class="status-pill ${r.status === "已形成候选产物" ? "success" : "muted"}">${esc(r.status)}</span>` }], reportRows());
    return dashboardView();
  }
  function dashboardView() { return `<div class="page module-page"><section class="module-header"><div><span class="eyebrow">仪表盘 · 四场景聚合</span><h2>组合经营驾驶舱</h2><p>同一页面比较四个业务场景的运行进度、数据资产、语义版本、报告状态和决策事项。</p></div><div class="module-header-actions"><button class="btn primary" data-action="run-all">${icon("play")}顺序运行未完成场景</button></div></section><section class="dashboard-grid">${R.SCENARIOS.map((s) => { const r = record(s.id); return `<article class="dashboard-card tone-${s.color}"><header><div><span class="scene-tag">${s.id}</span><h3>${esc(s.name)}</h3></div><span class="status-pill ${r.runStatus === "completed" ? "success" : r.runStatus === "running" ? "info" : "muted"}">${R.statusLabel(r)}</span></header><div class="dashboard-number">${progressText(r)}<small>链路进度</small></div><div class="dashboard-facts"><span>${esc(s.asset)}</span><span>${esc(s.ontology)}</span><span>${esc(s.report)}</span></div><footer><button class="btn" data-action="run-scenario" data-id="${s.id}" ${r.runStatus === "running" ? "disabled" : ""}>${r.runStatus === "completed" ? "重新运行" : "开始运行"}</button><button class="text-btn" data-action="detail" data-module="dashboard" data-index="${R.SCENARIOS.indexOf(s)}">查看详情 ${icon("arrow")}</button></footer></article>`; }).join("")}</section></div>`; }
  function dashboardView() { return `<div class="page module-page"><section class="module-header"><div><span class="eyebrow">仪表盘 · 四场景聚合</span><h2>组合经营驾驶舱</h2><p>同一页面比较四个业务场景的运行进度、数据资产、语义版本、报告状态和决策事项。</p></div><div class="module-header-actions"><button class="btn primary" data-action="run-all">${icon("play")}顺序运行未完成场景</button></div></section><section class="dashboard-grid">${R.SCENARIOS.map((s) => { const r = record(s.id); return `<article class="dashboard-card tone-${s.color}"><header><div><span class="scene-tag">${s.id}</span><h3>${esc(s.name)}</h3></div><span class="status-pill ${r.runStatus === "completed" ? "success" : r.runStatus === "running" ? "info" : "muted"}">${R.statusLabel(r)}</span></header><div class="dashboard-number">${progressText(r)}<small>链路进度</small></div><div class="dashboard-facts"><span>${esc(s.asset)}</span><span>${esc(s.ontology)}</span><span>${esc(s.report)}</span></div><footer><button class="btn" data-action="run-scenario" data-id="${s.id}" ${r.runStatus === "running" ? "disabled" : ""}>${r.runStatus === "completed" ? "重新运行" : "开始运行"}</button><button class="text-btn" data-action="detail" data-module="dashboard" data-index="${R.SCENARIOS.indexOf(s)}">查看详情 ${icon("arrow")}</button></footer></article>`; }).join("")}</section></div>`; }
  function detailView(moduleId, scenarioId) {
    const s = scenario(scenarioId); const src = R.detailSource(scenarioId, moduleId); const moduleName = R.modules.find((item) => item.id === moduleId)?.name || "模块";
    if (!src) return `<div class="page module-page"><section class="detail-unavailable"><h2>完整入口尚未登记</h2><p>${esc(s?.name || scenarioId)} 的 ${esc(moduleName)} 入口尚未登记。</p><button class="btn" data-route="${moduleId}">返回聚合目录</button></section></div>`;
    return `<div class="page detail-page"><section class="detail-toolbar"><div><span class="eyebrow">${esc(moduleName)} · ${esc(s?.id || scenarioId)} 完整功能</span><h2>${esc(s?.name || scenarioId)}</h2><p>沿用场景基线的完整页面和交互，外层导航保持为统一组合 Shell。</p></div><div><button class="btn ghost" data-route="${moduleId}">${icon("arrow")}返回聚合目录</button><button class="btn" data-action="reload-detail">${icon("refresh")}重新读取</button></div></section><section class="detail-frame-shell"><iframe id="detail-frame" title="${esc(s?.name || scenarioId)} · ${esc(moduleName)}" src="${esc(src)}" sandbox="allow-scripts allow-same-origin allow-forms allow-modals allow-popups allow-downloads"></iframe></section></div>`;
  }
  function injectDetailAdapter(frame) {
    try {
      const doc = frame.contentDocument; if (!doc || doc.getElementById("ofw-composite-detail-adapter")) return;
      const style = doc.createElement("style"); style.id = "ofw-composite-detail-adapter"; style.textContent = `html,body{min-height:100%!important;height:auto!important}body{overflow:auto!important}.platform-rail,.product-nav,.app-rail,.app-topbar,.topbar,.nav-rail,.product-sidebar{display:none!important}.app-shell,.decision-app{grid-template-columns:minmax(0,1fr)!important}.app-shell>.app-workspace,.app-shell>.workspace,.decision-app>.app-workspace{grid-column:1!important;grid-row:1!important}.main,.screen-stage{min-width:0!important}`; doc.head.appendChild(style);
    } catch (_) {}
  }
  function modal(title, body) { modalRoot.innerHTML = `<div class="modal-backdrop" data-action="close-modal"><section class="modal-card"><header><div><span class="eyebrow">运行详情</span><h2>${esc(title)}</h2></div><button class="icon-btn" data-action="close-modal" aria-label="关闭">${icon("close")}</button></header><div class="modal-body">${body}</div><footer><button class="btn" data-action="close-modal">关闭</button></footer></section></div>`; }
  function details(index) { const s = R.SCENARIOS[index]; const r = record(s.id); if (!s) return; modal(s.name, `<div class="detail-lead"><span class="scene-tag">${s.id}</span><strong>${esc(s.name)}</strong><span class="status-pill ${r.runStatus === "completed" ? "success" : "muted"}">${R.statusLabel(r)}</span></div><dl class="detail-grid"><div><dt>场景版本</dt><dd>${esc(s.version)}</dd></div><div><dt>运行轮次</dt><dd>${esc(r.scenarioRunId || "尚未形成")}</dd></div><div><dt>数据资产</dt><dd>${esc(s.asset)}</dd></div><div><dt>Published 本体</dt><dd>${esc(s.ontology)}</dd></div><div><dt>正式报告/草稿</dt><dd>${esc(s.report)}</dd></div><div><dt>证据包</dt><dd>${esc(s.evidence)}</dd></div></dl><div class="detail-note">${esc(s.actionSummary)}</div>`); }
  function render() { const body = route === "home" ? homeView() : route === "dashboard" ? dashboardView() : route.startsWith("detail/") ? detailView(route.split("/")[1], route.split("/")[2]) : moduleView(route); app.innerHTML = `<div class="composite-shell">${nav()}<section class="composite-workspace">${topbar()}<main class="composite-main">${body}</main></section></div>`; const frame = document.getElementById("detail-frame"); if (frame) { const apply = () => { injectDetailAdapter(frame); window.setTimeout(() => injectDetailAdapter(frame), 450); window.setTimeout(() => injectDetailAdapter(frame), 1200); }; frame.addEventListener("load", apply); apply(); } }
  document.addEventListener("click", async (event) => { const target = event.target.closest("[data-route]"); if (target) { route = target.dataset.route; location.hash = route; R.setModule(route); render(); return; } const action = event.target.closest("[data-action]"); if (!action) return; if (action.dataset.action === "refresh") { render(); return; } if (action.dataset.action === "run-scenario") { await R.runScenario(action.dataset.id); render(); return; } if (action.dataset.action === "run-all") { await R.runAll(); render(); return; } if (action.dataset.action === "reset-scenario") { R.resetScenario(action.dataset.id); render(); return; } if (action.dataset.action === "view-scenario") { route = "dashboard"; location.hash = route; render(); return; } if (action.dataset.action === "open-detail") { route = `detail/${action.dataset.module}/${action.dataset.scene}`; location.hash = route; render(); return; } if (action.dataset.action === "reload-detail") { const frame = document.getElementById("detail-frame"); if (frame) frame.contentWindow.location.reload(); return; } if (action.dataset.action === "detail") { details(Number(action.dataset.index)); return; } if (action.dataset.action === "close-modal") { modalRoot.replaceChildren(); return; } });
  document.addEventListener("input", (event) => { if (event.target.dataset.filter !== "table") return; const query = event.target.value.trim().toLowerCase(); document.querySelectorAll("tbody tr[data-row-text]").forEach((row) => { row.hidden = query && !row.dataset.rowText.toLowerCase().includes(query); }); });
  window.addEventListener("hashchange", () => { route = (location.hash || "#home").replace(/^#/, "") || "home"; render(); });
  R.subscribe(render); render();
})();
