import { MODEL_TEMPLATES, MODEL_STORE_KEY, createModelStudio, defaultParameters, defaultCode, runtimeParameterSpecs } from '../shared/model-studio.js';
import { escapeModelText as esc, modelResultMarkup, modelMoney, modelNumber } from '../shared/model-result-view.js';
const root = document.getElementById('model-center');
const studio = createModelStudio();
const query = new URLSearchParams(location.search);
const tabs = [['overview','目标概览'],['data','数据与范围'],['algorithm','算法与核验'],['versions','发布版本'],['use','使用与记录']];
let dataKey, data, selectedId = query.get('goal') || null, tab = 'overview', draft = null, dirty = false, busy = '', error = '', search = '', selectedRunId = query.get('run'), selectedVersionId = query.get('version'), useIds = [], hostIds = [], controller = null, pendingNavigation = null, sourceReference = null, showArchived = false, runOverrides = {};
const dialog = document.createElement('dialog');dialog.className='studio-dialog';document.body.append(dialog);
const getGoal = () => studio.read().goals.find(goal=>goal.id===selectedId);
const glyph = name => `<i data-lucide="${name}"></i>`;
const button = (action,label,primary=false,extra='') => `<button class="studio-button ${primary?'primary':''}" data-studio-action="${action}" ${extra}>${label}</button>`;
const iconButton = (action,label,icon,extra='') => `<button class="studio-icon-button" data-studio-action="${action}" aria-label="${label}" title="${label}" ${extra}>${glyph(icon)}</button>`;
const displayAt=value=>value?new Date(value).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',hour12:false}):'—';
const versionFor = goal => studio.read().versions.find(version=>version.id===studio.read().bindings[goal.id]);
const toast = message => { const region=document.getElementById('model-center-toast');region.textContent=message;region.className='studio-toast';setTimeout(()=>{region.textContent='';region.className='';},3500); };
function announce() { if(parent!==window)parent.postMessage({type:'OFW_MODEL_STUDIO_ROUTE',goalId:selectedId,tab},location.origin); }
function persistView(replace=true){const url=new URL(location.href);for(const key of ['goal','version','run','focusModel'])url.searchParams.delete(key);if(selectedId){url.searchParams.set('goal',selectedId);if(selectedVersionId)url.searchParams.set('version',selectedVersionId);if(selectedRunId)url.searchParams.set('run',selectedRunId);}url.hash=selectedId?`goal/${encodeURIComponent(selectedId)}/${tab}`:'objectives';history[replace?'replaceState':'pushState'](null,'',url);announce();}

function route() {
  if(location.hash==='#objectives'){selectedId=null;tab='overview';return;}
  const parts=location.hash.replace(/^#\/?/,'').split('/');
  if(parts[0]==='goal'&&parts[1]){selectedId=decodeURIComponent(parts[1]);tab=tabs.some(([id])=>id===parts[2])?parts[2]:'overview';}
  else if(query.get('focusModel')){selectedId='builtin-risk';tab='overview';}
  else if(query.get('goal')){selectedId=query.get('goal');tab=query.get('run')?'use':query.get('version')?'versions':'overview';}
  else selectedId=null;
}
function navigate(goalId, nextTab='overview') {
  if(busy){toast('请等待本次运行完成，或先停止计算');return;}
  if(goalId===selectedId&&nextTab===tab)return;
  const apply=()=>{selectedId=goalId;tab=nextTab;draft=goalId?structuredClone(getGoal().draft):null;dirty=false;error='';selectedRunId=null;selectedVersionId=goalId?studio.read().bindings[goalId]||null:null;useIds=initialUseIds();persistView(false);render();};
  if(dirty){pendingNavigation=apply;openDialog('保留当前修改',`<p>当前算法或范围尚未保存。选择保存后切换，或放弃本次修改。</p>`,`${button('cancel-dialog','继续编辑')}${button('discard-navigate','放弃修改')}${button('save-navigate','保存后切换',true)}`);}else apply();
}
function initialUseIds() { runOverrides={};const goal=getGoal();if(!goal)return[];const version=studio.read().versions.find(v=>v.id===(selectedVersionId||studio.read().bindings[goal.id]));return version?hostIds.length?hostIds.filter(id=>version.objectIds.includes(id)):[...version.objectIds]:[]; }
function badge(label, tone='') { return `<span class="studio-badge ${tone}">${esc(label)}</span>`; }
function targetStatus(goal) { if(goal.archived)return '已归档';const version=versionFor(goal);return version?`当前应用 ${version.name}`:studio.read().versions.some(v=>v.goalId===goal.id)?'未启用应用版本':'工作草稿'; }
function nextStep(goal) { const current=goal.id===selectedId&&draft?draft:goal.draft;if(!current.objectIds.length)return ['data','选择适用企业'];if(goal.id===selectedId&&dirty)return ['algorithm','核验当前修改'];if(goal.draft.signature!==goal.draft.validatedSignature||!goal.draft.validatedSignature)return ['algorithm','运行算法核验'];if(!studio.read().versions.some(v=>v.goalId===goal.id&&v.signature===goal.draft.signature))return ['versions','发布新版本'];return ['use','使用发布版本']; }
function refreshIcons() { window.lucide?.createIcons({root:document}); }
function render() {
  const state=studio.read(),goal=getGoal();
  const filtered=state.goals.filter(goal=>(showArchived||!goal.archived)&&(!search||`${goal.name} ${goal.owner}`.includes(search)));
  root.className='model-studio';
  root.innerHTML=`<aside class="studio-goals"><header><h2>模型目标</h2>${iconButton('new-goal','新建目标','plus')}</header><label class="studio-search">${glyph('search')}<input id="goal-search" type="search" placeholder="搜索目标或负责人" value="${esc(search)}"></label><nav>${filtered.map(item=>`<button class="studio-goal-link ${item.id===selectedId?'active':''}" data-studio-goal="${item.id}"><strong>${esc(item.name)}</strong><small>${esc(MODEL_TEMPLATES[item.type].resultLabel)} · ${esc(item.owner)}</small><span>${esc(targetStatus(item))}</span></button>`).join('')||'<p class="studio-empty">没有匹配目标。</p>'}</nav><footer><label><input id="show-archived" type="checkbox" ${showArchived?'checked':''}> 显示已归档目标</label><p>本地原型 · 版本与运行可追溯</p></footer></aside><section class="studio-main"><div class="studio-mobile-target"><label>当前目标<select id="mobile-goal"><option value="">模型目标目录</option>${state.goals.map(item=>`<option value="${item.id}" ${item.id===selectedId?'selected':''}>${esc(item.name)}</option>`).join('')}</select></label>${iconButton('new-goal','新建目标','plus')}</div>${error?`<div class="studio-notice error" role="alert">${esc(error)}</div>`:''}${goal?goalMarkup(goal):catalogMarkup(filtered)}</section>`;
  refreshIcons();
}
function catalogMarkup(goals) {
  return `<header class="studio-header"><div><span>模型与算法</span><h1>围绕业务目标构建模型</h1><p>从明确业务问题，到维护算法、核验、发布版本和使用结果。</p></div>${button('new-goal','新建模型目标',true)}</header><div class="studio-goal-cards">${goals.map(goal=>{const version=versionFor(goal),step=nextStep(goal);return `<article><header>${badge(MODEL_TEMPLATES[goal.type].name)}${badge(version?'可使用':'配置中',version?'success':'')}</header><h2>${esc(goal.name)}</h2><p>${esc(goal.question)}</p><dl><div><dt>负责人</dt><dd>${esc(goal.owner)}</dd></div><div><dt>当前应用</dt><dd>${version?esc(version.name)+(version.origin==='BUILTIN_REFERENCE'?' · 内置参考':''):'尚未发布'}</dd></div><div><dt>适用企业</dt><dd>${version?.objectIds.length||goal.draft.objectIds.length} 家</dd></div></dl><button class="studio-button primary" data-studio-goal="${goal.id}" data-target-tab="${step[0]}">${step[1]}</button><button class="studio-text-button" data-studio-goal="${goal.id}">查看目标与历史</button></article>`;}).join('')}</div><section class="studio-guidance"><h3>一次清楚的闭环</h3><ol><li>创建业务目标</li><li>选择数据与企业范围</li><li>维护算法并核验</li><li>发布不可变版本</li><li>使用版本并回看记录</li></ol><p>内置参考版本可直接体验；新目标按同一流程创建。成本预测使用借款现金流与利率假设，不虚构未来实际成本的回测结果。</p></section>`;
}
function goalMarkup(goal) {
  const step=nextStep(goal),version=versionFor(goal);
  return `<header class="studio-header"><div><button class="studio-text-button" data-studio-action="catalog">模型目标 /</button><h1>${esc(goal.name)}</h1><p>${esc(goal.question)}</p><div class="studio-meta">${badge(MODEL_TEMPLATES[goal.type].name)}<span>负责人 ${esc(goal.owner)}</span>${version?badge(`当前应用 ${version.name}`,'success'):badge('工作草稿')}<span class="studio-dirty" ${dirty?'':'hidden'}>有未保存修改</span></div></div><div class="studio-header-actions">${button('next',step[1],true,`data-next-tab="${step[0]}" ${busy?'disabled':''}`)}${iconButton('edit-goal','编辑目标','pencil')}${button('archive-goal',goal.archived?'恢复目标':'归档目标')}</div></header><nav class="studio-tabs" aria-label="目标工作步骤">${tabs.map(([id,label])=>`<button data-studio-tab="${id}" class="${tab===id?'active':''}">${label}</button>`).join('')}</nav>${busy?`<div class="studio-running" role="status"><span>${esc(busy)}</span>${controller?button('cancel-run','停止本次计算'):''}</div>`:''}<div class="studio-content">${tab==='overview'?overviewMarkup(goal):tab==='data'?dataMarkup(goal):tab==='algorithm'?algorithmMarkup(goal):tab==='versions'?versionsMarkup(goal):useMarkup(goal)}</div>`;
}
function overviewMarkup(goal) {
  const state=studio.read(),version=versionFor(goal),runs=state.runs.filter(run=>run.goalId===goal.id),template=MODEL_TEMPLATES[goal.type];
  return `${sourceReference&&goal.id==='builtin-risk'?sourceMarkup():''}<section class="studio-panel"><h2>业务目标与方法</h2><p>${esc(template.method)}</p><dl class="studio-definition"><dt>关注的结果</dt><dd>${esc(template.resultLabel)}</dd><dt>算法输入</dt><dd>${template.inputs.map(esc).join('、')}</dd><dt>数据观察日</dt><dd>${esc(state.datasets[goal.draft.dataKey]?.asOf)}</dd><dt>版本规则</dt><dd>工作草稿可以修改；已发布算法、参数、范围和核验依据固定保存。</dd></dl></section><div class="studio-overview-grid"><section class="studio-panel"><h2>当前应用版本</h2>${version?`<h3>${esc(version.name)} ${version.origin==='BUILTIN_REFERENCE'?badge('内置参考'):''}</h3><p>${esc(version.note)}</p><small>${esc(displayAt(version.publishedAt))}</small><div class="studio-inline-actions">${button('tab','查看版本',false,'data-tab="versions"')}${button('tab','使用此版本',true,'data-tab="use"')}</div>`:'<p>完成数据选择和算法核验后，在发布版本中创建第一个版本。</p>'}</section><section class="studio-panel"><h2>最近运行</h2>${runs.slice(0,4).map(run=>`<button class="studio-run-link" data-show-run="${run.id}"><strong>${run.purpose==='USE'?'模型使用':'算法核验'} · ${esc(run.versionName||'工作草稿')}</strong><span>${esc(status(run.status))} · ${run.objectIds.length} 家</span><small>${esc(displayAt(run.at))}</small></button>`).join('')||'<p>尚未运行，先维护算法并核验。</p>'}</section></div><section class="studio-panel"><h2>目标活动记录</h2><ol class="studio-audit">${state.audit.filter(entry=>entry.goalId===goal.id).slice(0,10).map(entry=>`<li><strong>${esc(entry.action)}</strong><span>${esc(entry.detail)}</span><small>${esc(displayAt(entry.at))}</small></li>`).join('')}</ol>${!goal.builtin&&!state.versions.some(v=>v.goalId===goal.id)&&!runs.length?button('delete-goal','删除未使用的草稿目标'):''}</section>`;
}
function scopePicker(ids, prefix, allowedIds=data.enterprises.map(c=>c.id)) {
  const snapshot=studio.read().datasets[prefix==='draft'?draft.dataKey:studio.read().versions.find(version=>version.id===selectedVersionId)?.dataKey]||data;
  const companies=snapshot.enterprises.filter(company=>allowedIds.includes(company.id));
  return `<div class="studio-scope-head"><strong><span data-scope-count="${prefix}">${ids.length}</span> / ${companies.length} 家企业</strong><div><button class="studio-text-button" data-scope-select="${prefix}" data-value="all">全选</button><button class="studio-text-button" data-scope-select="${prefix}" data-value="none">清空</button></div></div><div class="studio-scope-list">${companies.map(company=>`<label><input type="checkbox" data-scope="${prefix}" value="${company.id}" ${ids.includes(company.id)?'checked':''} ${busy?'disabled':''}><span><strong>${esc(company.name)}</strong><small>${esc(company.city)} · ${esc(company.industry)}</small></span></label>`).join('')}</div>`;
}
function dataMarkup(goal) {
  const dataset=studio.read().datasets[draft.dataKey],fields=MODEL_TEMPLATES[goal.type].inputs;
  return `<section class="studio-panel"><header><div><h2>已绑定的数据版本</h2><p>融资与风险演示快照 · ${dataset.enterprises.length} 家企业 / ${dataset.loans.length} 笔借款</p></div>${badge('数据已准备','success')}</header><label class="studio-field"><span>数据快照</span><select id="draft-dataset">${Object.entries(studio.read().datasets).map(([key,snapshot])=>`<option value="${key}" ${key===draft.dataKey?'selected':''}>${esc(snapshot.dataVersion)} · ${esc(snapshot.asOf)}</option>`).join('')}</select></label><dl class="studio-definition"><dt>观察日</dt><dd>${esc(dataset.asOf)}</dd><dt>数据版本</dt><dd>${esc(dataset.dataVersion)}</dd><dt>本体口径</dt><dd>${esc(dataset.ontologyVersion)}</dd><dt>本次算法输入</dt><dd>${fields.map(esc).join('、')}</dd><dt>金额口径</dt><dd>源数据为百万元，算法输入统一换算为元；历史风险评分作为独立输入保留。</dd></dl><details><summary>查看数据与原始样例</summary><p>使用联合态势的明确演示快照；模拟借款不是原始借据。核验不等于未来预测准确度评估。</p><div class="studio-table-scroll"><table><thead><tr><th>借款</th><th>企业</th><th>本金（百万元）</th><th>年利率</th><th>到期</th></tr></thead><tbody>${dataset.loans.slice(0,12).map(loan=>`<tr><td>${esc(loan.id)}</td><td>${esc(dataset.enterprises.find(c=>c.id===loan.enterpriseId)?.name)}</td><td>${modelNumber(loan.principal)}</td><td>${modelNumber(loan.rate)}%</td><td>${esc(loan.maturityDate)}</td></tr>`).join('')}</tbody></table></div><p>显示前12笔；发布与运行使用已选企业的完整存续借款。</p></details></section><section class="studio-panel"><h2>目标适用范围</h2><p>发布后，使用者可以在这组企业中选择具体对象运行。</p>${scopePicker(draft.objectIds,'draft')}<footer class="studio-panel-footer">${button('save-draft','保存数据与范围',true,busy?'disabled':'')}</footer></section>`;
}
function algorithmMarkup(goal) {
  const template=MODEL_TEMPLATES[goal.type],run=studio.read().runs.find(run=>run.id===goal.draft.validationRunId);
  return `<div class="studio-algorithm-grid"><section class="studio-panel"><header><div><h2>算法工作草稿</h2><p>${esc(template.method)} · 修订 ${draft.revision}</p></div>${badge('JavaScript')}</header><p>编辑的是工作草稿，已发布版本保持不变。</p><label class="studio-code-label" for="algorithm-code">运行脚本（input、parameters → 目标结果）</label><textarea id="algorithm-code" class="studio-code" spellcheck="false" ${busy?'disabled':''}>${esc(draft.code)}</textarea><div class="studio-inline-actions">${button('reset-code','恢复参考算法')}${button('copy-version','从当前发布版复制')}</div></section><section class="studio-panel"><h2>业务参数</h2><div class="studio-parameter-fields">${template.parameters.map(spec=>`<label><span>${esc(spec.label)} <small>${esc(spec.unit)}</small></span><input type="number" data-parameter="${spec.key}" value="${draft.parameters[spec.key]}" min="${spec.min}" max="${spec.max}" step="${['months','horizonDays','tenorMonths'].includes(spec.key)?1:0.1}" ${busy?'disabled':''}><small>${esc(spec.help)}</small></label>`).join('')}</div></section></div><section class="studio-panel"><header><div><h2>保存与核验</h2><p>核验检查对象、单位、历史基准及输出约束；不伪造未来实际结果或回测精度。</p></div><div class="studio-inline-actions">${button('save-draft','保存草稿',false,busy?'disabled':'')}${button('validate','保存并运行核验',true,busy?'disabled':'')}</div></header>${run&&goal.draft.validatedSignature===goal.draft.signature&&!dirty?`<ul class="studio-checks">${run.checks.map(check=>`<li>${glyph('circle-check')}${esc(check.label)} · 通过</li>`).join('')}</ul>${button('tab','下一步：发布版本',true,'data-tab="versions"')}`:'<p class="studio-notice">当前草稿需要核验。修改代码、参数或范围后，旧核验结果不会被套用。</p>'}${selectedRunId?modelResultMarkup(studio.read().runs.find(run=>run.id===selectedRunId)):run?modelResultMarkup(run):''}</section>`;
}
function versionsMarkup(goal) {
  const state=studio.read(),versions=state.versions.filter(version=>version.goalId===goal.id).reverse(),current=state.bindings[goal.id],eligible=goal.draft.validatedSignature&&goal.draft.validatedSignature===goal.draft.signature&&!dirty;
  const selected=versions.find(version=>version.id===selectedVersionId)||versions[0];
  return `<section class="studio-panel"><header><div><h2>发布当前草稿</h2><p>发布固定算法、参数、数据范围与核验依据，版本号不能覆盖。</p></div>${button('publish','发布新版本',true,eligible&&!busy&&!goal.archived?'':'disabled')}</header>${eligible?badge('当前草稿核验通过','success'):`<p class="studio-notice">先到“算法与核验”完成当前草稿核验。</p>`}</section><section class="studio-panel"><h2>已发布版本</h2><p>时间按北京时间显示；导出记录保留标准时间戳。</p><div class="studio-table-scroll"><table><thead><tr><th>版本</th><th>用途</th><th>范围</th><th>发布时间</th><th>当前应用</th><th>操作</th></tr></thead><tbody>${versions.map(version=>`<tr class="${selected?.id===version.id?'selected':''}"><td><button class="studio-text-button" data-inspect-version="${version.id}">${esc(version.name)}</button></td><td>${version.origin==='BUILTIN_REFERENCE'?'内置参考':'用户发布'}</td><td>${version.objectIds.length} 家</td><td>${esc(displayAt(version.publishedAt))}</td><td>${current===version.id?badge('当前','success'):state.availability[version.id]?badge('可使用'):badge('已停用')}</td><td><div class="studio-inline-actions">${current!==version.id&&state.availability[version.id]?button('bind','设为当前',false,`data-version="${version.id}"`):''}${button('availability',state.availability[version.id]?'停用':'启用',false,`data-version="${version.id}" data-enabled="${!state.availability[version.id]}"`)}</div></td></tr>`).join('')||'<tr><td colspan="6">完成核验后发布第一个版本。</td></tr>'}</tbody></table></div></section>${selected?`<section class="studio-panel"><header><div><h2>版本 ${esc(selected.name)} · 固定快照</h2><p>${esc(selected.note)}</p></div>${button('export-version','导出版本包',false,`data-version="${selected.id}"`)}</header><dl class="studio-definition"><dt>发布人</dt><dd>${esc(selected.publisher)}</dd><dt>算法与参数指纹</dt><dd class="studio-code-ref">${esc(selected.signature)}</dd><dt>核验记录</dt><dd><button class="studio-text-button" data-show-run="${selected.validationRunId}">${esc(selected.validationRunId)}</button></dd><dt>数据版本</dt><dd>${esc(state.datasets[selected.dataKey]?.dataVersion)} · ${esc(state.datasets[selected.dataKey]?.asOf)}</dd></dl><details><summary>查看固定参数与代码</summary><pre>${esc(JSON.stringify(selected.parameters,null,2))}</pre><pre class="studio-frozen-code">${esc(selected.code)}</pre></details></section>`:''}`;
}
function useMarkup(goal) {
  const state=studio.read(),versions=state.versions.filter(version=>version.goalId===goal.id),version=versions.find(version=>version.id===selectedVersionId)||versions.find(version=>version.id===state.bindings[goal.id]);
  selectedVersionId=version?.id||null;
  const runs=state.runs.filter(run=>run.goalId===goal.id),selected=runs.find(run=>run.id===selectedRunId);
  return `<section class="studio-panel"><h2>使用已发布版本</h2><p>使用固定发布快照计算，不读取尚未发布的草稿修改。</p><label class="studio-field"><span>发布版本</span><select id="use-version" ${busy?'disabled':''}>${versions.map(item=>`<option value="${item.id}" ${item.id===version?.id?'selected':''}>${esc(item.name)}${state.availability[item.id]?'':' · 已停用'}</option>`).join('')||'<option>尚未发布</option>'}</select></label>${version?`<details class="studio-runtime-parameters"><summary>本次运行情景（默认继承版本，可调整）</summary><div class="studio-parameter-fields">${runtimeParameterSpecs(goal.type).map(spec=>`<label><span>${esc(spec.label)} · ${esc(spec.unit)}</span><input type="number" data-run-parameter="${spec.key}" ${busy?'disabled':''} value="${runOverrides[spec.key]??version.parameters[spec.key]}" min="${spec.min}" max="${spec.max}" step="0.1"><small>${esc(spec.help)}</small></label>`).join('')}</div><p>运行实参单独记录，不修改发布版本。风险策略阈值须通过新版本维护。</p></details>${scopePicker(useIds,'use',version.objectIds)}`:'<p>先完成算法核验与版本发布。</p>'}<footer class="studio-panel-footer">${button('run-use','运行此版本',true,version&&state.availability[version.id]&&useIds.length&&!busy&&!goal.archived?'':'disabled')}</footer></section>${selected?`<section class="studio-panel">${modelResultMarkup(selected)}${selected.status==='SUCCEEDED'&&selected.purpose==='USE'?`<div class="studio-inline-actions">${button('open-exploration','在企业探索查看',true,`data-run="${selected.id}"`)}${button('export-run','导出运行结果',false,`data-run="${selected.id}"`)}</div>`:''}</section>`:''}<section class="studio-panel"><h2>核验与使用记录</h2><div class="studio-table-scroll"><table><thead><tr><th>时间</th><th>操作</th><th>版本</th><th>企业</th><th>状态</th><th></th></tr></thead><tbody>${runs.map(run=>`<tr><td>${esc(displayAt(run.at))}</td><td>${run.purpose==='USE'?'使用':'核验'}</td><td>${esc(run.versionName||'工作草稿')}</td><td>${run.objectIds.length} 家</td><td>${esc(status(run.status))}</td><td><button class="studio-text-button" data-show-run="${run.id}">查看结果</button></td></tr>`).join('')||'<tr><td colspan="6">运行记录会保留版本、范围、参数与结果。</td></tr>'}</tbody></table></div></section>`;
}
function status(value) { return ({RUNNING:'运行中',SUCCEEDED:'成功',FAILED:'失败',CANCELLED:'已停止'})[value]||value; }
function sourceMarkup() { const baseline=sourceReference.formalBaseline;return `<section class="studio-panel studio-source-reference"><h2>事件引用的历史评分基线</h2><p>${esc(baseline.name)} · ${esc(baseline.modelVersion)}</p><dl class="studio-definition"><dt>模型身份</dt><dd>${esc(baseline.modelId)}</dd><dt>引用版本</dt><dd>${esc(baseline.modelVersionId)}</dd><dt>数据版本</dt><dd>${esc(baseline.dataVersionId)}</dd><dt>评估观察日</dt><dd>${esc(baseline.resultEnvelope?.asOf)}</dd></dl><p>该历史评分版本只读。当前监控目标可以引用历史评分作为输入，其新提示不改写原评分。</p><details><summary>查看发布包与结果证据</summary><ul>${baseline.resultEnvelope?.evidenceRefs.map(ref=>`<li>${esc(ref)}</li>`).join('')}</ul></details></section>`; }
function openDialog(title,body,footer) { dialog.innerHTML=`<header><h2>${esc(title)}</h2>${iconButton('cancel-dialog','关闭','x')}</header><div class="studio-dialog-body">${body}</div><footer>${footer}</footer>`;if(!dialog.open)dialog.showModal();refreshIcons();dialog.querySelector('input,select,button')?.focus(); }
function openGoalForm(edit=false) { const goal=edit?getGoal():null;openDialog(edit?'编辑目标':'创建模型目标',`<form id="goal-form"><label class="studio-field"><span>目标类型</span><select name="type" ${edit?'disabled':''}>${Object.entries(MODEL_TEMPLATES).map(([type,template])=>`<option value="${type}" ${goal?.type===type?'selected':''}>${template.name}</option>`).join('')}</select></label><label class="studio-field"><span>目标名称</span><input name="name" maxlength="70" required value="${esc(goal?.name||'')}" placeholder="例如：2026年度融资成本预测"></label><label class="studio-field"><span>业务问题</span><textarea name="question" rows="3" required>${esc(goal?.question||MODEL_TEMPLATES.cost.question)}</textarea></label><label class="studio-field"><span>负责人</span><input name="owner" required value="${esc(goal?.owner||'')}" placeholder="模型负责人或团队"></label><p class="studio-dialog-error" role="alert"></p></form>`,`${button('cancel-dialog','取消')}${button(edit?'save-goal':'create-goal',edit?'保存目标':'创建并配置数据',true)}`); }
async function saveCurrentDraft() { const goal=getGoal();const saved=await studio.saveDraft(goal.id,{...draft},draft.revision);draft=structuredClone(saved.draft);dirty=false;return saved; }
function markDirty() { dirty=true;document.querySelector('.studio-dirty')?.removeAttribute('hidden');document.querySelector('[data-studio-action="publish"]')?.setAttribute('disabled',''); }
function download(name,value) { const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000); }
async function perform(action,target) {
  if(action==='cancel-dialog'){dialog.close();return;}
  if(action==='cancel-run'){controller?.abort();return;}
  if(busy)return;
  if(action==='archive-goal'){await studio.archiveGoal(selectedId,!getGoal().archived);showArchived=Boolean(getGoal().archived);render();return;}
  if(action==='catalog'){navigate(null);return;}
  if(action==='new-goal'||action==='edit-goal'){if(dirty){toast('请先保存当前修改，再创建或编辑目标信息');return;}openGoalForm(action==='edit-goal');return;}
  if(action==='create-goal'||action==='save-goal'){
    const form=dialog.querySelector('form');if(!form.reportValidity())return;const fields=Object.fromEntries(new FormData(form));
    try{if(action==='create-goal'){const goal=await studio.createGoal(fields,dataKey);dialog.close();navigate(goal.id,'data');}else{const saved=await studio.updateGoal(selectedId,fields);draft=structuredClone(saved.draft);dialog.close();render();}}catch(error){dialog.querySelector('.studio-dialog-error').textContent=error.message;}return;
  }
  if(action==='discard-navigate'){dirty=false;dialog.close();pendingNavigation?.();pendingNavigation=null;return;}
  if(action==='save-navigate'){await saveCurrentDraft();dialog.close();pendingNavigation?.();pendingNavigation=null;return;}
  if(action==='next'||action==='tab'){const next=target.dataset.nextTab||target.dataset.tab;if(action==='next'&&next===tab){if(tab==='algorithm')return perform('validate',target);if(tab==='versions')return perform('publish',target);if(tab==='use')return perform('run-use',target);document.querySelector('[data-scope="draft"]')?.focus();return;}navigate(selectedId,next);return;}
  if(action==='save-draft'){await saveCurrentDraft();render();toast('工作草稿已保存；原发布版本保持固定');return;}
  if(action==='reset-code'){draft.code=defaultCode(getGoal().type);draft.parameters=defaultParameters(getGoal().type);markDirty();render();return;}
  if(action==='copy-version'){const version=versionFor(getGoal());if(!version)throw Error('当前没有发布版本');Object.assign(draft,{code:version.code,parameters:structuredClone(version.parameters),dataKey:version.dataKey,objectIds:[...version.objectIds]});markDirty();render();return;}
  if(action==='validate'||action==='run-use'){
    if(action==='validate')await saveCurrentDraft();
    controller=new AbortController();busy=action==='validate'?'正在执行当前算法并核验业务约束…':`正在使用发布版本计算 ${useIds.length} 家企业…`;error='';render();
    try{const run=await studio.run(selectedId,action==='validate'?{signal:controller.signal}:{purpose:'USE',versionId:selectedVersionId,objectIds:useIds,parameterOverrides:runOverrides,signal:controller.signal});selectedRunId=run.id;persistView();draft=structuredClone(getGoal().draft);dirty=false;toast(action==='validate'?'当前草稿核验通过':'已形成可追溯的运行结果');}catch(caught){error=caught.message;}finally{busy='';controller=null;render();}return;
  }
  if(action==='publish'){
    if(dirty)throw Error('当前修改尚未核验，请先保存并运行核验');
    const count=studio.read().versions.filter(version=>version.goalId===selectedId).length;
    openDialog('发布模型版本',`<form id="publish-form"><p>将固定当前算法、参数、企业范围和核验记录。发布后可在企业探索中选择使用。</p><label class="studio-field"><span>版本号</span><input name="name" value="${count?`1.${count}.0`:'1.0.0'}" required pattern="[0-9]+\\.[0-9]+\\.[0-9]+"></label><label class="studio-field"><span>发布说明</span><textarea name="note" rows="3" required placeholder="说明本版本的业务假设和变更"></textarea></label><label class="studio-field"><span>发布人</span><input name="publisher" value="当前原型用户" required></label><p class="studio-dialog-error" role="alert"></p></form>`,`${button('cancel-dialog','取消')}${button('confirm-publish','发布版本',true)}`);return;
  }
  if(action==='confirm-publish'){const form=dialog.querySelector('form');if(!form.reportValidity())return;try{const version=await studio.publish(selectedId,Object.fromEntries(new FormData(form)));selectedVersionId=version.id;persistView();dialog.close();render();toast(`版本 ${version.name} 已发布，已设为当前应用版本`);}catch(caught){dialog.querySelector('.studio-dialog-error').textContent=caught.message;}return;}
  if(action==='bind'){await studio.bind(selectedId,target.dataset.version);selectedVersionId=target.dataset.version;render();toast('已切换当前应用版本，历史版本和结果保留');return;}
  if(action==='availability'){await studio.setAvailability(target.dataset.version,target.dataset.enabled==='true');render();return;}
  if(action==='delete-goal'){await studio.removeGoal(selectedId);navigate(null);return;}
  if(action==='export-version'){const version=studio.read().versions.find(version=>version.id===target.dataset.version);download(`${getGoal().name}-${version.name}.json`,{schemaVersion:'ofw.model-package.v1',goal:{id:selectedId,...version.goalDefinition},version,datasetIdentity:{dataVersion:data.dataVersion,asOf:data.asOf,ontologyVersion:data.ontologyVersion}});return;}
  if(action==='export-run'){const run=studio.read().runs.find(run=>run.id===target.dataset.run);download(`${getGoal().name}-${run.id}.json`,run);return;}
  if(action==='open-exploration'){const run=studio.read().runs.find(run=>run.id===target.dataset.run);parent.postMessage({type:'OFW_STUDIO_EXPLORE',goalId:selectedId,runId:run.id,objectIds:run.objectIds,selectedId:run.objectIds[0]},location.origin);return;}
}
document.addEventListener('click',event=>{
  const goal=event.target.closest('[data-studio-goal]');if(goal){navigate(goal.dataset.studioGoal,goal.dataset.targetTab||'overview');return;}
  const nextTab=event.target.closest('[data-studio-tab]');if(nextTab){navigate(selectedId,nextTab.dataset.studioTab);return;}
  const run=event.target.closest('[data-show-run]');if(run){if(busy)return;if(dirty){error='请先保存或放弃当前修改，再查看运行记录';render();return;}selectedRunId=run.dataset.showRun;const record=studio.read().runs.find(item=>item.id===selectedRunId);selectedVersionId=record?.versionId||selectedVersionId;tab='use';persistView();render();return;}
  const version=event.target.closest('[data-inspect-version]');if(version){if(busy)return;selectedVersionId=version.dataset.inspectVersion;persistView();render();return;}
  const scope=event.target.closest('[data-scope-select]');if(scope){if(busy)return;const values=scope.dataset.value==='all'?[...document.querySelectorAll(`[data-scope="${scope.dataset.scopeSelect}"]`)].map(input=>input.value):[];if(scope.dataset.scopeSelect==='draft'){draft.objectIds=values;markDirty();}else useIds=values;render();return;}
  const target=event.target.closest('[data-studio-action]');if(target)void perform(target.dataset.studioAction,target).catch(caught=>{error=caught.message;render();});
});
document.addEventListener('input',event=>{
  const target=event.target;
  if(target.id==='goal-search'){const start=target.selectionStart;search=target.value;render();const field=document.getElementById('goal-search');field.focus();try{field.setSelectionRange(start,start);}catch(_){}return;}
  if(target.id==='algorithm-code'){draft.code=target.value;markDirty();}
  if(target.matches('[data-run-parameter]')){runOverrides[target.dataset.runParameter]=target.valueAsNumber;}
  if(target.matches('[data-parameter]')){draft.parameters[target.dataset.parameter]=target.valueAsNumber;markDirty();}
});
document.addEventListener('change',event=>{
  const target=event.target;
  if(target.id==='draft-dataset'){draft.dataKey=target.value;const valid=new Set(studio.read().datasets[target.value].enterprises.map(company=>company.id));draft.objectIds=draft.objectIds.filter(id=>valid.has(id));markDirty();render();return;}
  if(target.id==='show-archived'){showArchived=target.checked;render();return;}
  if(target.id==='mobile-goal'){navigate(target.value||null);return;}
  if(target.name==='type'&&target.closest('#goal-form')){dialog.querySelector('[name="question"]').value=MODEL_TEMPLATES[target.value].question;return;}
  if(target.matches('[data-scope]')){const values=[...document.querySelectorAll(`[data-scope="${target.dataset.scope}"]:checked`)].map(input=>input.value);if(target.dataset.scope==='draft'){draft.objectIds=values;markDirty();}else useIds=values;document.querySelector(`[data-scope-count="${target.dataset.scope}"]`).textContent=values.length;const run=document.querySelector('[data-studio-action="run-use"]');if(run)run.disabled=!values.length||Boolean(getGoal()?.archived)||!studio.read().availability[selectedVersionId]||Boolean(busy);return;}
  if(target.id==='use-version'){selectedVersionId=target.value;useIds=initialUseIds();render();}
});
window.addEventListener('popstate',()=>{if(busy){controller?.abort();}selectedRunId=new URLSearchParams(location.search).get('run');selectedVersionId=new URLSearchParams(location.search).get('version');route();draft=getGoal()?structuredClone(getGoal().draft):null;dirty=false;useIds=initialUseIds();render();});
window.addEventListener('storage',event=>{if(event.key===MODEL_STORE_KEY&&!dirty&&!busy){draft=getGoal()?structuredClone(getGoal().draft):null;render();}});
window.addEventListener('message',event=>{if(event.source!==parent||event.origin!==location.origin)return;if(event.data?.type==='OFW_WORKSPACE_CONTEXT'){const context=event.data.context||{};hostIds=[...new Set(context.activeObjectRef?.id?[context.activeObjectRef.id]:context.objectSetRef?.objectIds||[])].map(id=>id.replace(/^S003-/,''));if(tab==='use'&&!dirty&&!busy){useIds=initialUseIds();render();}}});
window.addEventListener('pagehide',()=>controller?.abort(),{once:true});
async function start() {
  root.innerHTML='<div class="studio-loading" role="status">正在准备模型目标与参考算法…</div>';
  try{const response=await fetch('/data/portfolio.json');if(!response.ok)throw Error('模型数据读取失败');data=await response.json();dataKey=await studio.initialize(data);route();if(selectedId&&!getGoal())selectedId=null;draft=getGoal()?structuredClone(getGoal().draft):null;selectedVersionId=selectedVersionId||getGoal()&&studio.read().bindings[selectedId];useIds=initialUseIds();if(query.get('focusModel')){const response=await fetch('/model-api/v1/model-management/context?scenarioId=S003');if(response.ok)sourceReference=(await response.json()).state;}render();announce();window.__MODEL_STUDIO_DEBUG__={read:()=>studio.read(),current:()=>({selectedId,tab,dirty,busy})};}catch(caught){root.innerHTML=`<section class="studio-panel"><h1>模型与算法</h1><p role="alert">${esc(caught.message)}</p><button class="studio-button" onclick="location.reload()">重新读取</button></section>`;}
}
void start();
