(function(){
  const M=window.DE_MANIFEST,root=document.getElementById("compare");
  const variants=M.variants;let screen=M.screens[0];let chosen=null;let layout="readable";
  try{const saved=JSON.parse(localStorage.getItem("de.review-v3.choice")||"null");if(saved&&saved.variant)chosen=saved.variant;}catch(e){}
  function esc(x){return String(x).replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));}
  function entry(v){return `方案${v}.html${screen.route}`;}
  function fitCompactFrames(){if(layout!=="compact"||matchMedia("(max-width:1050px)").matches)return;document.querySelectorAll(".frame-wrap").forEach(w=>{const f=w.querySelector("iframe");const scale=Math.min(1,w.clientWidth/1280);f.style.transform=`scale(${scale})`;w.style.height=`${Math.round(720*scale)}px`;});}
  function render(){root.innerHTML=`<header class="top"><div class="title"><span class="mark">DE</span><div><h1>数据工程 · 方案 B 第二轮逐页对比</h1><p>业务合同与页面范围不变，只比较信息密度、面板分工和动效节奏</p></div></div><div class="controls"><div class="layout-toggle" role="group" aria-label="对比布局"><button data-layout="readable" class="${layout==="readable"?"active":""}">逐版阅读</button><button data-layout="compact" class="${layout==="compact"?"active":""}">三版缩略</button></div><label>评审页面 <select id="screen-select">${M.screens.map(s=>`<option value="${s.id}" ${s.id===screen.id?"selected":""}>${esc(s.label)}</option>`).join("")}</select></label><button id="previous">上一页</button><button id="next" class="primary">下一页</button></div></header><div class="context"><div><strong>${esc(screen.label)}</strong> <span>· 第 ${M.screens.indexOf(screen)+1} / ${M.screens.length} 页</span></div><span class="note">B1 均衡、B2 高密度、B3 聚焦分析；右栏只配置，底栏查看节点详情与证据。</span></div><main class="boards ${layout}">${variants.map(v=>`<section class="board"><div class="board-head"><div class="variant"><span class="variant-key">${v.key}</span><div><strong>${esc(v.title)}</strong><small>${esc(v.focus)} · ${esc(v.motion)}</small></div></div><div class="board-actions"><button class="choose ${chosen===v.key?"selected":""}" data-choose="${v.key}">${chosen===v.key?"已选择":"选择此版"}</button><a href="${entry(v.key)}" target="_blank">打开完整方案</a></div></div><div class="frame-wrap"><iframe title="${esc(v.title)} · ${esc(screen.label)}" src="${entry(v.key)}"></iframe></div></section>`).join("")}</main><div class="selection" id="selection"></div>`;document.querySelectorAll("iframe").forEach(f=>f.addEventListener("load",fitCompactFrames,{once:true}));requestAnimationFrame(fitCompactFrames);}
  function switchTo(index){const next=Math.max(0,Math.min(M.screens.length-1,index));screen=M.screens[next];render();}
  document.addEventListener("change",e=>{if(e.target.id==="screen-select"){screen=M.screens.find(s=>s.id===e.target.value)||M.screens[0];render();}});
  document.addEventListener("click",e=>{const layoutButton=e.target.closest("[data-layout]");if(layoutButton){layout=layoutButton.dataset.layout;render();return;}if(e.target.id==="previous")switchTo(M.screens.indexOf(screen)-1);else if(e.target.id==="next")switchTo(M.screens.indexOf(screen)+1);else{const b=e.target.closest("[data-choose]");if(b){chosen=b.dataset.choose;localStorage.setItem("de.review-v3.choice",JSON.stringify({pageId:screen.id,variant:chosen,selectedAt:new Date().toISOString()}));render();const n=document.getElementById("selection");n.textContent=`已记录：${screen.label}选择方案 ${chosen}`;n.classList.add("show");setTimeout(()=>n&&n.classList.remove("show"),2200);}}});
  window.addEventListener("resize",fitCompactFrames);
  render();
})();
