import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {mkdir,writeFile,readFile} from 'node:fs/promises';
const root=process.env.BASE_URL||'http://127.0.0.1:4504';
const out=new URL('../../../../outputs/m07-portrait-20260910/final/',import.meta.url);await mkdir(out,{recursive:true});
const browser=await chromium.connectOverCDP(process.env.CDP_URL||'http://127.0.0.1:4506');
const context=await browser.newContext({viewport:{width:1440,height:900},reducedMotion:'reduce',acceptDownloads:true});
const page=await context.newPage();page.setDefaultTimeout(20000);const errors=[],checks=[];page.on('pageerror',e=>errors.push(e.message));
const B='PRD-40A100000000B2C7',D='PRD-843300000000D4E2';
async function click(loc){await loc.evaluate(e=>e.scrollIntoView({block:'center',inline:'nearest',behavior:'instant'}));const b=await loc.boundingBox();assert.ok(b?.width&&b?.height,'click target visible');await page.mouse.click(b.x+b.width/2,b.y+b.height/2);}
async function frame(id='m07'){await page.waitForFunction(id=>document.querySelector('#module-frame')?.dataset.moduleId===id&&document.querySelector('#module-frame')?.contentDocument?.readyState==='complete',id,{polling:100});const f=await(await page.locator('#module-frame').elementHandle()).contentFrame();if(id==='m07')await f.waitForFunction(()=>window.__OFW_M07_DEBUG__,null,{polling:100});return f;}
async function capture(name,f){const s=await context.newCDPSession(page);const shot=await s.send('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});await writeFile(new URL(name+'.png',out),Buffer.from(shot.data,'base64'));await s.detach();await writeFile(new URL(name+'.json',out),JSON.stringify({url:page.url(),frame:f.url(),text:await f.locator('body').innerText(),state:await f.evaluate(()=>window.__OFW_M07_DEBUG__?.getState()||null),errors},null,2));checks.push(name);console.log('PASS '+name);}
async function tab(f,name){await click(f.locator(`[data-detail-tab="${name}"]`).filter({visible:true}).first());}
async function idle(f){await f.evaluate(()=>{window.__portraitIdle=0;window.__portraitObserver=new MutationObserver(ms=>__portraitIdle+=ms.length);__portraitObserver.observe(document.body,{childList:true,subtree:true});});await page.waitForTimeout(600);await f.evaluate(()=>__portraitIdle=0);await page.waitForTimeout(2000);const changes=await f.evaluate(()=>{__portraitObserver.disconnect();return __portraitIdle;});assert.equal(changes,0,'object page remains idle without interaction');}
try{
 await page.goto(root+'/',{waitUntil:'domcontentloaded'});await click(page.locator('[data-primary-nav][data-route="#module/m07"]'));let f=await frame();
 assert.equal(await f.locator('.result-table tbody tr').count(),30);
 await f.locator('#directory-type').selectOption('OBJ-INVESTMENT-PRODUCT');assert.equal(await f.locator('.result-table tbody tr').count(),4);
 await click(f.locator(`.result-table [data-preview-object="${B}"]`));assert.ok(await f.locator('#preview-pane').isVisible());
 for(const type of ['relations','events','history','evidence','properties']){await click(f.locator(`#preview-pane [data-preview-tab="${type}"]`));assert.ok((await f.locator('.preview-content').innerText()).length>10);}
 await capture('01-product-directory-preview',f);
 await click(f.locator(`.result-table [data-select-object="${B}"]`));await click(f.locator(`.result-table [data-select-object="${D}"]`));
 await click(f.locator('#explore-selection'));assert.equal(await f.evaluate(()=>__OFW_M07_DEBUG__.getState().lens),'selection');
 assert.equal(await f.locator('#canvas-stage tbody tr').count(),2);
 await click(f.locator('[data-selection-view="trends"]'));assert.equal(await f.locator('.portrait-chart').count(),2);
 const paths=await f.locator('.portrait-chart .chart-line').evaluateAll(es=>es.map(e=>e.getAttribute('d')));assert.notEqual(paths[0],paths[1]);
 const dimensions=await f.locator('[data-selection-dimension] option').evaluateAll(es=>es.map(e=>({value:e.value,text:e.textContent})));
 assert.equal(dimensions.length,4);await f.locator('[data-selection-dimension]').selectOption(dimensions.find(d=>d.text.includes('投资金额')).value);
 await capture('02-product-timeseries-parallel',f);
 await f.locator('#context-time-start').fill('2026-08-01');assert.equal(await f.locator('.portrait-chart').count(),0);assert.ok((await f.locator('#canvas-stage').innerText()).includes('所选区间无观测'));
 await f.locator('#context-time-start').fill('2025-02-21');await f.locator('#context-time-end').fill('2026-07-17');
 await click(f.locator('[data-selection-view="compare"]'));assert.equal(await f.locator('.selection-bars article').count(),2);await capture('03-product-latest-comparison',f);
 await click(f.locator('[data-selection-view="cards"]'));const values=await f.locator('[data-selection-dimension] option').evaluateAll(es=>es.map(e=>e.value));await f.locator('[data-selection-dimension]').selectOption(values[1]);assert.equal(await f.locator('.selection-tile .tile-value').count(),2);await capture('04-dimension-tiles',f);
 await click(f.locator('#workspace-context .context-token[data-open-mobile="path"]'));assert.ok(await f.locator('#drawer').evaluate(d=>d.open));assert.equal(await f.locator('#drawer [data-set-member]').count(),2);await f.locator('#drawer').press('Escape');assert.equal(await f.locator('#drawer').evaluate(d=>d.open),false);
 await click(f.locator('[data-selection-view="trends"]'));await click(f.locator('#save-exploration'));await f.locator('#exploration-name').fill('基金B与D持仓时序');await click(f.locator('#save-form button[value="default"]'));
 await page.reload({waitUntil:'domcontentloaded'});f=await frame();assert.equal(await f.evaluate(()=>__OFW_M07_DEBUG__.getState().selectionView),'trends');assert.equal(await f.locator('.portrait-chart').count(),2);await idle(f);await capture('05-selection-reload-and-idle',f);
 await click(f.locator('#continue-analysis'));await click(f.locator('#drawer [data-navigate-module="report"]'));let r=await frame('report');await r.getByRole('button',{name:'查看模型监测草稿',exact:true}).waitFor({state:'attached'});await click(r.getByRole('button',{name:'查看模型监测草稿',exact:true}));
 const report=await page.evaluate(()=>OFW_WORKFLOW.readReport('S005'));const block=report.contentBlocks.at(-1);assert.equal(block.rows.length,2);assert.equal(block.series.length,2);assert.deepEqual(block.workspaceContext.objectSetRef.objectIds,[B,D]);assert.equal(block.workspaceContext.activeObjectRef,null);
 const download=page.waitForEvent('download');await click(r.locator('[data-ofw-report-action="export"]'));await(await download).saveAs(new URL('product-parallel-report.html',out).pathname);await capture('06-set-report',r);await click(r.locator('[data-ofw-report-action="source"]').last());f=await frame();assert.equal(await f.evaluate(()=>__OFW_M07_DEBUG__.getState().selectionView),'trends');
 await click(f.locator('#workspace-context [data-route="discover"]'));await f.locator('#directory-type').selectOption('OBJ-ENTERPRISE');await click(f.locator('.result-table [data-select-object="ENT-001"]'));await click(f.locator('#explore-selection'));assert.equal(await f.evaluate(()=>__OFW_M07_DEBUG__.getState().selectionView),'list');assert.equal(await f.locator('[data-selection-view="compare"]').isDisabled(),true);assert.equal(await f.locator('[data-selection-view="trends"]').isDisabled(),true);
 await click(f.locator('[data-selection-view="cards"]'));assert.equal(await f.locator('.selection-tile').count(),3);await capture('07-mixed-object-basic-tiles',f);
 await click(f.locator('.selection-tile [data-open-object="ENT-001"]'));assert.equal(await f.locator('.portrait-map svg').count(),1);assert.ok(await f.locator('.portrait-map .province-boundaries').evaluate(e=>e.getBBox().width>200));assert.equal(await f.locator('.business-steps').count(),0);await tab(f,'events');assert.ok((await f.locator('[data-detail-panel="events"]').innerText()).includes('评估截至日'));await tab(f,'profile');await capture('08-enterprise-map-portrait',f);
 await click(f.locator('[data-open-canvas]'));let o=await frame('ontology');await o.locator('.canvas-node[data-node="OBJ-ENTERPRISE"]').waitFor({state:'attached'});assert.ok(o.url().includes('tab=canvas'));assert.ok(await o.locator('.canvas-node[data-node="OBJ-ENTERPRISE"]').evaluate(e=>e.style.outline.includes('4px')));await capture('09-focused-ontology-canvas',o);await click(page.locator('[data-action="return-business-overview"]'));f=await frame();assert.equal(await f.evaluate(()=>__OFW_M07_DEBUG__.getState().activeId),'ENT-001');
 await click(f.locator('#workspace-context [data-route="discover"]'));await f.locator('#directory-type').selectOption('OBJ-ENTERPRISE');await click(f.locator('.result-table [data-open-object="ENT-020"]'));await tab(f,'relations');assert.equal(await f.locator('.portrait-relations-diagram').count(),1);await tab(f,'events');assert.ok((await f.locator('[data-detail-panel="events"]').innerText()).includes('融资成本偏高'));await capture('10-unified-events',f);
 await tab(f,'actions');await click(f.locator('[data-business-action="AR-RUN-MSVJWKPO-002-UNIT-553"]'));let d=await frame('decision');await d.getByRole('button',{name:'确认承接',exact:true}).waitFor({state:'attached'});await click(d.getByRole('button',{name:'确认承接',exact:true}));await click(d.getByRole('button',{name:'开始处理',exact:true}));await click(d.getByRole('button',{name:'完成待办',exact:true}));await d.locator('.dc-modal textarea').fill('本轮完成融资业务复核，后续成本和风险仍按新数据跟踪。');await click(d.getByRole('button',{name:'确认完成',exact:true}));await d.waitForFunction(()=>JSON.parse(localStorage.getItem('ontology3-decision-center-review-v2-portfolio-state-v8')).tasks.find(t=>t.id==='TD-6872111633').status==='completed',null,{polling:100});await click(page.locator('[data-action="return-business-overview"]'));f=await frame();assert.equal(await f.evaluate(()=>__OFW_M07_DEBUG__.getState().detailTab),'actions');assert.ok((await f.locator('[data-detail-panel="actions"]').innerText()).includes('本轮完成融资业务复核'));await capture('11-action-progress-return',f);await tab(f,'events');assert.ok((await f.locator('[data-detail-panel="events"]').innerText()).includes('办理时间'));
 await tab(f,'profile');await idle(f);assert.ok(await f.locator('#enterprise-budget').isVisible());
 for(const [width,height] of [[1440,900],[1280,720],[390,844],[320,844]]){
  await page.setViewportSize({width,height});await click(f.locator('[data-manage-set]'));assert.ok(await f.locator('#drawer').evaluate(d=>d.open));assert.ok(await f.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await capture('12-set-dialog-'+width,f);await f.locator('#drawer').press('Escape');await tab(f,'profile');await f.locator('.portrait-identity').evaluate(e=>e.scrollIntoView({block:'start',behavior:'instant'}));await capture('13-portrait-'+width,f);
 }
 await click(f.locator('#workspace-context [data-route="discover"]'));await f.locator('#directory-type').selectOption('OBJ-INVESTMENT-PRODUCT');await click(f.locator(`.result-card[data-preview-object="${B}"] strong`).first());assert.ok(await f.locator('#drawer').evaluate(d=>d.open));await click(f.locator('#drawer [data-preview-tab="history"]'));assert.ok((await f.locator('#drawer').innerText()).includes('关联持仓时序'));await capture('14-mobile-preview',f);await f.locator('#drawer').press('Escape');
 assert.deepEqual(errors,[]);await writeFile(new URL('result.json',out),JSON.stringify({status:'passed',checks,errors,port:root},null,2));
}catch(error){await writeFile(new URL('failure.json',out),JSON.stringify({error:error.stack,checks,errors,frames:await Promise.all(page.frames().map(async f=>({url:f.url(),text:await f.locator('body').innerText().catch(()=>'' )})))},null,2));throw error;}finally{await context.close();await browser.close();}
