(()=>{
  'use strict';
  const V=window.REVIEW_VIEWS,{D,esc,icon,btn,tag,fmt,company,themes,pages,phases,cases}=V;
  const root=document.getElementById('app'),bar=document.getElementById('review-bar'),drawer=document.getElementById('drawer'),menu=document.getElementById('context-menu');
  const params=new URLSearchParams(location.hash.slice(1));
  const state={variant:['a','b','c'].includes(params.get('style'))?params.get('style'):'a',page:pages[params.get('page')]?params.get('page'):'map',reducedMotion:matchMedia('(prefers-reduced-motion: reduce)').matches,scope:'all',queryTopic:'risk',question:'哪些企业需要优先跟进？请说明依据。',display:'table',saved:false,selected:'ENT-020',search:'',industry:'',perspective:'risk',relations:['financing'],mapView:'map',zoom:1,globalRelations:false,caseId:'case-20',caseFilter:'all',caseStages:{'case-20':1,'case-17':1,'case-18':1,'case-07':0,'case-19':2},caseEvents:[],note:'',node:'enterprise',graphMode:'semantic',propertyTab:'fields',ontologyMode:'published',validated:false,publishedNew:false};
  let toastTimer,previousFocus;
  const original='http://127.0.0.1:4594/designs/prototype-work/v1.5/composite/s001-e2e-integration/index.html';
  const notify=text=>{const el=document.getElementById('toast');el.textContent=text;el.classList.add('open');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('open'),3300);};
  function route(){const p=new URLSearchParams({style:state.variant,page:state.page});history.replaceState(null,'','#'+p);}
  function render(){document.body.dataset.glass=state.variant;document.body.classList.toggle('motion-reduced',state.reducedMotion);bar.innerHTML=V.reviewBar(state);root.dataset.variant=state.variant;root.className='variant-'+state.variant;root.innerHTML=V.shell(state);route();menu.hidden=true;document.dispatchEvent(new CustomEvent('glass-rendered',{detail:{page:state.page,variant:state.variant,reducedMotion:state.reducedMotion}}));document.title=themes[state.variant].label+' · '+themes[state.variant].name+' / '+pages[state.page][0]+' · 智财问策';}
  function closeDrawer(){drawer.close();previousFocus?.focus?.();}
  function showDrawer(title,subtitle,content){previousFocus=document.activeElement;drawer.innerHTML=`<header class="drawer-head"><div><h2 id="drawer-title">${title}</h2><p>${subtitle}</p></div><button type="button" class="drawer-close" data-action="close-drawer" aria-label="关闭面板">${icon('x')}</button></header><div class="drawer-body">${content}<p class="preview-only">独立视觉方案预览。这里的演示操作不修改现有原型中的数据、模型、本体或办理记录。</p></div>`;if(!drawer.open)drawer.showModal();drawer.scrollTop=0;window.GLASS_MOTION?.drawer();}
  function entityInfo(id){const e=company(id||state.selected),m=e.metrics;showDrawer(e.name,'企业全景 · 保留原身份 '+e.id,`<div class="readout">${tag(e.riskTier,e.riskTier==='红灯'?'red':'amber')}<h3>${e.industry} · ${e.city}</h3><dl><dt>历史评分</dt><dd>${fmt(e.riskScore)}分</dd><dt>融资成本</dt><dd>${fmt(m.cost)}% / 年</dd><dt>融资余额</dt><dd>${fmt(m.balance/100)}亿元</dd><dt>观察日</dt><dd>${D.asOf}</dd></dl></div><h3>单对象视图</h3><div>${['基本信息','融资明细','经营指标','预算执行','风险事件','关系与担保','行动与进展','证据与口径'].map(t=>`<span class="function-chip">${t}</span>`).join('')}</div><p>原单对象画像的完整内容在后续重构中保留。选型页展示主要入口和信息层级。</p>${btn('围绕这家企业提问','object-query','message-square','primary',`data-entity="${e.id}"`)} ${btn('查看关联事项','to-decision','git-pull-request-arrow')}<h3>继续查看原功能基线</h3><a class="btn" href="${original}#module/m07" target="_blank" rel="noopener">在新标签打开当前对象全景 ${icon('external-link')}</a>`);}
  function evidence(id){const e=company(id||state.selected);showDrawer('结果依据与业务口径','对象、观察日、数据、本体和模型保持可追溯',`<h3>当前引用</h3><dl><dt>对象范围</dt><dd>${state.scope==='all'?'集团21家金融视角企业':company(state.scope).name}</dd><dt>观察日</dt><dd>${D.asOf}</dd><dt>风险结果</dt><dd>历史评分 · 模型1.0.2 · 结果版本1.1.0</dd><dt>金融演示数据</dt><dd>${D.dataVersion}</dd><dt>金融语义</dt><dd>${D.ontologyVersion}</dd></dl><div class="readout"><b>注意来源边界</b><p>历史风险评分与演示借款是不同来源；地图和成本图使用原金融演示快照，风险分档沿用原评估结果，互不冒充因果解释。</p></div><h3>${e.name}的关联依据</h3><p>${e.evidenceRefs.map(esc).join('<br>')}</p><h3>固定结果的恢复</h3><p>重构继续保留原运行编号、精确版本与原始证据。版本或数据不一致时，阻止沿用结果并提示返回来源恢复；历史记录仍可只读回看。</p>${btn('查看模型与版本','models','workflow')} ${btn('查看完整事项回溯','trace','route')}<details><summary>源指纹</summary><p class="mono">${D.digest}</p></details>`);}
  function designNotes(){showDrawer('从视频提炼的玻璃工作台','同一风格语言的三种延展 · 功能保持一致',`<p>参考视频是“北京到新疆自驾攻略”的路书工作台。可以看到深蓝半透明层、蓝金强调、大幅中央地图和两侧信息栏，以及对象切换时的地图视角过渡。</p><div class="readout"><b>转化为智财问策的五个设计要点</b><p>环境背景提供景深；玻璃层负责分区；细高光界定边界；语义颜色标识重点；动效解释位置与状态变化。</p></div><p>视频内界面占屏较小，下述透明度、模糊和动效时长是本项目的设计取值，不声称是源视频的精确参数。玻璃应用于容器，文字和表格始终保持可读。</p>${Object.entries(themes).map(([k,t])=>`<article class="design-option ${state.variant===k?'current':''}"><header><i class="swatch ${k}"></i><h3>${t.label} · ${t.name}</h3></header><p>${t.summary}</p><div class="design-tokens">${t.colors.map(c=>`<i style="background:${c}" title="${c}"></i>`).join('')}</div><p><b>适合：</b>${t.fit}<br><b>取舍：</b>${t.tradeoff}</p>${btn('查看这套四页方案','choose-style','arrow-right','primary',`data-choice="${k}"`)}</article>`).join('')}<h3>动效与业务边界</h3><p>切页以淡入和短距离位移过渡；地图定位沿当前位置移动；关系线一次描绘；详情抽屉平滑展开。每次动效结束即停止，无背景永久动画。系统减少动态效果偏好和手动低动效开关都有效。</p><p><a href="https://www.douyin.com/video/7685796717187675274" target="_blank" rel="noopener">查看原视频参考 ↗</a></p><h3>实现节奏</h3><p>本轮只做视觉选型。你在对话中选定01、02或03后，再统一重构导航、排版和各模块组件，并逐项回归原功能。</p>`);}
  function preservation(){showDrawer('功能保留与重构边界','布局可以调整，原有业务能力必须继续可用',`<h3>问数工作台</h3><p>推荐问题、业务主题、上下文澄清、追问、历史会话、文字／表格／图表切换、保存视图、导出、固定证据和人工确认行动。</p><h3>对象地图</h3><p>四个分析视角、筛选与框选、融资／授信／担保选择、取消聚焦、全局关系、地图／网络／矩阵／明细、画像、问数、模型、保存探索与时序。</p><h3>决策中心</h3><p>统一接收待办和方案，保留来源与负责人筛选、原事项回溯、建议、批准／退回／拒绝、承接、执行凭证、效果复核、补充事项及报告。</p><h3>本体工作台</h3><p>对象、属性、关系、指标、规则、行动、数据资产绑定、语义和血缘、校验、发布、版本、正式数据切换、消费证据。</p><div class="readout"><b>不因首屏未展示而删除功能</b><p>首屏聚焦结论与主操作；低频操作进入明确的抽屉、菜单和下钻。后续实施沿用现有状态与协议，逐项回归。</p></div><h3>本轮预览可操作</h3><p>风格／页面切换；问数样例与结果视图；地图选择、关系、右键、取消及缩放；事项阶段演示；本体节点、血缘、草稿校验发布演示。其他入口提供功能承载说明或原页面链接。</p><a href="README.md" target="_blank">查看完整功能映射清单 ↗</a>`);}
  function modelInfo(){showDrawer('模型与算法','完整构建链路保留在模型目标内',`<h3>融资成本预测</h3><div class="readout"><b>存量融资成本预测</b><p>读取原借据首次重定价日、周期与计息口径，按指定时点的利率情景计算传导。</p><b>AI 推荐融资置换</b><p>同评级银行相近期限优先，板块均值兜底；具体建议可进入决策中心询价。</p><b>存量合同延续</b><p>仅历史序列的Holt阻尼外推，不叠加续作或人为利率情景。</p></div><h3>保留的模型操作</h3><p>目标 → 输入绑定 → 算法构建 → 输出约定 → 模拟核验 → 版本发布。开发模拟、已核验、候选试用、已发布与当前应用分别展示。</p><a class="btn primary" href="${original}#module/modeling" target="_blank" rel="noopener">在原型中查看模型模块 ↗</a>`);}
  function trace(){const c=cases.find(c=>c.id===state.caseId)||cases[0];showDrawer('事项从哪里来','一条事项贯穿来源、研判、办理与效果',`<h3>${company(c.entity).name} · ${c.title}</h3><ol><li><b>固定数据与口径</b><p>观察日2025-12-31，对象身份${c.entity}，保留精确数据与语义版本。</p></li><li><b>${c.id==='case-07'?'AI置换运行':'历史模型评估'}</b><p>${c.id==='case-07'?'原借据、参考利率样本、匹配层级和运行版本随建议保存。':'原评分与风险分档可回到正式评估结果核对。'}</p></li><li><b>形成待处理事项</b><p>建议不等于批准，保留提交对象、原因、负责人和期限。</p></li><li><b>决定与办理</b><p>${state.caseEvents.length?state.caseEvents.map(esc).join('<br>'):'本选型页尚未进行阶段演示。'}</p></li><li><b>效果复核</b><p>执行完成后核对后续数据。未达成或证据不足时保留待复核，可发起补充事项。</p></li></ol>${btn('查看固定来源','evidence','shield-check')} ${btn('查看办理阶段','close-drawer','arrow-left')}`);}
  function handleCase(){const id=state.caseId,stage=state.caseStages[id]??1,note=state.note.trim();if(stage===5){trace();return;}const c=cases.find(x=>x.id===id);if(stage===1){showDrawer('批准并分办','决定范围与执行安排需明确',`<p>${company(c.entity).name} · ${c.title}</p><form id="case-operation" data-stage="${stage}"><label>执行负责人<input name="owner" required value="${company(c.entity).industry}业务负责人"></label><label>办理期限<input name="due" type="date" required value="2026-09-25"></label><label>批准意见<textarea name="note" required placeholder="明确批准的安排、前提和后续材料">${esc(note)}</textarea></label><p class="drawer-error"></p><button class="btn primary" type="submit">确认批准安排（演示）</button></form><p>本操作只演示UI状态，不发送外部消息或创建原型业务任务。</p>`);return;}
    if(stage===3){showDrawer('登记执行凭证','完成办理与验证效果是两个独立步骤',`<form id="case-operation" data-stage="3"><label>执行材料编号<input name="reference" required placeholder="填写办理材料或凭证编号"></label><label>执行说明<textarea name="note" required>${esc(note)}</textarea></label><p class="drawer-error"></p><button class="btn primary" type="submit">登记并确认执行完成（演示）</button></form>`);return;}
    if(stage===4){showDrawer('效果复核','依据后续证据判断，不由完成状态自动推断',`<form id="case-operation" data-stage="4"><label>复核结论<select name="outcome"><option value="met">已达成</option><option value="unmet">未达成</option><option value="insufficient">证据不足</option></select></label><label>效果材料编号<input name="reference" required placeholder="后续数据或复核材料编号"></label><label>复核说明<textarea name="note" required>${esc(note)}</textarea></label><p class="drawer-error"></p><button class="btn primary" type="submit">记录效果复核（演示）</button></form>`);return;}
    state.caseStages[id]=stage+1;state.caseEvents.push(phases[stage]+' → '+phases[stage+1]+' · 演示操作');state.note='';render();notify('已进入'+phases[stage+1]+'（仅选型页演示）');}
  function versions(){showDrawer('语义版本与正式使用','发布版本不可变，正式数据组合独立切换',`<h3>企业业务全景本体</h3><table><thead><tr><th>状态</th><th>版本</th><th>含义</th></tr></thead><tbody><tr><td>已发布语义</td><td>V2</td><td>对象、关系和发布时映射固定</td></tr><tr><td>当前正式使用</td><td>原型中的既有绑定</td><td>需按精确版本单独核对</td></tr>${state.ontologyMode==='draft'?`<tr><td>本次工作草稿</td><td>未发布</td><td>${state.validated?'本次校验通过':'尚需校验'}</td></tr>`:''}${state.publishedNew?'<tr><td>选型演示发布</td><td>V3 · 演示</td><td>没有自动切换正式使用</td></tr>':''}</tbody></table><div class="readout"><b>发布 ≠ 当前正式使用</b><p>原本体版本、映射、刷新目标、消费证据和历史记录都继续保留。此页不修改原型中的任何语义版本。</p></div>${btn('修订工作草稿','revise','git-branch','primary')} ${btn('查看消费证据','consumption','route')}`);}
  function doAction(action,target){switch(action){
    case 'close-drawer':closeDrawer();break;
    case 'motion-replay':window.GLASS_MOTION?.replay();break;
    case 'motion-toggle':state.reducedMotion=!state.reducedMotion;render();notify(state.reducedMotion?'已开启低动效：停止非必要位移与描线':'已恢复交互动效：仅响应操作，完成即停止');break;
    case 'design-notes':designNotes();break;
    case 'preservation':preservation();break;
    case 'choose-style':state.variant=target.dataset.choice;render();closeDrawer();notify('已切换至'+themes[state.variant].label+' · '+themes[state.variant].name+'，可继续比较四个页面');break;
    case 'presentation':document.body.classList.add('presentation');document.getElementById('return-review').hidden=false;notify('已隐藏评审工具栏；右下角返回，Esc退出演示。');break;
    case 'scope':showDrawer('对象范围与观察口径','跨页面保留对象、时间及版本',`<form id="scope-form"><label>分析对象<select name="scope"><option value="all">集团 · 全部21家企业</option>${V.riskCompanies.map(e=>`<option value="${e.id}" ${state.scope===e.id?'selected':''}>${e.name}</option>`).join('')}</select></label><div class="readout"><b>观察日 2025-12-31</b><p>风险事实引用原评估，融资指标引用原演示快照。正式身份和技术版本可以在依据中展开。</p></div><button type="submit" class="btn primary">应用对象范围</button></form>`);break;
    case 'evidence':evidence(target.dataset.entity);break;
    case 'portrait':entityInfo(target.dataset.entity);break;
    case 'history':showDrawer('会话与最近工作','保留原问题、上下文及固定结果',`<h3>当前演示会话</h3><article class="design-option"><b>集团债务风险跟进</b><p>21家企业 · 历史评估2025-12-31</p>${btn('打开会话','topic-risk','arrow-right')}</article><article class="design-option"><b>重点企业融资成本比较</b><p>三家重点企业 · 余额加权口径</p>${btn('打开会话','topic-finance','arrow-right')}</article><p>正式原型中的历史运行与保存视图保留，设计中收进独立会话面板，释放主工作空间。</p>`);break;
    case 'new-chat':state.page='query';state.queryTopic='risk';state.scope='all';state.question='哪些企业需要优先跟进？请说明依据。';state.display='table';state.saved=false;render();document.getElementById('ask-input')?.focus();notify('已开始新演示会话，可输入问题或查看推荐问题');break;
    case 'topic-risk':state.page='query';state.queryTopic='risk';state.question='哪些企业需要优先跟进？请说明依据。';state.scope='all';render();if(drawer.open)closeDrawer();break;
    case 'topic-finance':state.page='query';state.queryTopic='finance';state.question='三家重点企业的融资成本如何，应该先关注谁？';state.scope='all';render();if(drawer.open)closeDrawer();break;
    case 'topic-reason':evidence('ENT-020');break;
    case 'object-query':state.scope=target.dataset.entity||state.selected||'ENT-020';state.page='query';state.queryTopic='risk';state.question=company(state.scope).name+'目前有哪些需要关注的风险？';state.display='text';render();if(drawer.open)closeDrawer();break;
    case 'to-map':state.page='map';state.selected=state.scope==='all'?'ENT-020':state.scope;render();if(drawer.open)closeDrawer();break;
    case 'to-decision':state.page='decision';state.caseId=cases.find(c=>c.entity===(target.dataset.entity||state.scope))?.id||'case-20';render();if(drawer.open)closeDrawer();break;
    case 'save':state.saved=true;sessionStorage.setItem('zhicai.glass-review.saved',JSON.stringify({page:state.page,scope:state.scope,queryTopic:state.queryTopic,question:state.question,selected:state.selected,mapView:state.mapView,relations:state.relations}));render();notify('已保存当前设计预览的范围与视图');break;
    case 'saved':{const saved=sessionStorage.getItem('zhicai.glass-review.saved');if(saved){Object.assign(state,JSON.parse(saved));render();notify('已恢复预览中的对象范围和视图');}else showDrawer('已保存视图','现有能力的独立选型演示',`<p>你可以先在主工作区点击“保存视图”或“保存探索”，再从这里恢复。正式原型的历史数据不会被修改。</p>`);break;}
    case 'export':{const rows=state.queryTopic==='finance'?['ENT-020','ENT-007','ENT-017'].map(company):V.riskCompanies;const csv='\uFEFF企业,历史评分,历史分档,融资成本百分比,观察日\n'+rows.map(e=>[e.name,e.riskScore,e.riskTier,e.metrics.cost,D.asOf].join(',')).join('\n'),url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='智财问策-视觉选型-演示结果.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),500);notify('已导出演示结果与观察日期');break;}
    case 'models':modelInfo();break;
    case 'map-filters':showDrawer('企业范围与分析视角','筛选与关联上下文分别保留',`<form id="map-filter-form"><label>产业板块<select name="industry"><option value="">全部板块</option>${['环保','风电','核电'].map(x=>`<option ${state.industry===x?'selected':''}>${x}</option>`).join('')}</select></label><label>分析视角<select name="perspective">${[['risk','历史债务风险'],['cost','融资成本'],['maturity','到期与资金压力'],['exposure','银行借款敞口']].map(([v,n])=>`<option value="${v}" ${state.perspective===v?'selected':''}>${n}</option>`).join('')}</select></label><p>原型的期限、银行、风险分档、框选范围、高成本与资金缺口筛选等能力继续保留，默认收在该面板。</p><button class="btn primary" type="submit">应用筛选</button></form>`);break;
    case 'clear-map':state.selected=null;state.globalRelations=false;render();break;
    case 'select-default':state.selected='ENT-020';render();break;
    case 'zoom-in':state.zoom=Math.min(1.8,state.zoom+.2);render();break;
    case 'zoom-out':state.zoom=Math.max(.6,state.zoom-.2);render();break;
    case 'reset-map':state.zoom=1;state.globalRelations=false;state.selected=null;render();break;
    case 'global-relations':state.globalRelations=!state.globalRelations;render();break;
    case 'map-tools':showDrawer('地图与探索工具','大屏首屏只展示常用工具，完整能力继续保留',`<h3>范围操作</h3><p>框选企业、取消框选、适配当前对象、恢复全局、筛选撤销和保存探索仍在同一分析上下文中。</p><h3>关系呈现</h3><p>融资、授信、担保可分别显示。点击选中企业、右键菜单、Esc和地图空白处都能清除聚焦。关联对象可补充显示，但不自动扩大统计范围。</p>${btn('全局关系','global-relations','route')} ${btn('清除当前选择','clear-map','x')}`);break;
    case 'temporal':{const points=D.history,values=points.map(p=>p.rate),lo=Math.min(...values)-.1,hi=Math.max(...values)+.1,path=points.map((p,i)=>(i?'L':'M')+(24+i*454/(points.length-1))+','+(160-(p.rate-lo)/(hi-lo)*120)).join(' ');showDrawer('时序分析 · 通用对象视图','地图与时序并列，原功能与模型链路保持连续',`<h3>环保测试公司4 · 融资成本</h3><svg viewBox="0 0 510 205" role="img" aria-label="演示历史融资成本曲线"><path d="M24 22 V166 H487" fill="none" stroke="#d9e3e8"></path><path d="${path}" fill="none" stroke="#3a789a" stroke-width="2.5"></path><text x="24" y="193" font-size="11" fill="#718899">2024-01</text><text x="434" y="193" font-size="11" fill="#718899">2025-12</text></svg><p>曲线沿用已有24个月模拟历史，期末与现有快照校准。预测曲线、持仓208个原观测、模型维护入口、情景方案与事项研判在正式重构中完整保留。</p>${btn('查看模型与版本','models','workflow')}<p><a href="${original}#module/m07" target="_blank" rel="noopener">打开原对象全景并进入时序分析 ↗</a></p>`);break;}
    case 'trace':trace();break;
    case 'advance-case':handleCase();break;
    case 'other-case':showDrawer('其他事项处理','次要操作收纳，不取消原能力',`${btn('退回补充','return-case','arrow-left')} ${btn('调整负责人和期限','new-case','settings-2')}<h3>保留的处理</h3><p>拒绝及原因、取消、重开、补充事项、执行凭证、效果复核和原审批记录，仍依事项阶段及前置条件开放。</p>`);break;
    case 'return-case':state.caseStages[state.caseId]=0;state.caseEvents.push('退回补充 · 保留原决定及依据');state.note='';render();closeDrawer();notify('演示事项已退回研判，原依据继续保留');break;
    case 'reject-case':showDrawer('拒绝并记录原因','保留原提请和本次决定',`<form id="reject-case-form"><label>拒绝原因<textarea name="reason" required placeholder="说明暂不推进的原因及依据"></textarea></label><button class="btn primary" type="submit">记录拒绝（演示）</button></form>`);break;
    case 'reopen-case':state.caseStages[state.caseId]=0;state.caseEvents.push('根据新情况重开研判，原拒绝记录保留');render();notify('已重开演示事项');break;
    case 'new-case':showDrawer('新建待研判事项','接收通用事项或方案，不增加专用业务菜单',`<form id="new-case-form"><label>关联企业<select name="entity">${V.riskCompanies.map(e=>`<option value="${e.id}">${e.name}</option>`).join('')}</select></label><label>事项名称<input name="title" required placeholder="说明需要研判的问题"></label><label>负责人<input name="owner" required placeholder="填写负责人或团队"></label><label>来源与依据<textarea name="note" required placeholder="保留原问题、运行编号或相关材料"></textarea></label><p class="drawer-error"></p><button type="submit" class="btn primary">预览待研判事项</button></form>`);break;
    case 'overview':{const counts=phases.map((p,i)=>[p,cases.filter(c=>(state.caseStages[c.id]??1)===i).length]);showDrawer('事项运营总览','与事项工作台共享同一组样例状态',`<h3>当前阶段分布</h3><table><thead><tr><th>阶段</th><th>样例事项数</th></tr></thead><tbody>${counts.map(([p,n])=>`<tr><td>${p}</td><td>${n}</td></tr>`).join('')}</tbody></table><p>运营总览负责进度与分布，具体处理回到原事项详情。效果待复核仍计为未结束事项。</p>${btn('返回事项工作台','close-drawer','arrow-left')}`);break;}
    case 'case-filters':showDrawer('查找待处理事项','来源、负责人、阶段与期限统一筛选',`<h3>来源</h3><div>${['对象分析','智能问数','规则预警','模型提示','AI推荐方案','报告 / 驾驶舱'].map(x=>`<span class="function-chip">${x}</span>`).join('')}</div><h3>筛选演示</h3><p>切换主界面阶段标签即可过滤本组选型样例。完整原型的搜索、负责人、期限和来源筛选会作为同一筛选面板保留。</p>${btn('仅看待批准','filter-approval','filter','primary')}`);break;
    case 'filter-approval':state.caseFilter='approval';render();closeDrawer();break;
    case 'original-records':showDrawer('原申请与办理记录','原有业务链路持续可访问',`<p>统一事项工作台汇总多来源事项；原审批、行动申请、分办失败恢复和完整历史追溯不删除。</p><a class="btn primary" href="${original}#module/decision" target="_blank" rel="noopener">查看当前原型决策中心 ↗</a>`);break;
    case 'report':showDrawer('报告与交付','固定当前结论、对象范围与证据',`<p>保留保存报告草稿、正文及附件、复核记录、正式报告和历史版本。事项报告需要包含办理与效果状态，执行完成不会写成效果已达成。</p><a class="btn primary" href="${original}#module/report" target="_blank" rel="noopener">查看当前报告中心 ↗</a>`);break;
    case 'versions':versions();break;
    case 'revise':state.ontologyMode='draft';state.validated=false;render();if(drawer.open)closeDrawer();notify('已进入独立演示工作草稿，已发布V2保持不变');break;
    case 'validate':state.validated=true;render();notify('演示校验通过；发布与正式数据切换仍是两步');break;
    case 'publish':showDrawer('发布语义版本','发布后固定当前语义与映射，不自动切换正式使用',`<form id="publish-form"><label>新版本号<input name="version" required value="V3"></label><label>发布说明<textarea name="note" required placeholder="说明本次语义及映射变化"></textarea></label><div class="readout">工作草稿已通过演示校验。发布结果仅用于视觉选型，原型的已发布V2和正式绑定不会改变。</div><p class="drawer-error"></p><button class="btn primary" type="submit">确认演示发布</button></form>`);break;
    case 'edit-property':showDrawer('编辑语义资源','草稿编辑后重新校验',`<form id="property-form"><label>资源名称<input name="name" value="${esc(V.ontologyNodes.find(n=>n.id===state.node).name)}" required></label><label>定义<textarea name="definition" required>在固定业务身份下维护属性与数据映射，保留精确来源。</textarea></label><button class="btn primary" type="submit">保存到演示草稿</button></form>`);break;
    case 'validation':showDrawer('统一校验','原校验规则、失败定位和恢复入口继续保留',`<h3>当前选型状态：${state.validated?'已通过':'待校验'}</h3><ul><li>对象身份和主键唯一性</li><li>属性类型、单位与必填约束</li><li>关系方向、基数与端点映射</li><li>规则、指标及行动前置条件</li><li>已发布资产版本与字段来源</li></ul><p>真实原型只有当前内容的有效核验通过才允许发布。修改后使旧核验失效，不会套用旧结果。</p>${btn('运行演示校验','validate','shield-check','primary')}`);break;
    case 'binding':showDrawer('数据资产与字段映射','字段映射绑定精确数据资产版本',`<h3>${V.ontologyNodes.find(n=>n.id===state.node).name}</h3><table><thead><tr><th>业务属性</th><th>数据来源</th><th>约束</th></tr></thead><tbody>${V.ontologyNodes.find(n=>n.id===state.node).props.map((p,i)=>`<tr><td>${p}</td><td>已发布资产对应字段</td><td>${i===0?'主键唯一':'类型与单位一致'}</td></tr>`).join('')}</tbody></table><p>本表演示映射的呈现方式；原资产标识、字段标识、版本指纹与实际校验逻辑将原样保留。</p>${btn('查看版本与正式使用','versions','git-branch')}`);break;
    case 'consumption':showDrawer('下游消费与来源证据','保留当前正式组合和历史使用记录',`<h3>消费位置</h3><ul><li>对象全景：对象身份、关系与来源下钻</li><li>问数工作台：固定语义、观察期与计算结果</li><li>模型与算法：输入／输出绑定及精确版本</li><li>决策中心：规则、模型提示和受控行动</li></ul><p>未完成正式数据启用的版本会明确显示阻断原因，不能仅因“已发布”就标为正在使用。</p>`);break;
    case 'resources':case 'relations':case 'metrics':case 'add-resource':case 'graph-filter':showDrawer({resources:'语义资源目录',relations:'关系与方向',metrics:'指标与计算口径','add-resource':'添加语义资源','graph-filter':'画布显示范围'}[action],'原本体能力的承载方式',`<p>保留对象类型、属性、关系、指标、规则与行动的创建、编辑和依赖查看。工作区默认展示业务主干，完整资源与跨模块消费可按需展开。</p><div>${['11类对象','76个属性','10类关系','8个指标','3条规则','1类行动'].map(x=>`<span class="function-chip">${x}</span>`).join('')}</div><h3>当前画布</h3><p>选中节点即可查看属性、数据绑定和下游消费；切换“数据血缘”查看来源到语义及应用的路径。画布为关键资源排版示意，正式重构使用原本体图数据。</p>${btn('查看原本体模块','original-ontology','external-link','primary')}`);break;
    case 'graph-fit':notify('当前画布已适配完整业务主干');break;
    case 'original-ontology':window.open(original+'#module/ontology','_blank','noopener');break;
    case 'search':showDrawer('搜索业务资源','查找对象、模型、事项或语义',`<form id="resource-search-form"><label>资源名称<input name="query" required placeholder="例如：环保测试公司4"></label><button type="submit" class="btn primary">查找演示对象</button></form><p>完整原型的全局搜索与最近工作入口在顶栏保留。</p>`);break;
    case 'modules':showDrawer('全部功能入口','四个选型页面之外的模块继续保留',`<p>本轮仅选择关键页面验证风格。首页、数据工程、对象目录／画像／时序、模型与算法、Agent应用、报告中心将在你选定方案后使用同一套视觉规范。</p>${[['首页','home'],['数据工程','module/data'],['对象全景','module/m07'],['模型与算法','module/modeling'],['Agent 应用','module/agent'],['报告中心','module/report']].map(([n,hash])=>`<p><a class="btn" href="${original}#${hash}" target="_blank" rel="noopener">${n} · 当前原型 ↗</a></p>`).join('')}`);break;
    default:notify('该入口将在选定风格后与原业务逻辑绑定。');
  }}
  document.addEventListener('click',event=>{
    const style=event.target.closest('[data-variant]');if(style&&style.tagName==='BUTTON'){state.variant=style.dataset.variant;render();return;}
    const page=event.target.closest('[data-page]');if(page){state.page=page.dataset.page;render();return;}
    const display=event.target.closest('[data-display]');if(display){state.display=display.dataset.display;render();return;}
    const select=event.target.closest('[data-select]');if(select){state.selected=state.selected===select.dataset.select?null:select.dataset.select;state.globalRelations=false;render();return;}
    const bank=event.target.closest('[data-bank]');if(bank){const b=D.banks.find(b=>b.id===bank.dataset.bank),related=D.enterprises.filter(e=>D.loans.some(l=>l.enterpriseId===e.id&&l.bankId===b.id));showDrawer(b.name,'融资机构 · 关联企业',`<p>当前演示快照中关联 ${related.length} 家企业。银行与企业使用不同图标，关系来源仍可逐条追溯。</p>${related.map(e=>`<p>${btn(e.name,'portrait','building-2','',`data-entity="${e.id}"`)}</p>`).join('')}`);return;}
    const mode=event.target.closest('[data-map-view]');if(mode){state.mapView=mode.dataset.mapView;render();return;}
    if(event.target.closest('[data-clear-map]')){state.selected=null;state.globalRelations=false;render();return;}
    const item=event.target.closest('[data-case]');if(item){state.caseId=item.dataset.case;state.note='';render();return;}
    const filter=event.target.closest('[data-case-filter]');if(filter){state.caseFilter=filter.dataset.caseFilter;render();return;}
    const node=event.target.closest('[data-node]');if(node){state.node=node.dataset.node;render();return;}
    const graph=event.target.closest('[data-graph-mode]');if(graph){state.graphMode=graph.dataset.graphMode;render();return;}
    const tab=event.target.closest('[data-property-tab]');if(tab){state.propertyTab=tab.dataset.propertyTab;render();return;}
    const action=event.target.closest('[data-action]');if(action){doAction(action.dataset.action,action);return;}
    if(!menu.contains(event.target))menu.hidden=true;
  });
  document.addEventListener('change',event=>{const t=event.target;if(t.dataset.relation){state.relations=t.checked?[...new Set([...state.relations,t.dataset.relation])]:state.relations.filter(x=>x!==t.dataset.relation);render();}if(t.id==='industry-filter'){state.industry=t.value;render();}if(t.id==='perspective'){state.perspective=t.value;render();}});
  document.addEventListener('input',event=>{const t=event.target;if(t.id==='handling-note')state.note=t.value;if(t.id==='entity-search'){const value=t.value,position=t.selectionStart;state.search=value;render();const replacement=document.getElementById('entity-search');replacement.focus();replacement.setSelectionRange(position,position);}});
  document.addEventListener('submit',event=>{event.preventDefault();const form=event.target;if(!form.reportValidity())return;const fields=Object.fromEntries(new FormData(form));
    if(form.id==='ask-form'){const text=fields.question.trim();if(!text)return;if(/成本|融资|余额/.test(text)){state.queryTopic='finance';state.scope='all';}else if(/风险|关注|跟进|评分|红灯|黄灯/.test(text)){state.queryTopic='risk';}else{showDrawer('请明确业务问题','选型预览只运行已提供的示例问题',`<p>可查看集团风险分布、重点企业融资成本，或查看环保公司4的原评估依据。正式重构保留原问数的澄清与异常恢复能力。</p>${btn('查看集团风险','topic-risk','shield-alert')} ${btn('查看融资成本','topic-finance','chart-column')}`);return;}state.question=text;state.saved=false;render();}
    if(form.id==='scope-form'){state.scope=fields.scope;state.page='query';state.queryTopic='risk';state.question=fields.scope==='all'?'哪些企业需要优先跟进？请说明依据。':company(fields.scope).name+'需要关注什么？';render();closeDrawer();}
    if(form.id==='map-filter-form'){state.industry=fields.industry;state.perspective=fields.perspective;render();closeDrawer();}
    if(form.id==='case-operation'){const stage=Number(form.dataset.stage);if(!fields.note?.trim()){form.querySelector('.drawer-error').textContent='请填写办理或复核意见。';return;}const outcome=fields.outcome;state.caseStages[state.caseId]=stage===4?outcome==='met'?5:4:stage===3?4:stage+1;state.caseEvents.push(stage===4?'效果复核：'+({met:'已达成',unmet:'未达成，继续复核',insufficient:'证据不足，继续补充'})[outcome]:phases[stage]+' → '+phases[state.caseStages[state.caseId]]);state.note='';render();closeDrawer();notify('已更新演示事项状态，原型记录未修改');}
    if(form.id==='reject-case-form'){state.caseStages[state.caseId]=-1;state.caseEvents.push('已拒绝：'+fields.reason);state.note='';render();closeDrawer();notify('已记录拒绝原因，原提请及依据仍保留');}
    if(form.id==='new-case-form'){state.page='decision';state.caseId=cases.find(c=>c.entity===fields.entity)?.id||'case-20';state.caseStages[state.caseId]=0;state.note=fields.note;render();closeDrawer();notify('已预览对应企业的待研判状态');}
    if(form.id==='publish-form'){state.publishedNew=true;state.ontologyMode='published';state.validated=false;render();closeDrawer();notify('演示版本已发布；当前正式使用没有切换');}
    if(form.id==='property-form'){state.ontologyMode='draft';state.validated=false;render();closeDrawer();notify('演示草稿已修改，需重新校验');}
    if(form.id==='resource-search-form'){const match=D.enterprises.find(e=>e.name.includes(fields.query)||e.id===fields.query);if(match)entityInfo(match.id);else{const content=drawer.querySelector('.drawer-body');content.insertAdjacentHTML('beforeend','<p>没有匹配的演示企业，请尝试企业名称或编号。</p>');}}
  });
  document.addEventListener('contextmenu',event=>{const node=event.target.closest('[data-select]');if(!node||state.page!=='map')return;event.preventDefault();state.selected=node.dataset.select;render();menu.innerHTML=`<strong>${company(state.selected).name}</strong><button type="button" data-rel-preset="financing">仅显示融资关系</button><button type="button" data-rel-preset="credit">仅显示授信关系</button><button type="button" data-rel-preset="guarantee">仅显示担保关系</button><button type="button" data-rel-preset="all">显示全部关系</button><button type="button" data-action="clear-map">取消选择</button>`;menu.style.left=Math.min(innerWidth-210,event.clientX)+'px';menu.style.top=Math.min(innerHeight-260,event.clientY)+'px';menu.hidden=false;});
  menu.addEventListener('click',event=>{const preset=event.target.closest('[data-rel-preset]');if(preset){state.relations=preset.dataset.relPreset==='all'?['financing','credit','guarantee']:[preset.dataset.relPreset];render();}});
  document.addEventListener('keydown',event=>{if(event.key==='Escape'){if(drawer.open)return;menu.hidden=true;if(document.body.classList.contains('presentation')){document.body.classList.remove('presentation');document.getElementById('return-review').hidden=true;}else if(state.page==='map'){state.selected=null;state.globalRelations=false;render();}}if(['Enter',' '].includes(event.key)&&event.target.matches('g[role=button],circle[tabindex]')){event.preventDefault();event.target.dispatchEvent(new MouseEvent('click',{bubbles:true}));}});
  document.getElementById('return-review').addEventListener('click',()=>{document.body.classList.remove('presentation');document.getElementById('return-review').hidden=true;});
  drawer.addEventListener('click',event=>{if(event.target===drawer){const r=drawer.getBoundingClientRect();if(event.clientX<r.left||event.clientX>r.right)closeDrawer();}});
  window.addEventListener('hashchange',()=>{const q=new URLSearchParams(location.hash.slice(1));if(themes[q.get('style')])state.variant=q.get('style');if(pages[q.get('page')])state.page=q.get('page');render();});
  window.__DESIGN_REVIEW__={read:()=>structuredClone(state),pages:Object.keys(pages),styles:Object.keys(themes)};
  render();
})();
