(function () {
  "use strict";

  const portfolio = window.RC_PORTFOLIO?.data || {};
  const s003Source = portfolio.s003?.reports || [];

  const definitions = [
    {
      id: "RD-FIN-001",
      name: "集团融资经营分析报告",
      category: "融资经营分析",
      version: "1.0.0",
      status: "已启用",
      templateId: "RT-FIN-002",
      templateName: "集团融资成本与债务结构分析模板",
      templateVersion: "2.2.0",
      templateHref: "templates/s001-financing-report-template.html",
      scopeLabel: "集团及成员单位",
      dataOptions: ["融资资产 2025-12-31 · 已发布"],
      subjects: ["集团整体", "单位553", "单位465", "单位561"],
      agent: "融资报告生成助手",
      agentVersion: "3.1.0",
      chapters: ["经营概览", "融资成本", "债务结构", "重点单位与机构", "规则发现", "证据与限制"],
      verification: "指标、规则、单位与机构数据逐项核验"
    },
    {
      id: "RD-BUDGET-001",
      name: "预算监督管理分析报告",
      category: "预算管理",
      version: "1.0.0",
      status: "已启用",
      templateId: "RT-BUDGET-001",
      templateName: "预算监督管理分析模板",
      templateVersion: "1.0.0",
      templateHref: "templates/s002-budget-report-template.html",
      scopeLabel: "集团、部门与预算年度",
      dataOptions: ["预算管理资产 2025 年度 · 已发布"],
      subjects: ["集团整体", "设备管理部", "技术部", "安全运行部"],
      agent: "预算报告生成助手",
      agentVersion: "1.0.0",
      chapters: ["预算执行概览", "申报与批准", "项目余额", "采购占用", "费用与差旅", "异常与建议"],
      verification: "426 项检查、58 项事实、66 个锚点"
    },
    {
      id: "RD-RISK-001",
      name: "企业债务风险评估报告",
      category: "债务风险监测",
      version: "1.1.0",
      status: "已启用",
      templateId: "RT-RISK-001",
      templateName: "企业债务风险评估模板",
      templateVersion: "1.1.0",
      templateHref: "templates/s003-risk-report-template.html",
      scopeLabel: "单一受评企业",
      dataOptions: ["S003-T007-DEBT-RISK-20251231-v1 · 已发布"],
      subjects: s003Source.map((item) => item.enterpriseName),
      agent: "债务风险报告生成助手",
      agentVersion: "1.2.0",
      chapters: ["执行摘要", "风险诊断", "调节因子", "财务指标", "应对策略", "行动状态", "证据"],
      verification: "企业身份、评分、分档、指标、因子与决策状态逐项核验"
    },
    {
      id: "RDEF-S004-PREFLIGHT-002",
      name: "财务公司贷款贷前调查报告",
      category: "贷前调查",
      version: "2.0.0",
      status: "已启用",
      templateId: "RT-S004-PREFLIGHT-002",
      templateName: "财务公司贷款贷前调查模板",
      templateVersion: "2.0.0",
      templateHref: "../../scenarios/s004-runtime-v2.1.0/artifacts/templates/RT-S004-PREFLIGHT-002-v2.0.0.html",
      scopeLabel: "集团成员单位贷款申请",
      dataOptions: ["贷前调查固定事实包 2026-08-15 · 已发布"],
      subjects: ["中国广核电力股份有限公司"],
      agent: "贷前调查报告生成助手",
      agentVersion: "2.1.0",
      chapters: ["借款人评价", "经营情况", "财务情况", "借款风险", "授信结论", "数据来源"],
      verification: "18 项事实、稳定锚点、人工复核与同源产物核验"
    }
  ];

  const baseReports = [
    {
      id: "RPT-FIN-20260814-001",
      reportNo: "RPT-20260816-092626-010",
      title: "集团融资成本与债务结构分析报告",
      category: "融资经营分析",
      scope: "集团整体",
      period: "2025-12-31",
      version: "2.0.0",
      status: "已发布",
      issuedAt: "2026-08-16 09:26",
      owner: "集团财务管理部",
      definitionId: "RD-FIN-001",
      templateId: "RT-FIN-002",
      semanticVersion: "企业融资语义 V1 · semantic-MSVJM48O-VJC6",
      dataVersion: "FIN-ASSET-20251231-v02",
      evidenceId: "EP-20260816-092248-003",
      verification: "42 / 42 通过",
      agent: "融资报告生成助手 3.1.0",
      html: "portfolio-assets/s001-financing-report.html",
      pdf: "portfolio-assets/pdf/s001-financing-report.pdf",
      formats: ["HTML", "PDF"],
      summary: "集团融资余额 21,613.387 亿元，加权融资成本 2.372231%。报告集中呈现融资成本、债务结构、重点单位、金融机构和三条规则发现。",
      metrics: [["融资余额", "21,613.387 亿元"], ["加权成本", "2.372231%"], ["浮动利率占比", "95.149492%"], ["重点规则", "3 条"]],
      chapters: ["经营概览", "融资成本", "债务结构", "重点单位与机构", "规则发现", "证据与限制"],
      history: [{ version: "2.0.0", date: "2026-08-16 09:26", note: "确定性核验及人工复核完成后发布" }],
      questions: [["集团融资成本处于什么水平？", "集团加权融资成本为 2.372231%，单位553 的融资成本和高成本融资占比较高。"], ["优先与哪些银行协商？", "建议先结合单位553 在欧陆银行、寰宇银行和海联银行的余额、成本及到期分布开展协商。"]]
    },
    {
      id: "RPT-S002-BUDGET-20260815-001",
      reportNo: "BUDGET-RPT-2026-0001",
      title: "2025 年度预算监督管理分析报告",
      category: "预算管理",
      scope: "集团整体",
      period: "2025 年度",
      version: "1.0.0",
      status: "已发布",
      issuedAt: "2026-08-15 16:30",
      owner: "集团预算管理部",
      definitionId: "RD-BUDGET-001",
      templateId: "RT-BUDGET-001",
      semanticVersion: "预算管理本体 1.0.0",
      dataVersion: "S002-DATA-v1（预算执行 + 项目占用）",
      evidenceId: "预算监督固定证据包 · EP-S002-BUDGET-001",
      verification: "426 / 426 通过",
      sourceDraft: "RPT-S002-BUDGET-DRAFT-v1",
      verificationRun: "VRF-20260815-153001-001",
      agent: "预算报告生成助手 1.0.0",
      html: "portfolio-assets/s002-budget-report.html",
      pdf: "portfolio-assets/pdf/s002-budget-report.pdf",
      formats: ["HTML", "PDF"],
      summary: "围绕预算执行、申报批准、项目余额、采购占用、费用差旅和供应商价格形成统一监督结论，并保留部门级下钻证据。",
      metrics: [["预算执行率", "76.4%"], ["覆盖部门", "3 个"], ["核验事实", "58 项"], ["稳定锚点", "66 个"]],
      chapters: ["预算执行概览", "申报与批准", "项目余额", "采购占用", "费用与差旅", "异常与建议"],
      history: [{ version: "1.0.0", date: "2026-08-15 16:30", note: "五类监督主题核验完成后发布" }],
      questions: [["哪些部门预算执行偏差需要关注？", "安全运行部费用预算执行率接近上限，设备管理部执行率低于合理区间，建议结合项目进度分别核查。"], ["采购占用是否集中？", "设备项目年末预算占用集中度达到关注水平，应核对在途采购的交付和释放计划。"]]
    },
    {
      id: "RPT-S004-20260815-0001",
      reportNo: "S004-PLR-2026-0001",
      title: "中国广核电力股份有限公司贷款贷前调查报告",
      category: "贷前调查",
      scope: "中国广核电力股份有限公司",
      period: "2026-08-15",
      version: "2.0.0",
      status: "已发布",
      issuedAt: "2026-08-15 23:30",
      owner: "财务公司授信审查部",
      definitionId: "RDEF-S004-PREFLIGHT-002",
      templateId: "RT-S004-PREFLIGHT-002",
      semanticVersion: "贷前调查本体 V1 · SEM-S004-PREFLIGHT-V1",
      dataVersion: "DATA-ASSET-S004-20260815-V01",
      evidenceId: "EVID-S004-20260815-0002",
      verification: "18 / 18 通过",
      agent: "贷前调查报告生成助手 2.1.0",
      html: "../../scenarios/s004/artifacts/report/RPT-S004-CGNPC-20260815-v2.0.html",
      pdf: "../../scenarios/s004/artifacts/report/RPT-S004-CGNPC-20260815-v2.0.pdf",
      formats: ["HTML", "PDF"],
      summary: "围绕借款人主体与成员关系、经营情况、三年财务表现、偿债能力、风险判断和人工授信结论形成正式贷前调查报告。",
      metrics: [["固定事实", "18 项"], ["核验结果", "全部通过"], ["内容版本", "2.0.0"], ["人工复核", "已确认"]],
      chapters: ["借款人评价", "经营情况", "财务情况", "借款风险", "授信结论", "数据来源"],
      history: [{ version: "2.0.0", date: "2026-08-15 23:30", note: "更新财务和风险证据后发布" }, { version: "1.0.1", date: "2026-08-15 15:12", note: "上一正式版本" }],
      candidates: [{ version: "2.1.0-candidate", date: "2026-08-16 09:20", note: "新一轮内容已生成并完成自动核验，等待人工复核；不覆盖 2.0.0 正式版本。", html: "portfolio-assets/s004/RPT-S004-CGNPC-20260815-v2.1-preview.html" }],
      questions: [["借款人是否具备成员单位资格？", "成员关系、统一社会信用代码与集团成员标识均已进入固定事实包，并通过确定性核验。"], ["偿债能力结论依据是什么？", "结论引用近三年财务报表、现金流、授信与债务结构的固定证据，最终授信意见由有权人员确认。"]]
    }
  ];

  const riskReports = s003Source.map((item, index) => ({
    id: item.reportId,
    reportNo: `RISK-${String(index + 1).padStart(3, "0")}-2025`,
    title: `${item.enterpriseName}债务风险评估报告`,
    category: "债务风险监测",
    scope: item.enterpriseName,
    period: "2025-12-31",
    version: item.contentVersion || "1.7.0",
    status: "已发布",
    issuedAt: "2026-08-17 19:40",
    owner: "财务公司风险管理部",
    definitionId: "RD-RISK-001",
    templateId: "RT-RISK-001",
    semanticVersion: "债务风险本体 1.0.2",
    dataVersion: "S003-T007-DEBT-RISK-20251231-v1",
    evidenceId: `企业风险证据包 · ${item.enterpriseId}`,
    verification: "13 / 13 通过",
    agent: "债务风险报告生成助手 1.2.0",
    html: item.html,
    pdf: `portfolio-assets/pdf/${item.html.split("/").pop().replace(/\.html$/, ".pdf")}`,
    formats: ["HTML", "PDF"],
    riskTier: item.riskTier,
    score: item.finalScore,
    summary: `${item.enterpriseName}综合风险评分 ${item.finalScore} 分，风险等级为${item.riskTier}。报告固定本轮指标、调节因子、规则语义、处置状态和证据。`,
    metrics: [["风险评分", `${item.finalScore} 分`], ["风险等级", item.riskTier], ["评估时点", "2025-12-31"], ["核验结果", "13 / 13 通过"]],
    chapters: ["执行摘要", "风险诊断", "调节因子", "财务指标", "规则语义", "应对策略", "行动状态", "版本证据"],
    history: [{ version: item.contentVersion || "1.7.0", date: "2026-08-17 19:40", note: "企业风险评分与证据核验完成后发布" }],
    candidates: [],
    questions: [["本次风险等级及主要原因是什么？", `${item.enterpriseName}本轮评分为 ${item.finalScore} 分，等级为${item.riskTier}；主要原因可在风险诊断与调节因子章节逐项查看。`], ["报告中的评分可以直接修改吗？", "不能。报告只固定已发布模型的评分结果；输入或模型变化后应创建新的评估运行和报告版本。"]]
  }));

  const reports = [baseReports[0], baseReports[1], ...riskReports, baseReports[2]];

  window.RC_CANONICAL_DATA = Object.freeze({
    version: "ofw.report-center.canonical.v1",
    definitions,
    reports,
    reportCounts: {
      total: reports.length,
      published: reports.filter((item) => item.status === "已发布").length,
      verified: reports.filter((item) => item.verification.includes("通过")).length,
      categories: new Set(reports.map((item) => item.category)).size
    }
  });
})();
