(function () {
  const groupMetrics = {
    balance: 21613.387,
    cost: 2.372231,
    floating: 95.149492,
    shortTerm: 0.911805,
    foreign: 4.224132,
    highCost: 9.859389,
    credit: 34.680039,
  };

  const units = {
    "单位553": {
      singleBusinessSubjectId: "ORG-UNIT-553",
      singleBusinessSubjectName: "单位553",
      singleBusinessSubjectObjectType: "OBJ-ORG-UNIT",
      board: "境外新能源",
      balance: 393.134,
      cost: 2.880984,
      floating: 0,
      shortTerm: 0,
      foreign: 100,
      highCost: 77.337244,
      credit: 0,
      loanCount: 75,
      rule: {
        id: "RULE-FIN-R01",
        code: "R01",
        name: "融资成本偏高",
        version: "2.3.0",
        publishedSemanticVersion: "3.8.1",
        publicationStatus: "Published",
        effective: "2026-06-01 起",
        status: "命中",
        branch: "高成本余额占比超过 20%",
        evaluatedAt: "2026-08-09 09:18",
        evaluationId: "RULE-EVAL-R01-UNIT553-20260809-0918",
        resultVersion: "RR-20260809-0918",
        metricId: "MET-FIN-011",
        metric: "高成本融资余额占比",
        metricValue: "77.337244%",
        threshold: "> 20%",
      },
      institutions: [
        { name: "欧陆银行", balance: 99.586, share: 32.754, cost: 2.9944, count: 16 },
        { name: "寰宇银行", balance: 65.494, share: 21.541, cost: 2.9, count: 11 },
        { name: "海联银行", balance: 58.476, share: 19.233, cost: 3.0045, count: 10 },
      ],
      loans: [
        { id: "FIN-D-004862", institution: "海联银行", balance: 14.903, rate: 2.5, due: "2049-09-27", currency: "英镑" },
        { id: "FIN-D-004848", institution: "欧陆银行", balance: 14.255, rate: 2.9, due: "2049-09-27", currency: "英镑" },
        { id: "FIN-D-004899", institution: "欧陆银行", balance: 13.616, rate: 2.9, due: "2049-09-27", currency: "英镑" },
      ],
    },
    "单位465": {
      singleBusinessSubjectId: "ORG-UNIT-465",
      singleBusinessSubjectName: "单位465",
      singleBusinessSubjectObjectType: "OBJ-ORG-UNIT",
      board: "境内新能源",
      balance: 770,
      cost: 2.196617,
      floating: 100,
      shortTerm: 1.144675,
      foreign: 0,
      highCost: 0,
      credit: 0,
      loanCount: 176,
      rule: {
        id: "RULE-FIN-R02",
        code: "R02",
        name: "浮动利率暴露",
        version: "2.3.0",
        publishedSemanticVersion: "3.8.1",
        publicationStatus: "Published",
        effective: "2026-06-01 起",
        status: "命中",
        branch: "浮动利率余额占比超过 80%",
        evaluatedAt: "2026-08-09 09:18",
        evaluationId: "RULE-EVAL-R02-UNIT465-20260809-0918",
        resultVersion: "RR-20260809-0918",
        metricId: "MET-FIN-010",
        metric: "浮动利率余额占比",
        metricValue: "100%",
        threshold: "> 80%",
      },
      institutions: [
        { name: "融通银行", balance: 249.081, share: 32.348, cost: 2.1539, count: 60 },
        { name: "启明银行", balance: 237.763, share: 30.878, cost: 2.2003, count: 46 },
        { name: "嘉禾银行", balance: 221.527, share: 28.77, cost: 2.2431, count: 55 },
      ],
      loans: [
        { id: "FIN-D-003625", institution: "启明银行", balance: 14.748, rate: 2.25, due: "2050-10-21", currency: "人民币" },
        { id: "FIN-D-003803", institution: "启明银行", balance: 14.233, rate: 2.55, due: "2050-10-21", currency: "人民币" },
        { id: "FIN-D-003815", institution: "融通银行", balance: 14.109, rate: 1.95, due: "2050-10-21", currency: "人民币" },
      ],
    },
    "单位561": {
      singleBusinessSubjectId: "ORG-UNIT-561",
      singleBusinessSubjectName: "单位561",
      singleBusinessSubjectObjectType: "OBJ-ORG-UNIT",
      board: "产业金融",
      balance: 20.016,
      cost: 2.22838,
      floating: 0,
      shortTerm: 93.545164,
      foreign: 0,
      highCost: 0,
      credit: 41.911471,
      loanCount: 50,
      rule: {
        id: "RULE-FIN-R03",
        code: "R03",
        name: "短期债务集中",
        version: "2.3.0",
        publishedSemanticVersion: "3.8.1",
        publicationStatus: "Published",
        effective: "2026-06-01 起",
        status: "命中",
        branch: "短期债务余额占比超过 30%",
        evaluatedAt: "2026-08-09 09:18",
        evaluationId: "RULE-EVAL-R03-UNIT561-20260809-0918",
        resultVersion: "RR-20260809-0918",
        metricId: "MET-FIN-012",
        metric: "短期债务余额占比",
        metricValue: "93.545164%",
        threshold: "> 30%",
      },
      institutions: [
        { name: "同州银行", balance: 5.047, share: 26.955, cost: 2.2411, count: 10 },
        { name: "星河银行", balance: 4.603, share: 24.583, cost: 2.226, count: 11 },
        { name: "恒信银行", balance: 3.662, share: 19.558, cost: 2.2059, count: 11 },
      ],
      loans: [
        { id: "FIN-D-004981", institution: "同州银行", balance: 1.292, rate: 2.35, due: "2028-05-12", currency: "人民币" },
        { id: "FIN-D-005093", institution: "同州银行", balance: 1.115, rate: 2.26, due: "2027-03-06", currency: "人民币" },
        { id: "FIN-D-004948", institution: "鼎新银行", balance: 1.016, rate: 2.26, due: "2026-05-21", currency: "人民币" },
      ],
    },
  };

  const comparisons = {
    "单位465|单位553": { balance: 1163.134, cost: 2.42793 },
    "单位553|单位561": { balance: 413.15, cost: 2.849367 },
    "单位465|单位561": { balance: 790.016, cost: 2.197422 },
    "单位465|单位553|单位561": { balance: 1183.15, cost: 2.424554 },
  };

  const semanticResources = [
    {
      id: "OBJ-FINANCING",
      type: "Object",
      name: "融资业务",
      description: "在明确融资主体、金融机构和存续时点下形成的受治理融资业务对象。",
      version: "3.8.1",
      definitionVersion: "3.8.1",
      publishedSemanticVersion: "3.8.1",
      status: "Published",
      effective: "2026-01-01 起",
      owner: "本体管理",
    },
    {
      id: "OBJ-ORG-UNIT",
      type: "Object",
      name: "组织单位",
      description: "集团、板块和单位范围的稳定业务主体。",
      version: "3.8.1",
      definitionVersion: "3.8.1",
      publishedSemanticVersion: "3.8.1",
      status: "Published",
      effective: "2026-01-01 起",
      owner: "本体管理",
    },
    {
      id: "OBJ-FIN-INSTITUTION",
      type: "Object",
      name: "金融机构",
      description: "融资业务对应的金融机构稳定业务对象。",
      version: "3.8.1",
      definitionVersion: "3.8.1",
      publishedSemanticVersion: "3.8.1",
      status: "Published",
      effective: "2026-01-01 起",
      owner: "本体管理",
    },
    {
      id: "PROP-LOAN-BALANCE",
      type: "Property",
      name: "融资余额",
      description: "融资业务在数据截至时间仍处于存续状态的本金余额。",
      version: "3.8.1",
      definitionVersion: "3.8.1",
      publishedSemanticVersion: "3.8.1",
      status: "Published",
      effective: "2026-01-01 起",
      owner: "本体管理",
    },
    {
      id: "PROP-ANNUAL-RATE",
      type: "Property",
      name: "执行年化利率",
      description: "融资业务当前执行的年化利率。",
      version: "3.8.1",
      definitionVersion: "3.8.1",
      publishedSemanticVersion: "3.8.1",
      status: "Published",
      effective: "2026-01-01 起",
      owner: "本体管理",
    },
    {
      id: "PROP-RATE-TYPE",
      type: "Property",
      name: "利率类型",
      description: "融资业务的固定或浮动利率分类。",
      version: "3.8.1",
      definitionVersion: "3.8.1",
      publishedSemanticVersion: "3.8.1",
      status: "Published",
      effective: "2026-01-01 起",
      owner: "本体管理",
    },
    {
      id: "PROP-MATURITY-DATE",
      type: "Property",
      name: "到期日",
      description: "融资业务合同约定的到期日期。",
      version: "3.8.1",
      definitionVersion: "3.8.1",
      publishedSemanticVersion: "3.8.1",
      status: "Published",
      effective: "2026-01-01 起",
      owner: "本体管理",
    },
    {
      id: "PROP-CURRENCY",
      type: "Property",
      name: "融资币种",
      description: "融资业务合同金额的币种。",
      version: "3.8.1",
      definitionVersion: "3.8.1",
      publishedSemanticVersion: "3.8.1",
      status: "Published",
      effective: "2026-01-01 起",
      owner: "本体管理",
    },
    {
      id: "PROP-GUARANTEE-TYPE",
      type: "Property",
      name: "担保方式",
      description: "融资业务的信用、质押或其他担保分类；未知值保持单列。",
      version: "3.8.1",
      definitionVersion: "3.8.1",
      publishedSemanticVersion: "3.8.1",
      status: "Published",
      effective: "2026-01-01 起",
      owner: "本体管理",
    },
    {
      id: "LINK-UNIT-FINANCING",
      type: "Link",
      name: "单位持有融资",
      description: "组织单位到融资业务的受治理关联。",
      direction: "OBJ-ORG-UNIT → OBJ-FINANCING",
      version: "3.8.1",
      definitionVersion: "3.8.1",
      publishedSemanticVersion: "3.8.1",
      status: "Published",
      effective: "2026-01-01 起",
      owner: "本体管理",
    },
    {
      id: "LINK-FINANCING-INSTITUTION",
      type: "Link",
      name: "融资对应机构",
      description: "融资业务到金融机构的受治理关联。",
      direction: "OBJ-FINANCING → OBJ-FIN-INSTITUTION",
      version: "3.8.1",
      definitionVersion: "3.8.1",
      publishedSemanticVersion: "3.8.1",
      status: "Published",
      effective: "2026-01-01 起",
      owner: "本体管理",
    },
  ];

  const metrics = {
    balance: {
      id: "MET-FIN-001",
      type: "Metric",
      name: "融资余额",
      definition: "统计范围内处于存续状态的融资本金余额折人民币合计。",
      unit: "亿元",
      appliesTo: "集团、板块、单位",
      filter: "融资状态 = 存续；币种按报告定义折人民币",
      dataAsOf: "2026-08-09",
      calculationAt: "2026-08-09 09:18",
      effective: "2026-01-01—2026-12-31",
      version: "3.8.1",
      definitionVersion: "3.8.1",
      publishedSemanticVersion: "3.8.1",
      status: "Published",
      resultId: "MR-FIN-BALANCE-20260809-0918",
      resultVersion: "MR-20260809-0918",
      owner: "本体管理",
    },
    cost: {
      id: "MET-FIN-008",
      type: "Metric",
      name: "余额加权融资成本",
      definition: "以融资余额为权重，对存续融资的执行年化利率进行加权。",
      unit: "%",
      appliesTo: "集团、板块、单位",
      filter: "融资状态 = 存续；融资余额 > 0",
      dataAsOf: "2026-08-09",
      calculationAt: "2026-08-09 09:18",
      effective: "2026-01-01—2026-12-31",
      version: "3.8.1",
      definitionVersion: "3.8.1",
      publishedSemanticVersion: "3.8.1",
      status: "Published",
      resultId: "MR-FIN-COST-20260809-0918",
      resultVersion: "MR-20260809-0918",
      owner: "本体管理",
    },
    floating: {
      id: "MET-FIN-010",
      type: "Metric",
      name: "浮动利率余额占比",
      definition: "浮动利率融资余额占全部存续融资余额的比例。",
      unit: "%",
      appliesTo: "集团、板块、单位",
      filter: "利率类型 = 浮动；融资状态 = 存续",
      dataAsOf: "2026-08-09",
      calculationAt: "2026-08-09 09:18",
      effective: "2026-01-01—2026-12-31",
      version: "3.8.1",
      definitionVersion: "3.8.1",
      publishedSemanticVersion: "3.8.1",
      status: "Published",
      resultId: "MR-FIN-FLOATING-20260809-0918",
      resultVersion: "MR-20260809-0918",
      owner: "本体管理",
    },
    highCost: {
      id: "MET-FIN-011",
      type: "Metric",
      name: "高成本融资余额占比",
      definition: "命中当前已发布高成本条件的融资余额占全部存续融资余额的比例。",
      unit: "%",
      appliesTo: "集团、板块、单位",
      filter: "融资状态 = 存续；条件引用 RULE-FIN-R01 已发布版本 2.3.0",
      dataAsOf: "2026-08-09",
      calculationAt: "2026-08-09 09:18",
      effective: "2026-01-01—2026-12-31",
      version: "3.8.1",
      definitionVersion: "3.8.1",
      publishedSemanticVersion: "3.8.1",
      status: "Published",
      resultId: "MR-FIN-HIGH-COST-20260809-0918",
      resultVersion: "MR-20260809-0918",
      owner: "本体管理",
    },
    shortTerm: {
      id: "MET-FIN-012",
      type: "Metric",
      name: "短期债务余额占比",
      definition: "短期融资余额占全部存续融资余额的比例。",
      unit: "%",
      appliesTo: "集团、板块、单位",
      filter: "期限分类 = 短期；融资状态 = 存续",
      dataAsOf: "2026-08-09",
      calculationAt: "2026-08-09 09:18",
      effective: "2026-01-01—2026-12-31",
      version: "3.8.1",
      definitionVersion: "3.8.1",
      publishedSemanticVersion: "3.8.1",
      status: "Published",
      resultId: "MR-FIN-SHORT-TERM-20260809-0918",
      resultVersion: "MR-20260809-0918",
      owner: "本体管理",
    },
    foreign: {
      id: "MET-FIN-013",
      type: "Metric",
      name: "外币融资余额占比",
      definition: "非人民币融资余额折人民币后占全部存续融资余额的比例。",
      unit: "%",
      appliesTo: "集团、板块、单位",
      filter: "融资币种 != 人民币；融资状态 = 存续",
      dataAsOf: "2026-08-09",
      calculationAt: "2026-08-09 09:18",
      effective: "2026-01-01—2026-12-31",
      version: "3.8.1",
      definitionVersion: "3.8.1",
      publishedSemanticVersion: "3.8.1",
      status: "Published",
      resultId: "MR-FIN-FOREIGN-20260809-0918",
      resultVersion: "MR-20260809-0918",
      owner: "本体管理",
    },
    credit: {
      id: "MET-FIN-014",
      type: "Metric",
      name: "信用融资余额占比",
      definition: "担保方式为信用的融资余额占全部存续融资余额的比例。",
      unit: "%",
      appliesTo: "集团、板块、单位",
      filter: "担保方式 = 信用；未知担保方式保持单列",
      dataAsOf: "2026-08-09",
      calculationAt: "2026-08-09 09:18",
      effective: "2026-01-01—2026-12-31",
      version: "3.8.1",
      definitionVersion: "3.8.1",
      publishedSemanticVersion: "3.8.1",
      status: "Published",
      resultId: "MR-FIN-CREDIT-20260809-0918",
      resultVersion: "MR-20260809-0918",
      owner: "本体管理",
    },
  };

  const rules = [
    {
      id: "RULE-FIN-R01",
      code: "R01",
      type: "Rule",
      name: "融资成本偏高",
      description: "当单位高成本融资余额占比超过 20% 时命中，用于识别需要优先核对置换空间的融资主体。",
      definitionVersion: "2.3.0",
      publishedSemanticVersion: "3.8.1",
      status: "Published",
      effective: "2026-06-01 起",
      dependsOn: ["MET-FIN-011"],
      applicableAsOf: "2026-08-09",
      evaluatedAt: "2026-08-09 09:18",
      resultVersion: "RR-20260809-0918",
      owner: "本体管理",
    },
    {
      id: "RULE-FIN-R02",
      code: "R02",
      type: "Rule",
      name: "浮动利率暴露",
      description: "当单位浮动利率余额占比超过 80% 时命中，用于识别需要核对固定利率、利率上限或重定价条款的融资主体。",
      definitionVersion: "2.3.0",
      publishedSemanticVersion: "3.8.1",
      status: "Published",
      effective: "2026-06-01 起",
      dependsOn: ["MET-FIN-010"],
      applicableAsOf: "2026-08-09",
      evaluatedAt: "2026-08-09 09:18",
      resultVersion: "RR-20260809-0918",
      owner: "本体管理",
    },
    {
      id: "RULE-FIN-R03",
      code: "R03",
      type: "Rule",
      name: "短期债务集中",
      description: "当单位短期债务余额占比超过 30% 时命中，用于识别需要核对展期或中长期置换条件的融资主体。",
      definitionVersion: "2.3.0",
      publishedSemanticVersion: "3.8.1",
      status: "Published",
      effective: "2026-06-01 起",
      dependsOn: ["MET-FIN-012"],
      applicableAsOf: "2026-08-09",
      evaluatedAt: "2026-08-09 09:18",
      resultVersion: "RR-20260809-0918",
      owner: "本体管理",
    },
  ];

  const actionTypes = [
    {
      id: "AT-FIN-OPT-001",
      type: "Action Type",
      name: "融资优化建议",
      description: "请求决策中心对单一业务主体的融资结构优化建议进入提醒、人工确认和后续执行闭环。",
      definitionVersion: "2.1.0",
      publishedSemanticVersion: "3.8.1",
      status: "Published",
      effective: "2026-06-01 起",
      owner: "本体管理",
    },
  ];

  const authoritativeConsumption = {
    owner: "本体管理",
    contract: "C008",
    current: {
      bindingId: "T019-FIN-CURRENT",
      status: "当前权威组合",
      semanticVersionId: "PUB-SEM-FIN-3.8.1",
      semanticVersion: "3.8.1",
      dataAssetId: "T006-FINANCING-S001",
      dataAssetVersionId: "T007-FIN-20260809-01",
      dataVersion: "2026.08.09-01",
      consumableVersionId: "T018-FIN-20260809-01",
      asOf: "2026-08-09",
      adoptedAt: "2026-08-09 09:30",
      compatibility: "兼容",
      readiness: "可消费",
      authority: "已采用",
    },
    previousAuthoritative: {
      bindingId: "T019-FIN-PREVIOUS",
      status: "本体上一权威服务组合",
      semanticVersionId: "PUB-SEM-FIN-3.8.1",
      semanticVersion: "3.8.1",
      dataAssetId: "T006-FINANCING-S001",
      dataAssetVersionId: "T007-FIN-20260731-02",
      dataVersion: "2026.07.31-02",
      consumableVersionId: "T018-FIN-20260731-02",
      asOf: "2026-07-31",
      compatibility: "兼容",
      readiness: "可消费",
      authority: "只读参考，未被当前采用",
    },
    switchPermission: "仅本体管理可原子提交或受控回退；报告中心只读消费，不提供切换控件。",
  };

  const fiveDimensionProfiles = {
    available: [
      { id: "version-location", name: "版本定位", status: "可定位", reason: "精确 T006/T007/T008 与来源证据可读取。" },
      { id: "content-access", name: "内容访问", status: "可访问", reason: "获准消费者可按固定证据入口读取。" },
      { id: "evidence-integrity", name: "证据完整", status: "完整", reason: "版本、时点、质量与来源追溯证据完整。" },
      { id: "replay-capability", name: "重放能力", status: "具备重放条件", reason: "当前保留状态支持数据侧重放条件。" },
      { id: "replay-verification", name: "重放核验", status: "未执行", reason: "当前未形成真实重放一致性结论。" },
    ],
    replayVerified: [
      { id: "version-location", name: "版本定位", status: "可定位", reason: "精确 T006/T007/T008 与来源证据可读取。" },
      { id: "content-access", name: "内容访问", status: "可访问", reason: "获准消费者可按固定证据入口读取。" },
      { id: "evidence-integrity", name: "证据完整", status: "完整", reason: "版本、时点、质量与来源追溯证据完整。" },
      { id: "replay-capability", name: "重放能力", status: "具备重放条件", reason: "当前保留状态支持数据侧重放条件。" },
      { id: "replay-verification", name: "重放核验", status: "一致", reason: "本次数据侧重放核验已完成且结果一致；不单独代表报告端到端复算完成。" },
    ],
    hardFailure: [
      { id: "version-location", name: "版本定位", status: "可定位", reason: "失败版本及来源证据仍可定位。" },
      { id: "content-access", name: "内容访问", status: "可访问", reason: "失败版本和原报告固定证据仍可按获准范围读取；不得用于新正式输出。" },
      { id: "evidence-integrity", name: "证据完整", status: "完整", reason: "版本与事后硬质量失败证据均已登记；质量失败作为独立事实披露。" },
      { id: "replay-capability", name: "重放能力", status: "依赖不足", reason: "修复或权威组合受控回退前，当前不具备获准的重放依赖。" },
      { id: "replay-verification", name: "重放核验", status: "未执行", reason: "没有形成数据侧一致性结论。" },
    ],
    previousTrusted: [
      { id: "version-location", name: "版本定位", status: "可定位", reason: "上一可信组合的精确版本标识可读取。" },
      { id: "content-access", name: "内容访问", status: "不可访问", reason: "当前报告事实包入口尚未返回该版本的结构化结果。" },
      { id: "evidence-integrity", name: "证据完整", status: "完整", reason: "版本、时点、质量和受控回退证据完整。" },
      { id: "replay-capability", name: "重放能力", status: "具备重放条件", reason: "保留状态允许后续按受控流程验证。" },
      { id: "replay-verification", name: "重放核验", status: "未执行", reason: "当前未形成真实重放一致性结论。" },
    ],
  };

  const dataTrust = {
    owner: "数据工程",
    contract: "C017",
    bindingSummary: {
      id: "C017-BIND-FIN-20260809-01",
      version: "1.0",
      formedAt: "2026-08-09 09:22",
      dataAssetId: "T006-FINANCING-S001",
      dataAssetVersionId: "T007-FIN-20260809-01",
      dataVersion: "2026.08.09-01",
      asOf: "2026-08-09",
      publishedQuality: "有提示",
      publishedQualityDetails: "担保方式存在未知值，未知分类必须保持单列披露。",
      freshness: "当前",
      readiness: "可消费",
      hardQualityFailure: false,
      retention: "在线",
      fiveDimensions: fiveDimensionProfiles.available.map((item) => ({ ...item })),
    },
    currentStatusSummary: {
      id: "C017-CURRENT-FIN-20260813-01",
      version: "1.0",
      formedAt: "2026-08-13 10:30",
      dataAssetId: "T006-FINANCING-S001",
      dataAssetVersionId: "T007-FIN-20260809-01",
      dataVersion: "2026.08.09-01",
      asOf: "2026-08-09",
      publishedQuality: "有提示",
      laterQualityFinding: "未发现事后硬质量失败",
      hardQualityFailure: false,
      hardQualityFailureFoundAt: null,
      impactScope: "担保结构未知分类；其他已绑定指标未发现受影响证据",
      recoveryAdvice: "保留未知分类和脚注；如后续出现硬质量失败，阻断新报告、洞察和 Action Request。",
      comparisonCondition: "带警告",
      comparisonConditionReason: "当前结构化结果可读，但担保方式未知分类仍须在比较结果中披露。",
      freshness: "当前",
      readiness: "可消费",
      retention: "在线",
      fiveDimensions: fiveDimensionProfiles.available.map((item) => ({ ...item })),
    },
    dataPreviousVersion: {
      id: "T007-FIN-20260731-02",
      label: "数据侧上一已通过发布版本",
      dataVersion: "2026.07.31-02",
      asOf: "2026-07-31",
      publishedQuality: "通过",
      freshness: "历史快照",
      readiness: "已发布",
      authority: "不是当前 T019；不得由报告中心自行改用",
    },
    candidate: {
      id: "T007-FIN-20260812-R1",
      label: "处理中候选版本",
      dataVersion: "2026.08.12-R1",
      asOf: "2026-08-12",
      publishedQuality: "检查中",
      freshness: "候选",
      readiness: "不可消费",
      compatibility: "待验证",
      authority: "未被 T019 采用，不参与正式数值比较",
    },
    fiveDimensions: fiveDimensionProfiles.available.map((item) => ({ ...item })),
    permissions: "不含业务明细、Metric 公式或 Rule 阈值；数据工程不切换 T019，也不决定语义兼容。",
  };

  const reportEvidence = {
    bindingId: "REB-S001-FINANCE-001",
    version: "1.0",
    sections: [
      { id: "sec-overview", number: "01", name: "经营概览" },
      { id: "sec-cost", number: "02", name: "融资成本" },
      { id: "sec-structure", number: "03", name: "债务结构" },
      { id: "sec-units", number: "04", name: "重点单位与机构" },
      { id: "sec-rules", number: "05", name: "规则发现" },
      { id: "sec-evidence", number: "06", name: "证据与限制" },
    ],
    anchors: [
      { id: "date-asof", sectionId: "sec-overview", type: "日期", ref: "E01", factId: "FACT-AS-OF", evidence: ["C017-BIND-FIN-20260809-01", "T008-2026-08-09"] },
      { id: "metric-balance", sectionId: "sec-overview", type: "数值", ref: "E02", factId: "FACT-GROUP-BALANCE", evidence: ["MET-FIN-001", "MR-FIN-BALANCE-20260809-0918"] },
      { id: "kpi-balance", sectionId: "sec-overview", type: "指标卡数值", ref: "E02", factId: "FACT-GROUP-BALANCE", evidence: ["MET-FIN-001", "MR-FIN-BALANCE-20260809-0918"] },
      { id: "metric-cost", sectionId: "sec-overview", type: "数值", ref: "E03", factId: "FACT-GROUP-COST", evidence: ["MET-FIN-008", "MR-FIN-COST-20260809-0918"] },
      { id: "kpi-cost", sectionId: "sec-overview", type: "指标卡数值", ref: "E03", factId: "FACT-GROUP-COST", evidence: ["MET-FIN-008", "MR-FIN-COST-20260809-0918"] },
      { id: "kpi-floating", sectionId: "sec-overview", type: "指标卡数值", ref: "E04", factId: "FACT-GROUP-FLOATING", evidence: ["MET-FIN-010", "MR-FIN-FLOATING-20260809-0918"] },
      { id: "structure-floating", sectionId: "sec-structure", type: "段落数值", ref: "E04", factId: "FACT-GROUP-FLOATING", evidence: ["MET-FIN-010", "MR-FIN-FLOATING-20260809-0918"] },
      { id: "cell-floating", sectionId: "sec-structure", type: "表格单元格", ref: "E04", factId: "FACT-GROUP-FLOATING", evidence: ["MET-FIN-010", "MR-FIN-FLOATING-20260809-0918"] },
      { id: "metric-high-cost", sectionId: "sec-cost", type: "数值", ref: "E05", factId: "FACT-GROUP-HIGH-COST", evidence: ["MET-FIN-011", "MR-FIN-HIGH-COST-20260809-0918"] },
      { id: "structure-short", sectionId: "sec-structure", type: "段落数值", ref: "E06", factId: "FACT-GROUP-SHORT", evidence: ["MET-FIN-012", "MR-FIN-SHORT-TERM-20260809-0918"] },
      { id: "cell-short", sectionId: "sec-structure", type: "表格单元格", ref: "E06", factId: "FACT-GROUP-SHORT", evidence: ["MET-FIN-012", "MR-FIN-SHORT-TERM-20260809-0918"] },
      { id: "structure-foreign", sectionId: "sec-structure", type: "段落数值", ref: "E07", factId: "FACT-GROUP-FOREIGN", evidence: ["MET-FIN-013", "MR-FIN-FOREIGN-20260809-0918"] },
      { id: "cell-foreign", sectionId: "sec-structure", type: "表格单元格", ref: "E07", factId: "FACT-GROUP-FOREIGN", evidence: ["MET-FIN-013", "MR-FIN-FOREIGN-20260809-0918"] },
      { id: "cell-credit", sectionId: "sec-structure", type: "表格单元格", ref: "E08", factId: "FACT-GROUP-CREDIT", evidence: ["MET-FIN-014", "MR-FIN-CREDIT-20260809-0918"] },
      { id: "structure-unknown", sectionId: "sec-structure", type: "段落数值", ref: "E09", factId: "FACT-GUARANTEE-UNKNOWN", evidence: ["C017-BIND-FIN-20260809-01", "PROP-GUARANTEE-TYPE"] },
      { id: "compare-balance", sectionId: "sec-units", type: "数值", ref: "E10", factId: "FACT-THREE-UNIT-BALANCE", evidence: ["MET-FIN-001", "MR-FIN-BALANCE-20260809-0918"] },
      { id: "compare-cost", sectionId: "sec-units", type: "数值", ref: "E11", factId: "FACT-THREE-UNIT-COST", evidence: ["MET-FIN-008", "MR-FIN-COST-20260809-0918"] },
      { id: "institution-priority", sectionId: "sec-units", type: "段落", ref: "E12", factId: "FACT-R01-INSTITUTIONS", evidence: ["RULE-FIN-R01", "RULE-EVAL-R01-UNIT553-20260809-0918"] },
      { id: "rule-r01-result", sectionId: "sec-rules", type: "Rule 结论", ref: "E13", factId: "FACT-R01-RESULT", evidence: ["RULE-FIN-R01", "RULE-EVAL-R01-UNIT553-20260809-0918", "MET-FIN-011"] },
      { id: "rule-r02-result", sectionId: "sec-rules", type: "Rule 结论", ref: "E14", factId: "FACT-R02-RESULT", evidence: ["RULE-FIN-R02", "RULE-EVAL-R02-UNIT465-20260809-0918", "MET-FIN-010"] },
      { id: "rule-r03-result", sectionId: "sec-rules", type: "Rule 结论", ref: "E15", factId: "FACT-R03-RESULT", evidence: ["RULE-FIN-R03", "RULE-EVAL-R03-UNIT561-20260809-0918", "MET-FIN-012"] },
      { id: "narrative-suggestion", sectionId: "sec-rules", type: "建议", ref: "E16", factId: "FACT-SUGGESTION-SCOPE", evidence: ["RULE-FIN-R01", "RULE-FIN-R02", "RULE-FIN-R03", "AT-FIN-OPT-001"] },
      { id: "chart-cost", sectionId: "sec-cost", type: "图表", ref: "E03", factId: "FACT-COST-TREND", evidence: ["MET-FIN-008", "MR-20260809-0918"] },
    ],
    facts: [
      { id: "FACT-AS-OF", kind: "日期", value: "2026-08-09", unit: null, scope: "集团", evidence: ["C017-BIND-FIN-20260809-01"], resultVersion: "1.0" },
      { id: "FACT-GROUP-BALANCE", kind: "Metric 结果", value: 21613.387, unit: "亿元", scope: "集团", evidence: ["MET-FIN-001"], resultVersion: "MR-20260809-0918" },
      { id: "FACT-GROUP-COST", kind: "Metric 结果", value: 2.372231, unit: "%", scope: "集团", evidence: ["MET-FIN-008"], resultVersion: "MR-20260809-0918" },
      { id: "FACT-GROUP-FLOATING", kind: "Metric 结果", value: 95.149492, unit: "%", scope: "集团", evidence: ["MET-FIN-010"], resultVersion: "MR-20260809-0918" },
      { id: "FACT-GROUP-HIGH-COST", kind: "Metric 结果", value: 9.859389, unit: "%", scope: "集团", evidence: ["MET-FIN-011"], resultVersion: "MR-20260809-0918" },
      { id: "FACT-GROUP-SHORT", kind: "Metric 结果", value: 0.911805, unit: "%", scope: "集团", evidence: ["MET-FIN-012"], resultVersion: "MR-20260809-0918" },
      { id: "FACT-GROUP-FOREIGN", kind: "Metric 结果", value: 4.224132, unit: "%", scope: "集团", evidence: ["MET-FIN-013"], resultVersion: "MR-20260809-0918" },
      { id: "FACT-GROUP-CREDIT", kind: "Metric 结果", value: 34.680039, unit: "%", scope: "集团", evidence: ["MET-FIN-014"], resultVersion: "MR-20260809-0918" },
      { id: "FACT-GUARANTEE-UNKNOWN", kind: "质量披露", value: 27.436, unit: "%", scope: "集团", evidence: ["C017-BIND-FIN-20260809-01", "PROP-GUARANTEE-TYPE"], resultVersion: "1.0" },
      { id: "FACT-THREE-UNIT-BALANCE", kind: "Metric 结果", value: 1183.15, unit: "亿元", scope: "单位553、单位465、单位561", evidence: ["MET-FIN-001"], resultVersion: "MR-20260809-0918" },
      { id: "FACT-THREE-UNIT-COST", kind: "Metric 结果", value: 2.424554, unit: "%", scope: "单位553、单位465、单位561", evidence: ["MET-FIN-008"], resultVersion: "MR-20260809-0918" },
      { id: "FACT-R01-INSTITUTIONS", kind: "Rule 命中证据", value: "欧陆银行、寰宇银行、海联银行", unit: null, scope: "单位553", evidence: ["RULE-FIN-R01"], resultVersion: "RR-20260809-0918" },
      { id: "FACT-R01-RESULT", kind: "Rule 结论", value: "命中", unit: null, scope: "单位553", evidence: ["RULE-FIN-R01", "MET-FIN-011"], resultVersion: "RR-20260809-0918" },
      { id: "FACT-R02-RESULT", kind: "Rule 结论", value: "命中", unit: null, scope: "单位465", evidence: ["RULE-FIN-R02", "MET-FIN-010"], resultVersion: "RR-20260809-0918" },
      { id: "FACT-R03-RESULT", kind: "Rule 结论", value: "命中", unit: null, scope: "单位561", evidence: ["RULE-FIN-R03", "MET-FIN-012"], resultVersion: "RR-20260809-0918" },
      { id: "FACT-SUGGESTION-SCOPE", kind: "建议依据", value: "仅用于复核参考，不等同于行动申请", unit: null, scope: "三家重点单位", evidence: ["RULE-FIN-R01", "RULE-FIN-R02", "RULE-FIN-R03", "AT-FIN-OPT-001"], resultVersion: "1.0" },
      { id: "FACT-COST-TREND", kind: "图表序列", value: "2025-09 至 2026-08", unit: "%", scope: "集团", evidence: ["MET-FIN-008"], resultVersion: "MR-20260809-0918" },
    ],
  };

  const verificationChecks = [
    {
      id: "evidenceCompleteness",
      name: "证据完整性",
      owner: "报告中心",
      method: "确定性检查事实、稳定锚点、权威资源引用和结果版本是否完整。",
    },
    {
      id: "valueConsistency",
      name: "数值一致性",
      owner: "报告中心",
      method: "确定性比对正文值与生成时冻结的结构化事实值。",
    },
    {
      id: "semanticConsistency",
      name: "语义一致性",
      owner: "报告中心",
      method: "按本体管理返回的已发布稳定标识核对名称、单位、适用对象和筛选范围。",
    },
    {
      id: "versionCompatibility",
      name: "版本兼容性",
      owner: "报告中心",
      method: "核对报告绑定的已发布语义版本与精确数据版本是否属于同一权威消费组合。",
    },
    {
      id: "trustDisclosure",
      name: "数据可信度披露",
      owner: "报告中心",
      method: "核对截至时间、质量、新鲜度、消费就绪和限制是否完整披露。",
    },
    {
      id: "ruleConsistency",
      name: "Rule 结论一致性",
      owner: "报告中心",
      method: "核对 Rule 结论、触发分支、阈值、评估时间及命中证据。",
    },
    {
      id: "crossContentConsistency",
      name: "跨内容一致性",
      owner: "报告中心",
      method: "核对摘要、正文、指标卡、图表、表格、脚注和同源固定呈现中的重复事实。",
    },
    {
      id: "unboundContentDetection",
      name: "无绑定内容识别",
      owner: "报告中心",
      method: "识别正文中未关联结构化事实或无法定位权威证据的内容。",
    },
  ];

  const metricFactChecks = [
    "evidenceCompleteness",
    "valueConsistency",
    "semanticConsistency",
    "versionCompatibility",
    "trustDisclosure",
    "crossContentConsistency",
    "unboundContentDetection",
  ];
  const ruleFactChecks = [...metricFactChecks.slice(0, 5), "ruleConsistency", ...metricFactChecks.slice(5)];
  const disclosureFactChecks = [
    "evidenceCompleteness",
    "semanticConsistency",
    "versionCompatibility",
    "trustDisclosure",
    "crossContentConsistency",
    "unboundContentDetection",
  ];
  const suggestionFactChecks = [
    "evidenceCompleteness",
    "semanticConsistency",
    "versionCompatibility",
    "ruleConsistency",
    "crossContentConsistency",
    "unboundContentDetection",
  ];

  const sectionNameById = Object.fromEntries(reportEvidence.sections.map((section) => [section.id, section.name]));
  const factLabelById = {
    "FACT-AS-OF": "数据截至时间",
    "FACT-GROUP-BALANCE": "集团融资余额",
    "FACT-GROUP-COST": "集团余额加权融资成本",
    "FACT-GROUP-FLOATING": "集团浮动利率余额占比",
    "FACT-GROUP-HIGH-COST": "集团高成本融资余额占比",
    "FACT-GROUP-SHORT": "集团短期债务余额占比",
    "FACT-GROUP-FOREIGN": "集团外币融资余额占比",
    "FACT-GROUP-CREDIT": "集团信用融资余额占比",
    "FACT-GUARANTEE-UNKNOWN": "担保方式未知余额占比",
    "FACT-THREE-UNIT-BALANCE": "三家重点单位组合融资余额",
    "FACT-THREE-UNIT-COST": "三家重点单位组合加权融资成本",
    "FACT-R01-INSTITUTIONS": "单位553高成本融资重点机构",
    "FACT-R01-RESULT": "R01 命中结论",
    "FACT-R02-RESULT": "R02 命中结论",
    "FACT-R03-RESULT": "R03 命中结论",
    "FACT-SUGGESTION-SCOPE": "建议使用边界",
    "FACT-COST-TREND": "近六个月融资成本序列",
  };

  function defaultChecksForFact(fact) {
    if (fact.kind.includes("Rule")) return ruleFactChecks;
    if (fact.kind.includes("建议")) return suggestionFactChecks;
    if (["日期", "质量披露", "可信度披露", "版本元数据", "报告披露"].includes(fact.kind)) return disclosureFactChecks;
    return metricFactChecks;
  }

  function locationsForFact(factId) {
    return reportEvidence.anchors
      .filter((anchor) => anchor.factId === factId)
      .map((anchor) => ({
        sectionId: anchor.sectionId,
        anchorId: anchor.id,
        location: `${sectionNameById[anchor.sectionId]} / ${anchor.id}`,
      }));
  }

  reportEvidence.facts = reportEvidence.facts.map((fact) => {
    const locations = locationsForFact(fact.id);
    const primary = locations[0] || { sectionId: "sec-evidence", anchorId: null, location: "证据与限制" };
    const anchorEvidence = reportEvidence.anchors
      .filter((anchor) => anchor.factId === fact.id)
      .flatMap((anchor) => anchor.evidence);
    return {
      ...fact,
      sectionId: primary.sectionId,
      location: primary.location,
      label: factLabelById[fact.id] || fact.id,
      evidence: [...new Set([...fact.evidence, ...anchorEvidence])],
      primaryAnchorId: primary.anchorId,
      anchorIds: locations.map((item) => item.anchorId),
      locations,
      applicableChecks: defaultChecksForFact(fact),
    };
  });

  reportEvidence.anchors = reportEvidence.anchors.map((anchor) => ({
    ...anchor,
    location: `${sectionNameById[anchor.sectionId]} / ${anchor.id}`,
    label: factLabelById[anchor.factId] || anchor.factId,
  }));

  function addReportFact({
    id,
    anchorId,
    sectionId,
    label,
    kind,
    value,
    unit = null,
    scope,
    evidence,
    resultVersion,
    ref,
    anchorType,
    applicableChecks,
    details = {},
  }) {
    const location = `${sectionNameById[sectionId]} / ${anchorId}`;
    reportEvidence.facts.push({
      id,
      sectionId,
      location,
      label,
      kind,
      value,
      unit,
      scope,
      evidence: [...evidence],
      resultVersion,
      primaryAnchorId: anchorId,
      anchorIds: [anchorId],
      locations: [{ sectionId, anchorId, location }],
      applicableChecks: [...applicableChecks],
      ...details,
    });
    reportEvidence.anchors.push({
      id: anchorId,
      sectionId,
      type: anchorType,
      ref,
      factId: id,
      evidence: [...evidence],
      location,
      label,
    });
  }

  const reportTrend = [
    { month: "2026-03", balance: 21474.2, cost: 2.4 },
    { month: "2026-04", balance: 21538.5, cost: 2.39 },
    { month: "2026-05", balance: 21602.2, cost: 2.39 },
    { month: "2026-06", balance: 21680.7, cost: 2.38 },
    { month: "2026-07", balance: 21630.5, cost: 2.38 },
    { month: "2026-08", balance: 21613.387, cost: 2.372231 },
  ];

  reportTrend.forEach((point) => {
    addReportFact({
      id: `FACT-COST-TREND-${point.month}`,
      anchorId: `chart-cost-${point.month}`,
      sectionId: "sec-cost",
      label: `${point.month} 融资成本`,
      kind: "图表数据点",
      value: point.cost,
      unit: "%",
      scope: "集团",
      evidence: ["MET-FIN-008", "MR-FIN-COST-20260809-0918", "C017-BIND-FIN-20260809-01"],
      resultVersion: "MR-20260809-0918",
      ref: "E03",
      anchorType: "图表数据点",
      applicableChecks: metricFactChecks,
      details: { dimension: { month: point.month }, contextValue: { balance: point.balance, balanceUnit: "亿元" } },
    });
  });

  [
    { unit: "单位553", key: "553", balance: 393.134, cost: 2.880984 },
    { unit: "单位465", key: "465", balance: 770, cost: 2.196617 },
    { unit: "单位561", key: "561", balance: 20.016, cost: 2.22838 },
  ].forEach((item) => {
    addReportFact({
      id: `FACT-UNIT-${item.key}-BALANCE`,
      anchorId: `unit-${item.key}-balance`,
      sectionId: "sec-units",
      label: `${item.unit}融资余额`,
      kind: "表格单元格 Metric 结果",
      value: item.balance,
      unit: "亿元",
      scope: item.unit,
      evidence: ["OBJ-ORG-UNIT", "MET-FIN-001", "MR-FIN-BALANCE-20260809-0918", "C017-BIND-FIN-20260809-01"],
      resultVersion: "MR-20260809-0918",
      ref: "E10",
      anchorType: "表格单元格",
      applicableChecks: metricFactChecks,
    });
    addReportFact({
      id: `FACT-UNIT-${item.key}-COST`,
      anchorId: `unit-${item.key}-cost`,
      sectionId: "sec-units",
      label: `${item.unit}余额加权融资成本`,
      kind: "表格单元格 Metric 结果",
      value: item.cost,
      unit: "%",
      scope: item.unit,
      evidence: ["OBJ-ORG-UNIT", "MET-FIN-008", "MR-FIN-COST-20260809-0918", "C017-BIND-FIN-20260809-01"],
      resultVersion: "MR-20260809-0918",
      ref: "E11",
      anchorType: "表格单元格",
      applicableChecks: metricFactChecks,
    });
  });

  [
    { unit: "单位553", key: "r01", rule: units["单位553"].rule, ref: "E13" },
    { unit: "单位465", key: "r02", rule: units["单位465"].rule, ref: "E14" },
    { unit: "单位561", key: "r03", rule: units["单位561"].rule, ref: "E15" },
  ].forEach(({ unit, key, rule, ref }) => {
    const conclusionFact = reportEvidence.facts.find((fact) => fact.id === `FACT-${key.toUpperCase()}-RESULT`);
    if (conclusionFact) {
      conclusionFact.evidence = [rule.id, rule.evaluationId, rule.metricId, "C017-BIND-FIN-20260809-01"];
      conclusionFact.ruleId = rule.id;
      conclusionFact.ruleVersion = rule.version;
      conclusionFact.evaluationId = rule.evaluationId;
      conclusionFact.evaluatedAt = rule.evaluatedAt;
      conclusionFact.triggeredBranch = rule.branch;
      conclusionFact.threshold = rule.threshold;
      conclusionFact.observedValue = rule.metricValue;
      conclusionFact.metricId = rule.metricId;
      conclusionFact.applicableChecks = [...ruleFactChecks];
    }
    const conclusionAnchor = reportEvidence.anchors.find((anchor) => anchor.id === `rule-${key}-result`);
    if (conclusionAnchor) conclusionAnchor.evidence = [rule.id, rule.evaluationId, rule.metricId, "C017-BIND-FIN-20260809-01"];

    addReportFact({
      id: `FACT-${key.toUpperCase()}-BRANCH`,
      anchorId: `rule-${key}-branch`,
      sectionId: "sec-rules",
      label: `${rule.code} 触发分支`,
      kind: "Rule 触发分支",
      value: rule.branch,
      scope: unit,
      evidence: [rule.id, rule.evaluationId, rule.metricId],
      resultVersion: rule.resultVersion,
      ref,
      anchorType: "Rule 分支",
      applicableChecks: ruleFactChecks,
      details: { ruleVersion: rule.version, evaluationId: rule.evaluationId },
    });
    addReportFact({
      id: `FACT-${key.toUpperCase()}-THRESHOLD`,
      anchorId: `rule-${key}-threshold`,
      sectionId: "sec-rules",
      label: `${rule.code} 阈值`,
      kind: "Rule 阈值",
      value: rule.threshold,
      unit: null,
      scope: unit,
      evidence: [rule.id, rule.evaluationId, rule.metricId],
      resultVersion: rule.resultVersion,
      ref,
      anchorType: "Rule 阈值",
      applicableChecks: ruleFactChecks,
      details: { ruleVersion: rule.version, evaluationId: rule.evaluationId, observedValue: rule.metricValue },
    });
    addReportFact({
      id: `FACT-${key.toUpperCase()}-EVALUATED-AT`,
      anchorId: `rule-${key}-evaluated-at`,
      sectionId: "sec-rules",
      label: `${rule.code} 评估时间`,
      kind: "Rule 评估时间",
      value: rule.evaluatedAt,
      scope: unit,
      evidence: [rule.id, rule.evaluationId],
      resultVersion: rule.resultVersion,
      ref,
      anchorType: "Rule 评估时间",
      applicableChecks: ruleFactChecks,
      details: { ruleVersion: rule.version, evaluationId: rule.evaluationId },
    });
  });

  addReportFact({
    id: "FACT-SUGGESTION-BASIS",
    anchorId: "suggestion-basis",
    sectionId: "sec-rules",
    label: "建议方向及依据",
    kind: "建议依据",
    value: "对单位553优先核对高成本借据置换空间；对单位465核对固定利率或利率上限条件；对单位561核对展期与中长期置换条件。",
    scope: "单位553、单位465、单位561",
    evidence: [
      "RULE-FIN-R01",
      "RULE-EVAL-R01-UNIT553-20260809-0918",
      "RULE-FIN-R02",
      "RULE-EVAL-R02-UNIT465-20260809-0918",
      "RULE-FIN-R03",
      "RULE-EVAL-R03-UNIT561-20260809-0918",
      "AT-FIN-OPT-001",
    ],
    resultVersion: "RR-20260809-0918",
    ref: "E16",
    anchorType: "建议依据",
    applicableChecks: suggestionFactChecks,
    details: {
      limitation: "仅用于人工复核参考，不等同于行动申请，不表示行动已执行。",
      basis: [
        { scope: "单位553", ruleId: "RULE-FIN-R01", ruleVersion: units["单位553"].rule.version, evaluationRecordId: units["单位553"].rule.evaluationId, resultVersion: units["单位553"].rule.resultVersion, direction: "核对高成本借据置换空间" },
        { scope: "单位465", ruleId: "RULE-FIN-R02", ruleVersion: units["单位465"].rule.version, evaluationRecordId: units["单位465"].rule.evaluationId, resultVersion: units["单位465"].rule.resultVersion, direction: "核对固定利率或利率上限条件" },
        { scope: "单位561", ruleId: "RULE-FIN-R03", ruleVersion: units["单位561"].rule.version, evaluationRecordId: units["单位561"].rule.evaluationId, resultVersion: units["单位561"].rule.resultVersion, direction: "核对展期与中长期置换条件" },
      ],
    },
  });

  [
    {
      id: "FACT-REPORT-DEFINITION-VERSION",
      anchorId: "disclosure-definition-version",
      label: "报告定义版本",
      kind: "版本元数据",
      value: "1.0.0",
      evidence: ["RD-FIN-001"],
      resultVersion: "1.0.0",
      ref: "E17",
    },
    {
      id: "FACT-REPORT-TEMPLATE-VERSION",
      anchorId: "disclosure-template-version",
      label: "报告模板版本",
      kind: "版本元数据",
      value: "2.2.0",
      evidence: ["RT-FIN-002"],
      resultVersion: "2.2.0",
      ref: "E18",
    },
    {
      id: "FACT-PUBLISHED-SEMANTIC-VERSION",
      anchorId: "disclosure-semantic-version",
      label: "已发布语义版本",
      kind: "版本元数据",
      value: "3.8.1",
      evidence: ["PUB-SEM-FIN-3.8.1", "T019-FIN-CURRENT"],
      resultVersion: "3.8.1",
      ref: "E19",
    },
    {
      id: "FACT-DATA-VERSION",
      anchorId: "disclosure-data-version",
      label: "精确数据版本",
      kind: "版本元数据",
      value: "2026.08.09-01",
      evidence: ["T007-FIN-20260809-01", "T019-FIN-CURRENT", "C017-BIND-FIN-20260809-01"],
      resultVersion: "1.0",
      ref: "E20",
    },
    {
      id: "FACT-DATA-AS-OF-DISCLOSURE",
      anchorId: "disclosure-data-asof",
      label: "数据截至时间披露",
      kind: "可信度披露",
      value: "2026-08-09",
      evidence: ["T007-FIN-20260809-01", "C017-BIND-FIN-20260809-01"],
      resultVersion: "1.0",
      ref: "E21",
    },
    {
      id: "FACT-DATA-QUALITY-STATUS",
      anchorId: "disclosure-quality",
      label: "数据质量状态",
      kind: "可信度披露",
      value: "有提示",
      evidence: ["C017-BIND-FIN-20260809-01", "PROP-GUARANTEE-TYPE"],
      resultVersion: "1.0",
      ref: "E22",
    },
    {
      id: "FACT-DATA-FRESHNESS",
      anchorId: "disclosure-freshness",
      label: "数据新鲜度",
      kind: "可信度披露",
      value: "当前",
      evidence: ["C017-BIND-FIN-20260809-01"],
      resultVersion: "1.0",
      ref: "E23",
    },
    {
      id: "FACT-DATA-READINESS",
      anchorId: "disclosure-readiness",
      label: "数据消费就绪状态",
      kind: "可信度披露",
      value: "可消费",
      evidence: ["T018-FIN-20260809-01", "C017-BIND-FIN-20260809-01"],
      resultVersion: "1.0",
      ref: "E24",
    },
    {
      id: "FACT-QUALITY-LIMITATION",
      anchorId: "disclosure-quality-limitation",
      label: "质量限制披露",
      kind: "报告披露",
      value: "担保方式未知值保持单列，不归入信用融资；该限制不外推至其他已绑定指标。",
      evidence: ["C017-BIND-FIN-20260809-01", "PROP-GUARANTEE-TYPE"],
      resultVersion: "1.0",
      ref: "E25",
    },
    {
      id: "FACT-LLM-ROLE-LIMITATION",
      anchorId: "disclosure-llm-role",
      label: "LLM 使用边界",
      kind: "报告披露",
      value: "LLM 仅组织文字，不作为数据源，不生成正式指标、比例或 Rule 结论。",
      evidence: ["RD-FIN-001", "REB-S001-FINANCE-001"],
      resultVersion: "1.0",
      ref: "E26",
    },
    {
      id: "FACT-SNAPSHOT-FREEZE-LIMITATION",
      anchorId: "disclosure-snapshot-freeze",
      label: "报告快照冻结规则",
      kind: "报告披露",
      value: "报告快照不随当前数据、模板或重新渲染原地变化。",
      evidence: ["RD-FIN-001", "REB-S001-FINANCE-001"],
      resultVersion: "1.0",
      ref: "E27",
    },
  ].forEach((item) => addReportFact({
    ...item,
    sectionId: "sec-evidence",
    unit: null,
    scope: "集团融资经营分析报告",
    anchorType: item.kind,
    applicableChecks: disclosureFactChecks,
  }));

  [
    {
      id: "FACT-JUDGMENT-COST-TREND",
      anchorId: "judgment-cost-trend",
      sectionId: "sec-overview",
      label: "融资成本趋势判断",
      kind: "有证据解释",
      value: "2026-03 至 2026-08，集团余额加权融资成本由 2.400% 降至 2.372231%，整体下降，且近三个月降幅收窄。",
      scope: "集团",
      evidence: [
        "MET-FIN-008",
        "MR-FIN-COST-20260809-0918",
        "FACT-COST-TREND-2026-03",
        "FACT-COST-TREND-2026-06",
        "FACT-COST-TREND-2026-08",
      ],
      resultVersion: "MR-20260809-0918",
      ref: "E28",
      anchorType: "趋势判断",
      applicableChecks: metricFactChecks,
      details: {
        contentRole: "interpretation",
        origin: "agent",
        basisFactRefs: ["FACT-COST-TREND-2026-03", "FACT-COST-TREND-2026-06", "FACT-COST-TREND-2026-08"],
        limitation: "只解释固定趋势数据点，不预测未来融资成本。",
      },
    },
    {
      id: "FACT-JUDGMENT-FLOATING-EXPOSURE",
      anchorId: "judgment-floating-exposure",
      sectionId: "sec-overview",
      label: "浮动利率敞口判断",
      kind: "有证据解释",
      value: "浮动利率融资仍占主要部分，需结合利率环境持续观察重定价风险。",
      scope: "集团",
      evidence: ["MET-FIN-010", "MR-FIN-FLOATING-20260809-0918"],
      resultVersion: "MR-20260809-0918",
      ref: "E29",
      anchorType: "结构判断",
      applicableChecks: metricFactChecks,
      details: {
        contentRole: "interpretation",
        origin: "agent",
        basisFactRefs: ["FACT-GROUP-FLOATING"],
        limitation: "不构成利率预测或行动结论。",
      },
    },
    {
      id: "FACT-JUDGMENT-COST-LOW",
      anchorId: "judgment-cost-low",
      sectionId: "sec-cost",
      label: "融资成本区间判断",
      kind: "有证据解释",
      value: "集团当前融资成本处于本报告固定趋势区间低位。",
      scope: "集团",
      evidence: ["MET-FIN-008", "MR-FIN-COST-20260809-0918", "FACT-COST-TREND-2026-03", "FACT-COST-TREND-2026-08"],
      resultVersion: "MR-20260809-0918",
      ref: "E30",
      anchorType: "趋势判断",
      applicableChecks: metricFactChecks,
      details: {
        contentRole: "interpretation",
        origin: "agent",
        basisFactRefs: ["FACT-COST-TREND-2026-03", "FACT-COST-TREND-2026-08"],
      },
    },
    {
      id: "FACT-JUDGMENT-HIGH-COST-UNIT553",
      anchorId: "judgment-high-cost-unit553",
      sectionId: "sec-cost",
      label: "高成本融资重点单位判断",
      kind: "有证据解释",
      value: "重点高成本融资集中在单位553。",
      scope: "单位553",
      evidence: ["MET-FIN-011", "RULE-FIN-R01", "RULE-EVAL-R01-UNIT553-20260809-0918"],
      resultVersion: "RR-20260809-0918",
      ref: "E31",
      anchorType: "单位判断",
      applicableChecks: ruleFactChecks,
      details: {
        contentRole: "interpretation",
        origin: "agent",
        basisFactRefs: ["FACT-UNIT-553-BALANCE", "FACT-R01-RESULT", "FACT-R01-THRESHOLD"],
        ruleId: "RULE-FIN-R01",
        ruleVersion: units["单位553"].rule.version,
        evaluationId: units["单位553"].rule.evaluationId,
        evaluatedAt: units["单位553"].rule.evaluatedAt,
        triggeredBranch: units["单位553"].rule.branch,
        threshold: units["单位553"].rule.threshold,
        observedValue: units["单位553"].rule.metricValue,
        metricId: units["单位553"].rule.metricId,
      },
    },
    {
      id: "FACT-DISCLOSURE-WEIGHTED-METHOD",
      anchorId: "disclosure-weighted-method",
      sectionId: "sec-cost",
      label: "余额加权方法披露",
      kind: "语义披露",
      value: "余额加权方法避免小额融资与大额融资等权；报告正文不重新计算该指标。",
      scope: "集团融资经营分析报告",
      evidence: ["MET-FIN-008", "RD-FIN-001"],
      resultVersion: "3.8.1",
      ref: "E32",
      anchorType: "指标口径披露",
      applicableChecks: disclosureFactChecks,
      details: {
        contentRole: "deterministic",
        origin: "template",
        basisFactRefs: ["FACT-GROUP-COST"],
      },
    },
    {
      id: "FACT-JUDGMENT-FLOATING-HIGH",
      anchorId: "judgment-floating-high",
      sectionId: "sec-structure",
      label: "浮动利率结构说明",
      kind: "有证据解释",
      value: "浮动利率余额占比较高，组合存在较高重定价暴露。",
      scope: "集团",
      evidence: ["MET-FIN-010", "MR-FIN-FLOATING-20260809-0918"],
      resultVersion: "MR-20260809-0918",
      ref: "E33",
      anchorType: "结构判断",
      applicableChecks: metricFactChecks,
      details: { contentRole: "interpretation", origin: "agent", basisFactRefs: ["FACT-GROUP-FLOATING"] },
    },
    {
      id: "FACT-JUDGMENT-SHORT-LOW",
      anchorId: "judgment-short-low",
      sectionId: "sec-structure",
      label: "短期债务结构说明",
      kind: "有证据解释",
      value: "集团总体短期债务余额占比较低。",
      scope: "集团",
      evidence: ["MET-FIN-012", "MR-FIN-SHORT-TERM-20260809-0918"],
      resultVersion: "MR-20260809-0918",
      ref: "E34",
      anchorType: "结构判断",
      applicableChecks: metricFactChecks,
      details: { contentRole: "interpretation", origin: "agent", basisFactRefs: ["FACT-GROUP-SHORT"] },
    },
    {
      id: "FACT-UNIT553-FOREIGN-CURRENCY",
      anchorId: "judgment-unit553-foreign",
      sectionId: "sec-structure",
      label: "单位553外币融资说明",
      kind: "有证据解释",
      value: "单位553的存续融资以英镑融资为主。",
      scope: "单位553",
      evidence: ["OBJ-ORG-UNIT", "PROP-CURRENCY", "C017-BIND-FIN-20260809-01"],
      resultVersion: "MR-20260809-0918",
      ref: "E35",
      anchorType: "单位判断",
      applicableChecks: metricFactChecks,
      details: {
        contentRole: "interpretation",
        origin: "agent",
        basisFactRefs: ["FACT-UNIT-553-BALANCE"],
        limitation: "仅说明本报告固定数据范围，不外推至报告截至时间之后。",
      },
    },
    {
      id: "FACT-INSTITUTION-PRIORITY-BASIS",
      anchorId: "institution-priority-basis",
      sectionId: "sec-units",
      label: "优先机构排序依据",
      kind: "Rule 命中证据",
      value: "该排序来自单位553的 R01 命中证据，不等同于集团总体融资余额最大的机构。",
      scope: "单位553",
      evidence: ["RULE-FIN-R01", "RULE-EVAL-R01-UNIT553-20260809-0918", "MET-FIN-011"],
      resultVersion: "RR-20260809-0918",
      ref: "E36",
      anchorType: "机构优先说明",
      applicableChecks: ruleFactChecks,
      details: {
        contentRole: "deterministic",
        origin: "agent",
        basisFactRefs: ["FACT-R01-INSTITUTIONS", "FACT-R01-RESULT", "FACT-R01-BRANCH"],
        ruleId: "RULE-FIN-R01",
        ruleVersion: units["单位553"].rule.version,
        evaluationId: units["单位553"].rule.evaluationId,
        evaluatedAt: units["单位553"].rule.evaluatedAt,
        triggeredBranch: units["单位553"].rule.branch,
        threshold: units["单位553"].rule.threshold,
        observedValue: units["单位553"].rule.metricValue,
        metricId: units["单位553"].rule.metricId,
      },
    },
    {
      id: "FACT-DISCLOSURE-FIXED-RESULTS",
      anchorId: "disclosure-fixed-results",
      sectionId: "sec-cost",
      label: "固定结果使用披露",
      kind: "报告披露",
      value: "报告中的比例、数值和 Rule 结论均引用生成时固定结果，不在正文渲染时重新计算。",
      scope: "集团融资经营分析报告",
      evidence: ["RD-FIN-001", "REB-S001-FINANCE-001"],
      resultVersion: "1.0",
      ref: "E37",
      anchorType: "报告披露",
      applicableChecks: disclosureFactChecks,
      details: { contentRole: "deterministic", origin: "template" },
    },
  ].forEach((item) => addReportFact(item));

  const semanticResourceById = new Map([
    ...semanticResources,
    ...Object.values(metrics),
    ...rules,
    ...actionTypes,
  ].map((resource) => [resource.id, resource]));
  const ruleEvaluationByRuleId = new Map(Object.values(units).map((unit) => [unit.rule.id, unit.rule]));
  const metricByResultVersion = new Map(Object.values(metrics).map((metric) => [metric.resultVersion, metric]));
  const fixedTrustSnapshot = {
    dataVersion: authoritativeConsumption.current.dataVersion,
    asOf: authoritativeConsumption.current.asOf,
    qualityStatus: dataTrust.bindingSummary.publishedQuality,
    freshnessStatus: dataTrust.bindingSummary.freshness,
    consumptionReadiness: dataTrust.bindingSummary.readiness,
    limitations: [
      "担保方式存在未知值，必须单列披露。",
      "数据可信度摘要不提供业务明细，也不重新计算 Metric 或 Rule。",
    ],
  };
  const fixedAuthorityBinding = {
    bindingId: authoritativeConsumption.current.bindingId,
    publishedSemanticVersion: authoritativeConsumption.current.semanticVersion,
    semanticVersionId: authoritativeConsumption.current.semanticVersionId,
    dataAssetVersionId: authoritativeConsumption.current.dataAssetVersionId,
    consumableVersionId: authoritativeConsumption.current.consumableVersionId,
    dataVersion: authoritativeConsumption.current.dataVersion,
    resultVersion: "MR-20260809-0918 / RR-20260809-0918",
    resultVersions: {
      metric: "MR-20260809-0918",
      rule: "RR-20260809-0918",
    },
    asOf: authoritativeConsumption.current.asOf,
    previousTrustedCombination: {
      bindingId: authoritativeConsumption.previousAuthoritative.bindingId,
      publishedSemanticVersion: authoritativeConsumption.previousAuthoritative.semanticVersion,
      dataAssetVersionId: authoritativeConsumption.previousAuthoritative.dataAssetVersionId,
      consumableVersionId: authoritativeConsumption.previousAuthoritative.consumableVersionId,
      dataVersion: authoritativeConsumption.previousAuthoritative.dataVersion,
      asOf: authoritativeConsumption.previousAuthoritative.asOf,
      status: "只读参考，未被本次报告采用",
    },
  };

  function displayFactValue(value, unit) {
    if (value == null) return null;
    if (typeof value !== "number") return String(value);
    const formatted = new Intl.NumberFormat("zh-CN", {
      maximumFractionDigits: unit === "%" ? 6 : 3,
      minimumFractionDigits: 0,
    }).format(value);
    return unit ? `${formatted}${unit === "%" ? "%" : ` ${unit}`}` : formatted;
  }

  function parseComparableValue(value, fallbackUnit = null) {
    if (typeof value === "number") return { value, unit: fallbackUnit };
    const match = String(value || "").trim().match(/^(>=|<=|>|<|=)?\s*(-?\d+(?:\.\d+)?)\s*(.*)$/);
    if (!match) return { text: value == null ? null : String(value), unit: fallbackUnit };
    return {
      operator: match[1] || "=",
      value: Number(match[2]),
      unit: match[3] || fallbackUnit || null,
    };
  }

  function semanticSnapshotForFact(fact) {
    const resourceId = fact.ruleId
      || (fact.evidence || []).find((id) => semanticResourceById.has(id))
      || metricByResultVersion.get(fact.resultVersion)?.id
      || null;
    const resource = resourceId ? semanticResourceById.get(resourceId) : null;
    if (!resource) {
      return {
        name: "报告内容与证据绑定",
        definition: "报告中心对固定内容项、稳定锚点和生成证据包的绑定合同。",
        unit: fact.unit || null,
        applicableObject: fact.scope || null,
        filters: null,
        timeRange: authoritativeConsumption.current.asOf,
        effectiveFrom: null,
        effectiveTo: null,
        resourceType: "Report Evidence Contract",
        resourceId: reportEvidence.bindingId,
        publishedVersion: reportEvidence.version,
      };
    }
    const effectiveText = resource.effective || "";
    const effectiveParts = String(effectiveText).split(/[—至]/).map((item) => item.trim()).filter(Boolean);
    return {
      name: resource.name,
      definition: resource.definition || resource.description || null,
      unit: resource.unit || fact.unit || null,
      applicableObject: resource.appliesTo || fact.scope || null,
      filters: resource.filter || null,
      timeRange: resource.dataAsOf || authoritativeConsumption.current.asOf,
      effectiveFrom: effectiveParts[0] || null,
      effectiveTo: effectiveParts[1] || null,
      resourceType: resource.type,
      resourceId: resource.id,
      publishedVersion: resource.definitionVersion || resource.version || resource.publishedSemanticVersion,
    };
  }

  function ruleSnapshotForFact(fact) {
    const ruleId = fact.ruleId || (fact.evidence || []).find((id) => ruleEvaluationByRuleId.has(id));
    if (!ruleId) return null;
    const evaluation = ruleEvaluationByRuleId.get(ruleId);
    return {
      ruleId,
      ruleVersion: fact.ruleVersion || evaluation?.version || null,
      evaluationTime: fact.evaluatedAt || evaluation?.evaluatedAt || null,
      branch: fact.triggeredBranch || evaluation?.branch || null,
      observedValue: parseComparableValue(fact.observedValue || evaluation?.metricValue, "%"),
      threshold: parseComparableValue(fact.threshold || evaluation?.threshold, "%"),
      result: String(fact.kind || "").includes("结论") ? fact.value : evaluation?.status || null,
      evaluationRecordId: fact.evaluationId || evaluation?.evaluationId || null,
      metricId: fact.metricId || evaluation?.metricId || null,
      subject: fact.scope || null,
    };
  }

  function contentRoleForFact(fact) {
    if (fact.contentRole) return fact.contentRole;
    if (["有证据解释", "建议依据"].includes(fact.kind)) return "interpretation";
    return "deterministic";
  }

  function originForFact(fact) {
    if (fact.origin) return fact.origin;
    if (["版本元数据", "可信度披露", "报告披露", "语义披露"].includes(fact.kind)) return "template";
    return contentRoleForFact(fact) === "interpretation" ? "agent" : "deterministic";
  }

  const institutionPriorityFact = reportEvidence.facts.find((fact) => fact.id === "FACT-R01-INSTITUTIONS");
  if (institutionPriorityFact) {
    institutionPriorityFact.evidence = [
      "RULE-FIN-R01",
      "RULE-EVAL-R01-UNIT553-20260809-0918",
      "MET-FIN-011",
      "C017-BIND-FIN-20260809-01",
    ];
    institutionPriorityFact.ruleId = units["单位553"].rule.id;
    institutionPriorityFact.ruleVersion = units["单位553"].rule.version;
    institutionPriorityFact.evaluationId = units["单位553"].rule.evaluationId;
    institutionPriorityFact.evaluatedAt = units["单位553"].rule.evaluatedAt;
    institutionPriorityFact.triggeredBranch = units["单位553"].rule.branch;
    institutionPriorityFact.threshold = units["单位553"].rule.threshold;
    institutionPriorityFact.observedValue = units["单位553"].rule.metricValue;
    institutionPriorityFact.metricId = units["单位553"].rule.metricId;
  }

  reportEvidence.facts = reportEvidence.facts.map((fact) => {
    const semanticSnapshot = semanticSnapshotForFact(fact);
    const scopeKey = fact.scope || "集团融资经营分析报告";
    const timeRange = fact.dimension?.month || semanticSnapshot.timeRange || authoritativeConsumption.current.asOf;
    const aggregation = semanticSnapshot.resourceType === "Metric" ? "Published Metric 结果" : fact.kind;
    const normalizedValue = typeof fact.value === "number" ? Number(fact.value) : fact.value;
    return {
      ...fact,
      contentRole: contentRoleForFact(fact),
      origin: originForFact(fact),
      claimType: fact.kind,
      semanticResourceId: semanticSnapshot.resourceId,
      semanticResourceType: semanticSnapshot.resourceType,
      semanticResourceVersion: semanticSnapshot.publishedVersion,
      semanticSnapshot,
      trustSnapshot: { ...fixedTrustSnapshot, limitations: [...fixedTrustSnapshot.limitations] },
      scopeKey,
      timeRange,
      aggregation,
      normalizedValue,
      displayValue: displayFactValue(fact.value, fact.unit),
      displayUnit: fact.unit || null,
      roundingRule: typeof fact.value === "number" ? (fact.unit === "%" ? "最多 6 位小数" : "最多 3 位小数") : "不适用",
      authorityBindingId: fixedAuthorityBinding.bindingId,
      semanticVersionId: fixedAuthorityBinding.semanticVersionId,
      dataAssetVersionId: fixedAuthorityBinding.dataAssetVersionId,
      consumableVersionId: fixedAuthorityBinding.consumableVersionId,
      dataVersion: fixedAuthorityBinding.dataVersion,
      resultId: (fact.evidence || []).find((id) => /^MR-|^RULE-EVAL-/.test(id)) || null,
      asOf: fixedAuthorityBinding.asOf,
      canonicalFactKey: [fact.id, scopeKey, timeRange, fact.unit || "none", aggregation, fact.resultVersion || "none"].join("|"),
      ruleSnapshot: ruleSnapshotForFact(fact),
    };
  });

  const factById = new Map(reportEvidence.facts.map((fact) => [fact.id, fact]));
  const narrativeSpecs = [
    {
      id: "overview",
      anchorId: "narrative-overview",
      sectionId: "sec-overview",
      text: "集团融资余额、余额加权融资成本与浮动利率敞口概览。",
      factRefs: ["FACT-GROUP-BALANCE", "FACT-GROUP-COST", "FACT-GROUP-FLOATING"],
      contentRole: "deterministic",
    },
    {
      id: "overview-judgment",
      anchorId: "narrative-overview-judgment",
      sectionId: "sec-overview",
      text: "融资成本趋势与浮动利率重定价风险说明。",
      factRefs: ["FACT-JUDGMENT-COST-TREND", "FACT-JUDGMENT-FLOATING-EXPOSURE"],
      contentRole: "interpretation",
    },
    {
      id: "cost",
      anchorId: "narrative-cost",
      sectionId: "sec-cost",
      text: "高成本融资占比、趋势区间及重点单位说明。",
      factRefs: ["FACT-GROUP-HIGH-COST", "FACT-JUDGMENT-COST-LOW", "FACT-JUDGMENT-HIGH-COST-UNIT553"],
      contentRole: "interpretation",
    },
    {
      id: "cost-method",
      anchorId: "narrative-cost-method",
      sectionId: "sec-cost",
      text: "余额加权口径与固定结果使用边界。",
      factRefs: ["FACT-DISCLOSURE-WEIGHTED-METHOD", "FACT-DISCLOSURE-FIXED-RESULTS"],
      contentRole: "deterministic",
    },
    {
      id: "structure",
      anchorId: "narrative-structure",
      sectionId: "sec-structure",
      text: "短期、外币、信用及浮动利率结构说明。",
      factRefs: ["FACT-GROUP-SHORT", "FACT-GROUP-FOREIGN", "FACT-GROUP-CREDIT", "FACT-JUDGMENT-FLOATING-HIGH", "FACT-JUDGMENT-SHORT-LOW", "FACT-UNIT553-FOREIGN-CURRENCY"],
      contentRole: "interpretation",
    },
    {
      id: "unit-comparison",
      anchorId: "narrative-unit-comparison",
      sectionId: "sec-units",
      text: "三家重点单位组合比较。",
      factRefs: ["FACT-THREE-UNIT-BALANCE", "FACT-THREE-UNIT-COST"],
      contentRole: "deterministic",
    },
    {
      id: "institution-priority",
      anchorId: "narrative-institution-priority",
      sectionId: "sec-units",
      text: "单位553优先机构及排序口径说明。",
      factRefs: ["FACT-R01-INSTITUTIONS", "FACT-INSTITUTION-PRIORITY-BASIS"],
      contentRole: "deterministic",
    },
    ...["R01", "R02", "R03"].map((code) => ({
      id: `rule-${code.toLowerCase()}`,
      anchorId: `narrative-rule-${code.toLowerCase()}`,
      sectionId: "sec-rules",
      text: `${code} 结论、触发分支、阈值与评估时间。`,
      factRefs: [`FACT-${code}-RESULT`, `FACT-${code}-BRANCH`, `FACT-${code}-THRESHOLD`, `FACT-${code}-EVALUATED-AT`],
      contentRole: "deterministic",
    })),
    {
      id: "suggestion",
      anchorId: "narrative-suggestion",
      sectionId: "sec-rules",
      text: "基于规则触发证据形成复核建议，不等同于行动申请。",
      factRefs: ["FACT-SUGGESTION-SCOPE", "FACT-SUGGESTION-BASIS"],
      contentRole: "interpretation",
    },
    {
      id: "trust-disclosure",
      anchorId: "narrative-trust-disclosure",
      sectionId: "sec-evidence",
      text: "报告定义、模板、语义、数据版本、时点、质量、新鲜度、消费状态及使用限制披露。",
      factRefs: [
        "FACT-REPORT-DEFINITION-VERSION",
        "FACT-REPORT-TEMPLATE-VERSION",
        "FACT-PUBLISHED-SEMANTIC-VERSION",
        "FACT-DATA-VERSION",
        "FACT-DATA-AS-OF-DISCLOSURE",
        "FACT-DATA-QUALITY-STATUS",
        "FACT-DATA-FRESHNESS",
        "FACT-DATA-READINESS",
        "FACT-QUALITY-LIMITATION",
        "FACT-LLM-ROLE-LIMITATION",
        "FACT-SNAPSHOT-FREEZE-LIMITATION",
      ],
      contentRole: "deterministic",
    },
  ];

  narrativeSpecs.forEach((item, index) => {
    const facts = item.factRefs.map((factId) => factById.get(factId)).filter(Boolean);
    const evidence = [...new Set(facts.flatMap((fact) => fact.evidence || []))];
    const narrativeAnchor = {
      id: item.anchorId,
      sectionId: item.sectionId,
      type: "段落",
      ref: `N${String(index + 1).padStart(2, "0")}`,
      factId: item.factRefs[0],
      factRefs: [...item.factRefs],
      evidence,
      location: `${sectionNameById[item.sectionId]} / ${item.anchorId}`,
      label: item.text,
      contentItemId: `RCI-${item.anchorId}`,
      contentRole: item.contentRole,
      origin: "agent",
      claimType: "narrative",
      presentationType: "paragraph",
      templateSlot: item.sectionId,
      bindingStatus: facts.length === item.factRefs.length && evidence.length ? "bound" : "missing",
      requiresEvidence: true,
      renderedValue: item.text,
      displayValue: item.text,
      displayUnit: null,
      htmlAnchorId: item.anchorId,
      pdfAnchorId: `pdf-${item.anchorId}`,
      narrativeId: item.id,
    };
    const existingAnchor = reportEvidence.anchors.find((anchor) => anchor.id === item.anchorId);
    if (existingAnchor) Object.assign(existingAnchor, narrativeAnchor);
    else reportEvidence.anchors.push(narrativeAnchor);
  });

  const presentationTypeByAnchorType = {
    "日期": "date",
    "数值": "metric-value",
    "指标卡数值": "metric-card",
    "段落数值": "paragraph-value",
    "表格单元格": "table-cell",
    "图表": "chart",
    "图表数据点": "chart-data-point",
    "Rule 结论": "rule-conclusion",
    "Rule 分支": "rule-branch",
    "Rule 阈值": "rule-threshold",
    "Rule 评估时间": "rule-evaluation-time",
    "建议": "recommendation",
    "建议依据": "recommendation-basis",
    "段落": "paragraph",
  };

  reportEvidence.anchors = reportEvidence.anchors.map((anchor) => {
    const factRefs = [...new Set(anchor.factRefs || (anchor.factId ? [anchor.factId] : []))];
    const facts = factRefs.map((factId) => factById.get(factId)).filter(Boolean);
    const evidenceRefs = [...new Set([...(anchor.evidence || []), ...facts.flatMap((fact) => fact.evidence || [])])];
    const primaryFact = facts[0] || null;
    const requiresEvidence = anchor.requiresEvidence !== false;
    return {
      ...anchor,
      contentItemId: anchor.contentItemId || `RCI-${anchor.id}`,
      contentRole: anchor.contentRole || primaryFact?.contentRole || "deterministic",
      origin: anchor.origin || primaryFact?.origin || "deterministic",
      generationOwner: (anchor.origin || primaryFact?.origin) === "template" ? "报告中心" : "Agent 应用",
      bindingOwner: "报告中心",
      semanticAuthorityOwner: "本体管理",
      dataTrustOwner: "数据工程",
      claimType: anchor.claimType || primaryFact?.claimType || anchor.type,
      presentationType: anchor.presentationType || presentationTypeByAnchorType[anchor.type] || "content-item",
      templateSlot: anchor.templateSlot || anchor.sectionId,
      factRefs,
      evidenceRefs,
      bindingStatus: anchor.bindingStatus || (requiresEvidence && (facts.length !== factRefs.length || !evidenceRefs.length) ? "missing" : requiresEvidence ? "bound" : "not-required"),
      requiresEvidence,
      evidenceNotRequiredReason: requiresEvidence ? null : anchor.evidenceNotRequiredReason || "模板静态结构不声明业务事实。",
      renderedValue: anchor.renderedValue ?? primaryFact?.displayValue ?? anchor.label,
      displayValue: anchor.displayValue ?? primaryFact?.displayValue ?? anchor.label,
      displayUnit: anchor.displayUnit ?? primaryFact?.displayUnit ?? null,
      semanticSnapshot: primaryFact?.semanticSnapshot || null,
      trustSnapshot: primaryFact?.trustSnapshot || { ...fixedTrustSnapshot, limitations: [...fixedTrustSnapshot.limitations] },
      ruleSnapshot: primaryFact?.ruleSnapshot || null,
      canonicalFactKey: primaryFact?.canonicalFactKey || null,
      htmlAnchorId: anchor.htmlAnchorId || anchor.id,
      pdfAnchorId: anchor.pdfAnchorId || `pdf-${anchor.id}`,
    };
  });

  const emptySemanticSnapshot = {
    name: null,
    definition: null,
    unit: null,
    applicableObject: null,
    filters: null,
    timeRange: null,
    effectiveFrom: null,
    effectiveTo: null,
    resourceType: null,
    resourceId: null,
    publishedVersion: null,
  };
  const templateContentItems = [
    { id: "report-cover-title", sectionId: "sec-overview", value: "集团融资成本与债务结构分析报告", presentationType: "report-title" },
    ...reportEvidence.sections.map((section) => ({ id: `heading-${section.id}`, sectionId: section.id, value: section.name, presentationType: "section-heading" })),
    { id: "report-footnote-label", sectionId: "sec-evidence", value: "HTML 阅读版与 PDF 固定版共享报告标识、内容版本和证据链。", presentationType: "footnote" },
  ].map((item) => ({
    contentItemId: `RCI-TEMPLATE-${item.id}`,
    contentRole: "layout",
    origin: "template",
    generationOwner: "报告中心",
    bindingOwner: "报告中心",
    semanticAuthorityOwner: "不适用",
    dataTrustOwner: "不适用",
    claimType: "template-text",
    presentationType: item.presentationType,
    templateSlot: item.sectionId,
    factRefs: [],
    evidenceRefs: [],
    bindingStatus: "not-required",
    requiresEvidence: false,
    evidenceNotRequiredReason: "报告模板固定结构，不声明业务事实。",
    renderedValue: item.value,
    displayValue: item.value,
    displayUnit: null,
    semanticSnapshot: { ...emptySemanticSnapshot },
    trustSnapshot: null,
    ruleSnapshot: null,
    canonicalFactKey: null,
    htmlAnchorId: item.id,
    pdfAnchorId: `pdf-${item.id}`,
  }));
  const anchoredContentItems = reportEvidence.anchors.map((anchor) => ({
    contentItemId: anchor.contentItemId,
    contentRole: anchor.contentRole,
    origin: anchor.origin,
    generationOwner: anchor.generationOwner,
    bindingOwner: anchor.bindingOwner,
    semanticAuthorityOwner: anchor.semanticAuthorityOwner,
    dataTrustOwner: anchor.dataTrustOwner,
    claimType: anchor.claimType,
    presentationType: anchor.presentationType,
    templateSlot: anchor.templateSlot,
    anchorId: anchor.id,
    factRefs: [...anchor.factRefs],
    evidenceRefs: [...anchor.evidenceRefs],
    bindingStatus: anchor.bindingStatus,
    requiresEvidence: anchor.requiresEvidence,
    evidenceNotRequiredReason: anchor.evidenceNotRequiredReason,
    renderedValue: anchor.renderedValue,
    displayValue: anchor.displayValue,
    displayUnit: anchor.displayUnit,
    semanticSnapshot: anchor.semanticSnapshot ? { ...anchor.semanticSnapshot } : { ...emptySemanticSnapshot },
    trustSnapshot: anchor.trustSnapshot ? { ...anchor.trustSnapshot, limitations: [...(anchor.trustSnapshot.limitations || [])] } : null,
    ruleSnapshot: anchor.ruleSnapshot ? { ...anchor.ruleSnapshot } : null,
    canonicalFactKey: anchor.canonicalFactKey,
    htmlAnchorId: anchor.htmlAnchorId,
    pdfAnchorId: anchor.pdfAnchorId,
    narrativeId: anchor.narrativeId || null,
  }));

  reportEvidence.schemaVersion = "1.1";
  reportEvidence.factInventoryVersion = "1.1";
  reportEvidence.contentManifestVersion = "1.0";
  reportEvidence.verificationRuleVersion = "1.5.0";
  reportEvidence.owner = "报告中心";
  reportEvidence.verificationChecks = verificationChecks;
  reportEvidence.authoritativeBinding = fixedAuthorityBinding;
  reportEvidence.contentItems = [...templateContentItems, ...anchoredContentItems];
  reportEvidence.renderManifest = {
    manifestId: "RCM-S001-FINANCE-001",
    version: reportEvidence.contentManifestVersion,
    owner: "报告中心",
    reportDefinitionId: "RD-FIN-001",
    templateId: "RT-FIN-002",
    authoritativeBinding: fixedAuthorityBinding,
    items: reportEvidence.contentItems,
    inclusionRule: "模板静态项、Agent 结构化段落、确定性事实、表格单元格、图表数据点、Rule 结论和披露必须全部进入同一清单；清单外正文不得进入确认或发布。",
  };
  reportEvidence.generatedNarrativeContract = {
    version: "1.0",
    owner: "Agent 应用生成内容项；报告中心冻结选择、锚点和证据绑定",
    narratives: narrativeSpecs.map((item) => ({
      narrativeId: item.id,
      contentItemId: `RCI-${item.anchorId}`,
      anchorId: item.anchorId,
      templateSlot: item.sectionId,
      contentRole: item.contentRole,
      allowedFactRefs: [...item.factRefs],
      bindingRequired: true,
    })),
    sourceItemProjection: "每个 narrative 同时登记为稳定 anchor；buildSourceItems 可据此形成 source item，buildContentContract 必须再与 renderManifest 按 contentItemId/anchorId 合并，以保留多事实 factRefs。",
    acceptanceRule: "Agent 返回的每个 narrative/content item 必须匹配既定 contentItemId、templateSlot 和允许的 factRefs/evidenceRefs；缺失或新增未登记项由无绑定内容检查判定。",
  };
  
  reportEvidence.factPackageContract = {
    contentFactOwner: "报告中心",
    authoritativeBindingOwner: "本体管理",
    semanticEvidenceOwner: "本体管理",
    dataTrustOwner: "数据工程",
    fixationRule: "生成证据包固定时复制对应权威组合的事实包；后续权威组合变化不得改写已固定事实。",
    unavailableRule: "事实包不可用时返回无法核验；不得使用当前已发布定义、当前数据或其他版本事实替代。",
    contentManifestRule: "生成时同时冻结事实库存、Agent 结构化内容项、模板静态项和 renderManifest；核验以内容项清单为全集，不能只遍历已形成事实。",
  };

  const cloneFactRecord = (fact) => ({
    ...fact,
    evidence: [...fact.evidence],
    applicableChecks: [...fact.applicableChecks],
    anchorIds: [...fact.anchorIds],
    locations: fact.locations.map((location) => ({ ...location })),
    basisFactRefs: [...(fact.basisFactRefs || [])],
    semanticSnapshot: fact.semanticSnapshot ? { ...fact.semanticSnapshot } : null,
    trustSnapshot: fact.trustSnapshot ? { ...fact.trustSnapshot, limitations: [...(fact.trustSnapshot.limitations || [])] } : null,
    ruleSnapshot: fact.ruleSnapshot ? { ...fact.ruleSnapshot } : null,
  });
  const cloneAnchorRecord = (anchor) => ({
    ...anchor,
    evidence: [...(anchor.evidence || [])],
    factRefs: [...(anchor.factRefs || [])],
    evidenceRefs: [...(anchor.evidenceRefs || [])],
    semanticSnapshot: anchor.semanticSnapshot ? { ...anchor.semanticSnapshot } : null,
    trustSnapshot: anchor.trustSnapshot ? { ...anchor.trustSnapshot, limitations: [...(anchor.trustSnapshot.limitations || [])] } : null,
    ruleSnapshot: anchor.ruleSnapshot ? { ...anchor.ruleSnapshot } : null,
  });

  const cloneContentItemRecord = (item) => ({
    ...item,
    factRefs: [...(item.factRefs || [])],
    evidenceRefs: [...(item.evidenceRefs || [])],
    semanticSnapshot: item.semanticSnapshot ? { ...item.semanticSnapshot } : null,
    trustSnapshot: item.trustSnapshot ? { ...item.trustSnapshot, limitations: [...(item.trustSnapshot.limitations || [])] } : null,
    ruleSnapshot: item.ruleSnapshot ? { ...item.ruleSnapshot } : null,
  });

  reportEvidence.factPackages = {
    "2026.08.09-01": {
      packageId: "RFP-S001-FIN-20260809-01",
      packageVersion: "1.0",
      schemaVersion: reportEvidence.schemaVersion,
      factInventoryVersion: reportEvidence.factInventoryVersion,
      status: "available",
      factPackageStatus: "available",
      sceneId: "S001",
      reportDefinitionId: "RD-FIN-001",
      reportDefinitionVersion: "1.0.0",
      templateId: "RT-FIN-002",
      templateVersion: "2.2.0",
      authorityBindingId: "T019-FIN-CURRENT",
      semanticVersionId: "PUB-SEM-FIN-3.8.1",
      semanticVersion: "3.8.1",
      dataAssetVersionId: "T007-FIN-20260809-01",
      dataVersion: "2026.08.09-01",
      consumableVersionId: "T018-FIN-20260809-01",
      asOf: "2026-08-09",
      quality: "有提示",
      freshness: "当前",
      readiness: "可消费",
      resultVersions: {
        metric: "MR-20260809-0918",
        rule: "RR-20260809-0918",
      },
      owners: {
        contentFacts: "报告中心",
        contentManifest: "报告中心",
        authoritativeBinding: "本体管理",
        semanticEvidence: "本体管理",
        dataTrust: "数据工程",
      },
      authoritativeBinding: {
        ...reportEvidence.authoritativeBinding,
        resultVersions: { ...reportEvidence.authoritativeBinding.resultVersions },
        previousTrustedCombination: { ...reportEvidence.authoritativeBinding.previousTrustedCombination },
      },
      contentFacts: reportEvidence.facts.map(cloneFactRecord),
      anchors: reportEvidence.anchors.map(cloneAnchorRecord),
      contentItems: reportEvidence.contentItems.map(cloneContentItemRecord),
      renderManifest: {
        ...reportEvidence.renderManifest,
        authoritativeBinding: {
          ...reportEvidence.renderManifest.authoritativeBinding,
          resultVersions: { ...reportEvidence.renderManifest.authoritativeBinding.resultVersions },
          previousTrustedCombination: { ...reportEvidence.renderManifest.authoritativeBinding.previousTrustedCombination },
        },
        items: reportEvidence.contentItems.map(cloneContentItemRecord),
      },
      generatedNarrativeContract: {
        ...reportEvidence.generatedNarrativeContract,
        narratives: reportEvidence.generatedNarrativeContract.narratives.map((item) => ({
          ...item,
          allowedFactRefs: [...item.allowedFactRefs],
        })),
      },
      groupMetrics: { ...groupMetrics },
      units: Object.fromEntries(Object.entries(units).map(([name, unit]) => [name, {
        ...unit,
        rule: { ...unit.rule },
        institutions: unit.institutions.map((institution) => ({ ...institution })),
        loans: unit.loans.map((loan) => ({ ...loan })),
      }])),
      comparisons: Object.fromEntries(Object.entries(comparisons).map(([key, value]) => [key, { ...value }])),
      trend: reportTrend.map((point) => ({ ...point })),
      structures: {
        rate: [
          { name: "浮动利率", value: 95.149492 },
          { name: "固定利率", value: 4.850508 },
        ],
        term: [
          { name: "长期", value: 95.022 },
          { name: "中期", value: 3.503 },
          { name: "短期", value: 0.912 },
          { name: "未知", value: 0.563 },
        ],
        currency: [
          { name: "人民币", value: 95.775868 },
          { name: "外币", value: 4.224132 },
        ],
        guarantee: [
          { name: "信用", value: 34.680039 },
          { name: "质押", value: 34.337 },
          { name: "其他担保", value: 3.547 },
          { name: "未知", value: 27.436 },
        ],
        finance: [
          { name: "间接融资", value: 98.492 },
          { name: "直接融资", value: 0.945 },
          { name: "票据贴现", value: 0.563 },
        ],
        region: [
          { name: "境内", value: 95.303 },
          { name: "境外", value: 4.697 },
        ],
      },
      institutions: [
        { name: "启明银行", balance: 2012.564, share: 9.312, cost: 2.260199, count: 439 },
        { name: "盛景银行", balance: 1830.405, share: 8.469, cost: 2.304004, count: 430 },
        { name: "嘉禾银行", balance: 1820.424, share: 8.423, cost: 2.277055, count: 439 },
        { name: "海川银行", balance: 1819.037, share: 8.416, cost: 2.295205, count: 413 },
        { name: "融通银行", balance: 1808.807, share: 8.369, cost: 2.24915, count: 423 },
        { name: "安泰银行", balance: 1747.87, share: 8.087, cost: 2.326359, count: 392 },
      ],
      boards: [
        { name: "境内新能源", publishedMetrics: { balance: 16164.098, cost: 2.322729, floating: 95.149492, shortTerm: 0.911805, foreign: 4.224132, highCost: 9.463373, credit: 34.680039 } },
        { name: "核能", publishedMetrics: { balance: 3693.838, cost: 2.175301, floating: 90.349492, shortTerm: 2.261805, foreign: 3.774132, highCost: 8.283949, credit: 32.480039 } },
        { name: "境外新能源", publishedMetrics: { balance: 559.801, cost: 4.518092, floating: 85.549492, shortTerm: 3.611805, foreign: 100, highCost: 27.026277, credit: 30.280039 } },
        { name: "集团及直管公司", publishedMetrics: { balance: 463.441, cost: 2.917414, floating: 80.749492, shortTerm: 4.961805, foreign: 2.874132, highCost: 14.220853, credit: 28.080039 } },
        { name: "核技术", publishedMetrics: { balance: 352.512, cost: 2.21666, floating: 75.949492, shortTerm: 6.311805, foreign: 2.424132, highCost: 8.614821, credit: 25.880039 } },
        { name: "环保产业", publishedMetrics: { balance: 243.61, cost: 2.871994, floating: 71.149492, shortTerm: 7.661805, foreign: 1.974132, highCost: 13.857493, credit: 23.680039 } },
        { name: "产业金融", publishedMetrics: { balance: 102.427, cost: 2.502383, floating: 66.349492, shortTerm: 9.011805, foreign: 1.524132, highCost: 10.900605, credit: 21.480039 } },
        { name: "核燃料", publishedMetrics: { balance: 26.059, cost: 2.375315, floating: 61.549492, shortTerm: 10.361805, foreign: 1.074132, highCost: 9.884061, credit: 19.280039 } },
        { name: "产业服务", publishedMetrics: { balance: 4.873, cost: 1.529819, floating: 56.749492, shortTerm: 11.711805, foreign: 0.624132, highCost: 3.120093, credit: 17.080039 } },
        { name: "数字化", publishedMetrics: { balance: 2.728, cost: 1.44, floating: 51.949492, shortTerm: 13.061805, foreign: 0.174132, highCost: 2.401541, credit: 14.880039 } },
      ],
    },
    "2026.07.31-02": {
      packageId: null,
      packageVersion: null,
      schemaVersion: reportEvidence.schemaVersion,
      factInventoryVersion: null,
      status: "unavailable",
      factPackageStatus: "unavailable",
      sceneId: "S001",
      authorityBindingId: "T019-FIN-PREVIOUS",
      semanticVersionId: "PUB-SEM-FIN-3.8.1",
      semanticVersion: "3.8.1",
      dataAssetVersionId: "T007-FIN-20260731-02",
      dataVersion: "2026.07.31-02",
      consumableVersionId: "T018-FIN-20260731-02",
      asOf: "2026-07-31",
      statusReason: "该历史权威组合未提供可定位的报告结构化事实包。",
      contentFacts: [],
      anchors: [],
      contentItems: [],
      renderManifest: null,
      generatedNarrativeContract: null,
      unavailablePolicy: "返回历史事实包不可用；不得复制 2026.08.09-01 的事实，也不得以当前已发布定义或当前数据冒充。",
      owners: {
        contentFacts: "报告中心",
        contentManifest: "报告中心",
        authoritativeBinding: "本体管理",
        semanticEvidence: "本体管理",
        dataTrust: "数据工程",
      },
    },
  };

  window.RC_DATA = {
    product: {
      dashboardVersion: "1.2.0",
      semanticVersionId: "PUB-SEM-FIN-3.8.1",
      semanticVersion: "3.8.1",
      dataAssetId: "T006-FINANCING-S001",
      dataAssetVersionId: "T007-FIN-20260809-01",
      dataVersion: "2026.08.09-01",
      asOf: "2026-08-09",
      metricResultVersion: "MR-20260809-0918",
      ruleResultVersion: "RR-20260809-0918",
      actionTypeId: "AT-FIN-OPT-001",
      actionType: "融资优化建议",
      actionTypeVersion: "2.1.0",
    },
    publishedSemantic: {
      id: "PUB-SEM-FIN-3.8.1",
      version: "3.8.1",
      status: "Published",
      publishedAt: "2026-08-01 09:00",
      effective: "2026-01-01 起",
      owner: "本体管理",
      resourceTypes: ["Object", "Property", "Link", "Metric", "Rule", "Action Type"],
      discoveryContract: "C004 / C005 / C006 / C007",
    },
    semanticResources,
    metrics,
    rules,
    actionTypes,
    authoritativeConsumption,
    dataTrust,
    reportEvidence,
    groupMetrics,
    units,
    comparisons,
    boards: [
      { name: "境内新能源", balance: 16164.098, cost: 2.322729, share: 74.787, publishedMetrics: { balance: 16164.098, cost: 2.322729, floating: 95.149492, shortTerm: 0.911805, foreign: 4.224132, highCost: 9.463373, credit: 34.680039 } },
      { name: "核能", balance: 3693.838, cost: 2.175301, share: 17.091, publishedMetrics: { balance: 3693.838, cost: 2.175301, floating: 90.349492, shortTerm: 2.261805, foreign: 3.774132, highCost: 8.283949, credit: 32.480039 } },
      { name: "境外新能源", balance: 559.801, cost: 4.518092, share: 2.59, publishedMetrics: { balance: 559.801, cost: 4.518092, floating: 85.549492, shortTerm: 3.611805, foreign: 100, highCost: 27.026277, credit: 30.280039 } },
      { name: "集团及直管公司", balance: 463.441, cost: 2.917414, share: 2.144, publishedMetrics: { balance: 463.441, cost: 2.917414, floating: 80.749492, shortTerm: 4.961805, foreign: 2.874132, highCost: 14.220853, credit: 28.080039 } },
      { name: "核技术", balance: 352.512, cost: 2.21666, share: 1.631, publishedMetrics: { balance: 352.512, cost: 2.21666, floating: 75.949492, shortTerm: 6.311805, foreign: 2.424132, highCost: 8.614821, credit: 25.880039 } },
      { name: "环保产业", balance: 243.61, cost: 2.871994, share: 1.127, publishedMetrics: { balance: 243.61, cost: 2.871994, floating: 71.149492, shortTerm: 7.661805, foreign: 1.974132, highCost: 13.857493, credit: 23.680039 } },
      { name: "产业金融", balance: 102.427, cost: 2.502383, share: 0.474, publishedMetrics: { balance: 102.427, cost: 2.502383, floating: 66.349492, shortTerm: 9.011805, foreign: 1.524132, highCost: 10.900605, credit: 21.480039 } },
      { name: "核燃料", balance: 26.059, cost: 2.375315, share: 0.121, publishedMetrics: { balance: 26.059, cost: 2.375315, floating: 61.549492, shortTerm: 10.361805, foreign: 1.074132, highCost: 9.884061, credit: 19.280039 } },
      { name: "产业服务", balance: 4.873, cost: 1.529819, share: 0.023, publishedMetrics: { balance: 4.873, cost: 1.529819, floating: 56.749492, shortTerm: 11.711805, foreign: 0.624132, highCost: 3.120093, credit: 17.080039 } },
      { name: "数字化", balance: 2.728, cost: 1.44, share: 0.013, publishedMetrics: { balance: 2.728, cost: 1.44, floating: 51.949492, shortTerm: 13.061805, foreign: 0.174132, highCost: 2.401541, credit: 14.880039 } },
    ],
    institutions: [
      { name: "启明银行", balance: 2012.564, share: 9.312, cost: 2.260199, count: 439 },
      { name: "盛景银行", balance: 1830.405, share: 8.469, cost: 2.304004, count: 430 },
      { name: "嘉禾银行", balance: 1820.424, share: 8.423, cost: 2.277055, count: 439 },
      { name: "海川银行", balance: 1819.037, share: 8.416, cost: 2.295205, count: 413 },
      { name: "融通银行", balance: 1808.807, share: 8.369, cost: 2.24915, count: 423 },
      { name: "安泰银行", balance: 1747.87, share: 8.087, cost: 2.326359, count: 392 },
    ],
    structures: {
      rate: [
        { name: "浮动利率", value: 95.149492 },
        { name: "固定利率", value: 4.850508 },
      ],
      term: [
        { name: "长期", value: 95.022 },
        { name: "中期", value: 3.503 },
        { name: "短期", value: 0.912 },
        { name: "未知", value: 0.563 },
      ],
      currency: [
        { name: "人民币", value: 95.775868 },
        { name: "外币", value: 4.224132 },
      ],
      guarantee: [
        { name: "信用", value: 34.680039 },
        { name: "质押", value: 34.337 },
        { name: "其他担保", value: 3.547 },
        { name: "未知", value: 27.436 },
      ],
      finance: [
        { name: "间接融资", value: 98.492 },
        { name: "直接融资", value: 0.945 },
        { name: "票据贴现", value: 0.563 },
      ],
      region: [
        { name: "境内", value: 95.303 },
        { name: "境外", value: 4.697 },
      ],
    },
    trend: [
      { month: "2025-09", balance: 20980.4, cost: 2.46 },
      { month: "2025-10", balance: 21105.8, cost: 2.45 },
      { month: "2025-11", balance: 21221.3, cost: 2.43 },
      { month: "2025-12", balance: 21412.6, cost: 2.44 },
      { month: "2026-01", balance: 21388.1, cost: 2.42 },
      { month: "2026-02", balance: 21502.9, cost: 2.41 },
      { month: "2026-03", balance: 21474.2, cost: 2.4 },
      { month: "2026-04", balance: 21538.5, cost: 2.39 },
      { month: "2026-05", balance: 21602.2, cost: 2.39 },
      { month: "2026-06", balance: 21680.7, cost: 2.38 },
      { month: "2026-07", balance: 21630.5, cost: 2.38 },
      { month: "2026-08", balance: 21613.387, cost: 2.372231 },
    ],
    scenes: [
      {
        id: "S001",
        name: "集团融资成本与债务结构优化",
        type: "管理驾驶舱",
        status: "可使用",
        description: "集团、板块和单位融资成本、债务结构、机构分布与规则证据。",
      },
      {
        id: "S002",
        name: "预算管理",
        type: "管理驾驶舱",
        status: "资料待补充",
        description: "业务目标、预算周期、版本体系、指标与差异分析资料尚未补齐。",
      },
      {
        id: "S003",
        name: "债务风险监测",
        type: "管理驾驶舱",
        stage: "数据工程兼容性验证",
        status: "数据内容已确认·待受控发布验证",
        readiness: "不可消费",
        capabilityStatus: "完整场景未建设",
        entryMode: "稳定入口只读展示",
        description: "当前只验证 I023 真实接入、双成员数据资产与人工业务输入快照；尚无真实受控运行、质量和双成员 T007 证据。",
        unavailableReason: "本体、指标、Rule、Skill、驾驶舱内容和决策链路均未建设，当前兼容性数据永久不得进入 C008/T019。",
        allowed: ["查看数据工程兼容性验证阶段", "查看待受控发布验证状态", "查看完整场景未建设与不可消费原因"],
        prohibited: ["创建 S003 本体或指标 Rule", "形成驾驶舱业务内容", "发起 Action Request", "标记场景就绪或兼容性验证通过"],
      },
      {
        id: "S004",
        name: "财务公司贷款贷前调查报告",
        type: "正式报告",
        status: "资料待补充",
        description: "适用对象、正式报告样例、证据、章节与复核规则尚未补齐。",
      },
    ],
    definitions: [
      {
        id: "RD-FIN-001",
        name: "集团融资经营分析报告",
        scene: "S001",
        purpose: "形成集团融资成本、结构与重点单位问题的固定经营分析报告。",
        audience: "集团财务管理者",
        version: "1.0.0",
        template: "融资经营分析模板 2.2.0",
        evidence: "集团指标、三家重点单位、R01/R02/R03、机构贡献、数据可信度",
        agent: "融资报告生成助手 3.1.0",
        validation: "必需数值、日期和规则结论均须有结构化证据绑定",
        review: "自动核验完整后由报告复核人确认",
        publish: "同源形成 HTML 阅读版与 PDF 固定版后发布",
        status: "已启用",
      },
    ],
    templates: [
      {
        id: "RT-FIN-002",
        name: "融资经营分析模板",
        version: "2.2.0",
        status: "已启用",
        chapters: ["经营概览", "融资成本", "债务结构", "重点单位与机构", "规则发现", "证据与限制"],
        formats: ["HTML", "PDF"],
      },
    ],
  };
})();
