import {FINANCING_MODELS} from '../shared/financing-models.js';
import {loadFinanceContracts} from '../shared/finance-contract-loader.js';
import {parameterControl,parameterValue} from '../shared/model-parameter-view.js';
import {loadFinanceHistory} from '../shared/model-history-loader.js';
import {modelAssetCatalog,defaultIOBindings,INPUT_PORTS,acceptsConsumer} from '../shared/model-contracts.js';
import {workingBindings,pipelineMarkup,inputBindingMarkup,outputBindingMarkup,simulationSummary} from './builder-view.js';
import {FORECAST_METHODS as LEGACY_FORECAST_METHODS,forecastCode,forecastParameterDefaults} from '../shared/forecast-methods.js';
import {createCandidateView} from './candidate-view.js';
import {taskFromModelRun} from '../shared/task-workflow.js';
import {readWork,saveWorkTask,resultIdentityLabel} from '../shared/work-items.js';
import { MODEL_TEMPLATES, MODEL_STORE_KEY, createModelStudio, defaultParameters, defaultCode, runtimeParameterSpecs,modelParameterSpecs } from '../shared/model-studio.js';
import { escapeModelText as esc, modelMoney, modelNumber } from '../shared/model-result-view.js';
const FORECAST_METHODS={...LEGACY_FORECAST_METHODS,...FINANCING_MODELS};
const root = document.getElementById('model-center');
const studio = createModelStudio();
let initialized=false;
const viewScrolls=new Map(),viewDetails=new Map();
const query = new URLSearchParams(location.search);
const tabs = [['overview','模型概览'],['data','输入绑定'],['algorithm','算法构建'],['output','输出约定'],['use','模拟核验'],['versions','版本管理']];
let dataKey, data, selectedId = query.get('goal') || null, tab = 'overview', draft = null, dirty = false, busy = '', error = '', search = '', selectedRunId = query.get('run'), selectedVersionId = query.get('version'), useIds = [], hostIds = [], controller = null, pendingNavigation = null, sourceReference = null, showArchived = false, runOverrides = {}, businessContext = null, simulationSample='first',simulationVersionId='', contractDirty=false;
const dialog = document.createElement('dialog');dialog.className='studio-dialog';document.body.append(dialog);
const candidateView=createCandidateView({studio,getGoal:()=>getGoal(),getHostIds:()=>hostIds,render:()=>render(),setBusy:value=>busy=value,onResult:run=>{selectedRunId=run.id;selectedVersionId=run.versionId;tab='use';persistView();render();},onPromote:candidate=>{void perform('publish',document.createElement('button')).then(()=>{dialog.dataset.candidateId=candidate.id;dialog.querySelector('header h2').textContent='正式发布候选 · '+candidate.name;dialog.querySelector('#publish-form p').textContent='发布此候选的固定快照及审阅记录；当前工作草稿不参与本次发布。';});}});
const getGoal = () => studio.read().goals.find(goal=>goal.id===selectedId);
const glyph = name => `<i data-lucide="${name}"></i>`;
const button = (action,label,primary=false,extra='') => `<button class="studio-button ${primary?'primary':''}" data-studio-action="${action}" ${extra}>${label}</button>`;
const iconButton = (action,label,icon,extra='') => `<button class="studio-icon-button" data-studio-action="${action}" aria-label="${label}" title="${label}" ${extra}>${glyph(icon)}</button>`;
const displayAt=value=>value?new Date(value).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',hour12:false}):'—';
const versionFor = goal => studio.read().versions.find(version=>version.id===studio.read().bindings[goal.id]);
const toast = message => { const region=document.getElementById('model-center-toast');region.textContent=message;region.className='studio-toast';setTimeout(()=>{region.textContent='';region.className='';},3500); };
function announce() { if(parent!==window)parent.postMessage({type:'OFW_MODEL_STUDIO_ROUTE',goalId:selectedId,tab},location.origin); }
function persistView(replace=true){const url=new URL(location.href);for(const key of ['goal','version','run','focusModel','editVersion'])url.searchParams.delete(key);if(selectedId){url.searchParams.set('goal',selectedId);if(selectedVersionId)url.searchParams.set('version',selectedVersionId);if(selectedRunId)url.searchParams.set('run',selectedRunId);}url.hash=selectedId?`goal/${encodeURIComponent(selectedId)}/${tab}`:'objectives';history[replace?'replaceState':'pushState'](null,'',url);announce();}

function route() {
  if(location.hash==='#objectives'){selectedId=null;tab='overview';return;}
  const parts=location.hash.replace(/^#\/?/,'').split('/');
  if(parts[0]==='goal'&&parts[1]){selectedId=decodeURIComponent(parts[1]);tab=tabs.some(([id])=>id===parts[2])?parts[2]:'overview';}
  else if(query.get('focusModel')){selectedId='builtin-risk';tab='overview';}
  else if(query.get('goal')){selectedId=query.get('goal');tab=query.get('run')?'use':query.get('version')?'versions':'overview';}
  else selectedId=null;
}
function navigate(goalId, nextTab='overview') {
  if(busy){toast('请等待本次运行完成，或先停止计算');return;}
  if(goalId===selectedId&&nextTab===tab)return;
  const apply=()=>{const changed=selectedId!==goalId;selectedId=goalId;tab=nextTab;draft=goalId?structuredClone(getGoal().draft):null;dirty=false;error='';if(changed){simulationVersionId='';simulationSample='first';selectedRunId=null;selectedVersionId=goalId?studio.read().bindings[goalId]||null:null;useIds=initialUseIds();}persistView(false);render();};
  if(dirty){pendingNavigation=apply;openDialog('保留当前修改',`<p>输入绑定、算法或输出约定尚未保存。选择保存后切换，或放弃本次修改。</p>`,`${button('cancel-dialog','继续编辑')}${button('discard-navigate','放弃修改')}${button('save-navigate','保存后切换',true)}`);}else apply();
}
function initialUseIds() { runOverrides={};const goal=getGoal();if(!goal)return[];const version=studio.read().versions.find(v=>v.id===(selectedVersionId||studio.read().bindings[goal.id]));return version?hostIds.length?hostIds.filter(id=>version.objectIds.includes(id)):[...version.objectIds]:[]; }
function badge(label, tone='') { return `<span class="studio-badge ${tone}">${esc(label)}</span>`; }
function targetStatus(goal) { if(goal.archived)return '已归档';const version=versionFor(goal);return version?`当前应用 ${version.name}`:studio.read().versions.some(v=>v.goalId===goal.id)?'未启用应用版本':'工作草稿'; }
function nextStep(goal) { const current=goal.id===selectedId&&draft?draft:goal.draft;if(!current.objectIds.length)return ['data','选择适用企业'];if(goal.id===selectedId&&dirty)return ['algorithm','核验当前修改'];if(goal.draft.signature!==goal.draft.validatedSignature||!goal.draft.validatedSignature)return ['algorithm','运行算法核验'];if(!studio.read().versions.some(v=>v.goalId===goal.id&&v.signature===goal.draft.signature))return ['versions','管理候选与发布'];return ['use','使用发布版本']; }
function refreshIcons() { window.lucide?.createIcons({root:document}); }
function render() {
  if(!initialized)return;
  const scrollTop=root.querySelector('.studio-main')?.scrollTop||0,key=(selectedId||'catalog')+':'+tab;if(root.dataset.viewKey){viewScrolls.set(root.dataset.viewKey,scrollTop);viewDetails.set(root.dataset.viewKey,[...root.querySelectorAll('details[data-builder-detail][open]')].map(e=>e.dataset.builderDetail));}const restoreTop=root.dataset.viewKey===key?scrollTop:viewScrolls.get(key)||0;root.dataset.viewKey=key;
  const state=studio.read(),goal=getGoal();
  const filtered=state.goals.filter(goal=>(showArchived||!goal.archived)&&(!search||`${goal.name} ${goal.question} ${goal.owner}`.includes(search)));
  root.className='model-studio';
  root.innerHTML=`<section class="studio-main"><div class="studio-mobile-target"><label>当前目标<select id="mobile-goal"><option value="">模型目标目录</option>${state.goals.map(item=>`<option value="${item.id}" ${item.id===selectedId?'selected':''}>${esc(item.name)}</option>`).join('')}</select></label>${iconButton('new-goal','新建目标','plus')}</div>${error?`<div class="studio-notice error" role="alert">${esc(error)}</div>`:''}${goal?goalMarkup(goal):catalogMarkup(filtered)}</section>`;
  refreshIcons();root.querySelector('.studio-main').scrollTop=restoreTop;for(const id of viewDetails.get(key)||[]){const detail=[...root.querySelectorAll('[data-builder-detail]')].find(e=>e.dataset.builderDetail===id);if(detail)detail.open=true;}
}
function contextMarkup(){
  if(!hostIds.length)return '';
  const names=hostIds.slice(0,2).map(id=>data.enterprises.find(c=>c.id===id)?.name||id);
  return `<p class="studio-context">来源对象：${names.map(esc).join('、')}${hostIds.length>2?`等 ${hostIds.length} 个对象`:''} · 数据截至 ${esc(businessContext?.sourceObservationDate||data.asOf)}。此范围用于试用与比较，模型输入范围单独维护。</p>`;
}
function catalogMarkup(goals) {
  return `<header class="studio-header"><div><span>模型与算法 · v1.5</span><h1>模型目标工作台</h1><p>绑定数据资产，构建算法，约定输出，并通过模拟和契约核验发布。</p></div>${button('new-goal','新建模型目标',true)}</header>${contextMarkup()}<div class="studio-catalog-tools"><label class="studio-search">${glyph('search')}<input id="goal-search" placeholder="搜索业务目标、问题或负责人" value="${esc(search)}"></label><label><input type="checkbox" id="show-archived" ${showArchived?'checked':''}> 显示已归档</label></div><div class="studio-goal-cards">${goals.map(goal=>{const version=versionFor(goal),step=nextStep(goal);return `<article><header>${badge(MODEL_TEMPLATES[goal.type].name)}${badge(version?'可使用':'配置中',version?'success':'')}</header><h2>${esc(goal.name)}</h2><p>${esc(goal.question)}</p><dl><div><dt>负责人</dt><dd>${esc(goal.owner)}</dd></div><div><dt>当前应用</dt><dd>${version?esc(version.name)+(version.origin==='BUILTIN_REFERENCE'?' · 内置参考':''):'尚未发布'}</dd></div><div><dt>适用企业</dt><dd>${version?.objectIds.length||goal.draft.objectIds.length} 家</dd></div></dl><button class="studio-button primary" data-studio-goal="${goal.id}" data-target-tab="overview">进入目标</button><button class="studio-text-button" data-studio-goal="${goal.id}">查看目标与历史</button></article>`;}).join('')}</div><section class="studio-guidance"><h3>一次清楚的闭环</h3><ol><li>创建业务目标</li><li>绑定输入数据资产</li><li>构建算法并约定输出</li><li>模拟、核验与发布</li><li>在业务视图使用固定版本</li></ol><p>内置参考版本可直接体验；新目标按同一流程创建。成本预测使用借款现金流与利率假设，不虚构未来实际成本的回测结果。</p></section>`;
}
function goalMarkup(goal) {
  const step=nextStep(goal),version=versionFor(goal);
  return `<header class="studio-header"><div><button class="studio-text-button" data-studio-action="catalog">模型目标 /</button><h1>${esc(goal.name)}</h1><p>${esc(goal.question)}</p><div class="studio-meta">${badge(MODEL_TEMPLATES[goal.type].name)}<span>负责人 ${esc(goal.owner)}</span>${version?badge(`当前应用 ${version.name}`,'success'):badge('工作草稿')}<span class="studio-dirty" ${dirty?'':'hidden'}>有未保存修改</span></div></div><div class="studio-header-actions">${button('tab','模拟运行',true,`data-tab="use" ${busy?'disabled':''}`)}${button('tab','版本管理',false,'data-tab="versions"')}${iconButton('edit-goal','编辑目标','pencil')}${button('archive-goal',goal.archived?'恢复目标':'归档目标')}</div></header>${contextMarkup()}<nav class="studio-tabs" aria-label="目标工作步骤">${tabs.map(([id,label])=>`<button data-studio-tab="${id}" class="${tab===id?'active':''}">${label}</button>`).join('')}</nav>${busy?`<div class="studio-running" role="status"><span>${esc(busy)}</span>${controller?button('cancel-run','停止本次计算'):''}</div>`:''}${tab==='overview'?pipelineMarkup(studio.read(),goal,draft):''}<div class="studio-content">${tab==='overview'?overviewMarkup(goal):tab==='data'?dataMarkup(goal):tab==='algorithm'?algorithmMarkup(goal):tab==='output'?outputBindingMarkup(studio.read(),goal,draft):tab==='versions'?versionsMarkup(goal):useMarkup(goal)}</div>`;
}
function overviewMarkup(goal) {
  const state=studio.read(),version=versionFor(goal),runs=state.runs.filter(run=>run.goalId===goal.id),template=MODEL_TEMPLATES[goal.type];
  return `${sourceReference&&goal.id==='builtin-risk'?sourceMarkup():''}${methodCards(goal)}<section class="studio-panel"><h2>业务目标与方法</h2><p>${esc(template.method)}</p><dl class="studio-definition"><dt>关注的结果</dt><dd>${esc(template.resultLabel)}</dd><dt>算法输入</dt><dd>${template.inputs.map(esc).join('、')}</dd><dt>数据观察日</dt><dd>${esc(state.datasets[goal.draft.dataKey]?.asOf)}</dd><dt>版本规则</dt><dd>工作草稿可以修改；已发布算法、参数、范围和核验依据固定保存。</dd></dl></section><div class="studio-overview-grid"><section class="studio-panel"><h2>当前应用版本</h2>${version?`<h3>${esc(version.name)} ${version.origin==='BUILTIN_REFERENCE'?badge('内置参考'):''}</h3><p>${esc(version.note)}</p><small>${esc(displayAt(version.publishedAt))}</small><div class="studio-inline-actions">${button('tab','查看版本',false,'data-tab="versions"')}${button('open-consumer','到业务视图使用',true,`data-version="${version.id}"`)}</div>`:'<p>完成数据选择和算法核验后，在发布版本中创建第一个版本。</p>'}</section><section class="studio-panel"><h2>最近运行</h2>${runs.slice(0,4).map(run=>`<button class="studio-run-link" data-show-run="${run.id}"><strong>${run.purpose==='SIMULATION'?'开发模拟':run.purpose==='USE'?'业务运行引用':run.purpose==='TRIAL'?'候选试用':run.purpose==='COMPARE'?'版本比较':'算法核验'} · ${esc(run.versionName||'工作草稿')}</strong><span>${esc(status(run.status))} · ${run.objectIds.length} 家</span><small>${esc(displayAt(run.at))}</small></button>`).join('')||'<p>尚未运行，先维护算法并核验。</p>'}</section></div><section class="studio-panel"><h2>目标活动记录</h2><ol class="studio-audit">${state.audit.filter(entry=>entry.goalId===goal.id).slice(0,10).map(entry=>`<li><strong>${esc(entry.action)}</strong><span>${esc(entry.detail)}</span><small>${esc(displayAt(entry.at))}</small></li>`).join('')}</ol>${!goal.builtin&&!state.versions.some(v=>v.goalId===goal.id)&&!runs.length?button('delete-goal','删除未使用的草稿目标'):''}</section>`;
}
function methodCards(goal,compact=false) {
  if(goal.type!=='cost')return `<section class="studio-method-toolbar"><strong>${esc(MODEL_TEMPLATES[goal.type].method)}</strong><span>在当前目标内维护模型与参数，核验后发布。</span></section>`;
  const chosen=draft?.methodId;
  const controls=Object.entries(FINANCING_MODELS).map(([id,m])=>`<button class="studio-button ${chosen===id?'primary':''}" data-studio-action="choose-method" data-method="${id}" ${busy?'disabled':''}>${esc(m.name)}</button>`).join('');
  const legacy=`<details data-builder-detail="legacy-methods"><summary>历史算法工作副本与兼容维护</summary><p>原版本和运行仍按原代码解释；新建分析优先使用上方三个模型。</p><div class="studio-inline-actions">${Object.entries(LEGACY_FORECAST_METHODS).map(([id,m])=>`<button class="studio-button" data-studio-action="choose-method" data-method="${id}" ${busy?'disabled':''}>${esc(m.name)} · 历史方法</button>`).join('')}</div></details>`;
  if(compact)return `<section class="studio-panel"><div class="studio-method-picker"><span>维护模型</span><div>${controls}</div></div>${legacy}</section>`;
  return `<section class="studio-panel studio-method-library"><header><div><h2>选择融资业务模型</h2><p>区分合同利率传导、主动置换方案和仅历史序列延续。</p></div>${badge(FORECAST_METHODS[chosen]?.name||'历史基础试算')}</header><div class="studio-method-cards">${Object.entries(FINANCING_MODELS).map(([id,m])=>`<article class="${chosen===id?'selected':''}"><header>${glyph(id==='stock-rate'?'calendar-range':id==='refinance-ai'?'sparkles':'chart-spline')}<h3>${esc(m.name)}</h3></header><p>${esc(m.description)}</p><small>${esc(m.boundary)}</small><button class="studio-button ${chosen===id?'primary':''}" data-studio-action="choose-method" data-method="${id}" ${busy?'disabled':''}>${chosen===id?'维护当前模型':'选择并维护'}</button></article>`).join('')}</div>${legacy}</section>`;
}
function scopePicker(ids, prefix, allowedIds=data.enterprises.map(c=>c.id)) {
  const snapshot=studio.read().datasets[prefix==='draft'?draft.dataKey:studio.read().versions.find(version=>version.id===selectedVersionId)?.dataKey]||data;
  const companies=snapshot.enterprises.filter(company=>allowedIds.includes(company.id));
  return `<div class="studio-scope-head"><strong><span data-scope-count="${prefix}">${ids.length}</span> / ${companies.length} 家企业</strong><div><button class="studio-text-button" data-scope-select="${prefix}" data-value="all">全选</button><button class="studio-text-button" data-scope-select="${prefix}" data-value="none">清空</button></div></div><div class="studio-scope-list">${companies.map(company=>`<label><input type="checkbox" data-scope="${prefix}" value="${company.id}" ${ids.includes(company.id)?'checked':''} ${busy?'disabled':''}><span><strong>${esc(company.name)}</strong><small>${esc(company.city)} · ${esc(company.industry)}</small></span></label>`).join('')}</div>`;
}
function dataMarkup(goal){return inputBindingMarkup(studio.read(),goal,draft,scopePicker(draft.objectIds,'draft'));}
function algorithmMarkup(goal) {
  const template=MODEL_TEMPLATES[goal.type],run=studio.read().runs.find(run=>run.id===goal.draft.validationRunId);
  return `${methodCards(goal,true)}<div class="studio-algorithm-grid"><section class="studio-panel"><header><div><h2>算法工作草稿</h2><p>${esc(FORECAST_METHODS[draft.methodId]?.description||template.method)} · 修订 ${draft.revision}</p></div>${badge('JavaScript')}</header><p>编辑的是工作草稿，已发布版本保持不变。${draft.sourceVersionId?'工作副本来自版本 '+esc(studio.read().versions.find(v=>v.id===draft.sourceVersionId)?.name||draft.sourceVersionId):''}</p><label class="studio-code-label" for="algorithm-code">运行脚本（input、parameters → 目标结果）</label><textarea id="algorithm-code" class="studio-code" spellcheck="false" ${busy?'disabled':''}>${esc(draft.code)}</textarea><div class="studio-inline-actions">${button('reset-code','恢复参考算法')}${button('copy-version','从当前发布版复制')}</div></section><section class="studio-panel"><h2>业务参数</h2><div class="studio-parameter-fields">${modelParameterSpecs(goal.type,draft.methodId).map(spec=>`<label><span>${esc(spec.label)} <small>${esc(spec.unit)}</small></span>${parameterControl(spec,draft.parameters[spec.key],'data-parameter',{state:studio.read(),disabled:!!busy})}<small>${esc(spec.help)}</small></label>`).join('')}</div></section></div><section class="studio-panel"><header><div><h2>保存与核验</h2><p>核验检查对象、单位、历史基准及输出约束；不伪造未来实际结果或回测精度。</p></div><div class="studio-inline-actions">${button('save-draft','保存草稿',false,busy?'disabled':'')}${button('validate','保存并运行核验',true,busy?'disabled':'')}</div></header>${run&&goal.draft.validatedSignature===goal.draft.signature&&!dirty?`<p class="studio-badge success">当前工作副本已通过完整核验</p>${button('tab','下一步：候选与发布',true,'data-tab="versions"')}`:'<p class="studio-notice">当前草稿需要核验。修改代码、参数或范围后，旧核验结果不会被套用。</p>'}${selectedRunId?simulationSummary(studio.read().runs.find(run=>run.id===selectedRunId)):run?simulationSummary(run):''}</section>`;
}
function versionsMarkup(goal) {
  const state=studio.read(),versions=state.versions.filter(version=>version.goalId===goal.id).reverse(),current=state.bindings[goal.id],eligible=Boolean(goal.draft.ioBindings)&&goal.draft.validatedSignature&&goal.draft.validatedSignature===goal.draft.signature&&!dirty;
  const selected=versions.find(version=>version.id===selectedVersionId)||versions[0];
  return `<div class="studio-version-status"><article><span>当前应用</span><strong>${esc(versions.find(v=>v.id===current)?.name||'尚未选择')}</strong></article><article><span>候选试用</span><strong>${esc(state.candidates.find(v=>v.id===state.candidateBindings[goal.id])?.name||'未启用')}</strong></article><article><span>工作草稿</span><strong>${eligible?'已核验':'待核验'}</strong></article></div><section class="studio-panel"><header><div><h2>发布与当前应用</h2><p>发布固定算法、参数、数据范围与核验依据。发布后再独立选择是否切换当前应用。</p></div>${button('publish','发布新版本',true,eligible&&!busy&&!goal.archived?'':'disabled')}</header>${eligible?badge('当前草稿核验通过','success'):`<p class="studio-notice">先保存输入与输出绑定，再完成当前草稿的全部契约核验。</p>`}</section>${candidateView.markup(goal)}<section class="studio-panel"><h2>已发布版本</h2><p>时间按北京时间显示；导出记录保留标准时间戳。</p><div class="studio-table-scroll"><table><thead><tr><th>版本</th><th>模型 / 用途</th><th>范围</th><th>发布时间</th><th>当前应用</th><th>操作</th></tr></thead><tbody>${versions.map(version=>`<tr class="${selected?.id===version.id?'selected':''}"><td><button class="studio-text-button" data-inspect-version="${version.id}">${esc(version.name)}</button></td><td>${esc(FORECAST_METHODS[version.methodId]?.name||MODEL_TEMPLATES[goal.type].resultLabel)}<small>${version.origin==='BUILTIN_REFERENCE'?'内置参考':'用户发布'}</small></td><td>${version.objectIds.length} 家</td><td>${esc(displayAt(version.publishedAt))}</td><td>${current===version.id?badge('当前','success'):state.availability[version.id]?badge('可使用'):badge('已停用')}</td><td><div class="studio-inline-actions">${current!==version.id&&state.availability[version.id]?button('bind','设为当前',false,`data-version="${version.id}"`):''}${button('maintain-version','维护工作副本',false,`data-version="${version.id}"`)}${button('availability',state.availability[version.id]?'停用':'启用',false,`data-version="${version.id}" data-enabled="${!state.availability[version.id]}"`)}</div></td></tr>`).join('')||'<tr><td colspan="6">完成核验后发布第一个版本。</td></tr>'}</tbody></table></div></section>${selected?`<section class="studio-panel"><header><div><h2>版本 ${esc(selected.name)} · 固定快照</h2><p>${esc(selected.note)}</p></div><div class="studio-inline-actions">${button('open-consumer','到业务视图使用',true,`data-version="${selected.id}" ${state.availability[selected.id]?'':'disabled'}`)}${button('export-version','导出版本包',false,`data-version="${selected.id}"`)}</div></header><dl class="studio-definition"><dt>发布人</dt><dd>${esc(selected.publisher)}</dd><dt>算法与参数指纹</dt><dd class="studio-code-ref">${esc(selected.signature)}</dd><dt>核验记录</dt><dd><button class="studio-text-button" data-show-run="${selected.validationRunId}">${esc(selected.validationRunId)}</button></dd><dt>数据版本</dt><dd>${esc(state.datasets[selected.dataKey]?.dataVersion)} · ${esc(state.datasets[selected.dataKey]?.asOf)}</dd></dl><details><summary>查看固定参数与代码</summary><pre>${esc(JSON.stringify(selected.parameters,null,2))}</pre><pre class="studio-frozen-code">${esc(selected.code)}</pre></details></section>`:''}`;
}
function useMarkup(goal) {
  const state=studio.read(),versions=state.versions.filter(v=>v.goalId===goal.id),config=simulationVersionId?versions.find(v=>v.id===simulationVersionId)||draft:draft,ids=config.objectIds||[],source=state.datasets[config.dataKey],selected=state.runs.find(r=>r.id===selectedRunId),runs=state.runs.filter(r=>r.goalId===goal.id&&['SIMULATION','VALIDATION'].includes(r.purpose));
  return `<section class="studio-panel"><header><div><h2>模拟与契约核验</h2><p>用少量输入样本调试算法。发布前再对全部声明范围验证输入、输出和业务约束。</p></div><span class="studio-badge">构建环境</span></header><div class="builder-simulation-config"><label class="studio-field"><span>运行对象</span><select id="simulation-version"><option value="">当前工作草稿</option>${versions.map(v=>`<option value="${v.id}" ${simulationVersionId===v.id?'selected':''}>固定版本 ${esc(v.name)}</option>`).join('')}</select></label><label class="studio-field"><span>输入样本</span><select id="simulation-sample"><option value="first">前 ${Math.min(3,ids.length)} 条符合范围的记录</option>${ids.map(id=>`<option value="${id}" ${simulationSample===id?'selected':''}>${esc(source.enterprises.find(c=>c.id===id)?.name||id)} · ${id}</option>`).join('')}</select></label></div><div class="studio-inline-actions">${button('run-use','模拟运行',true,busy||!ids.length||goal.archived?'disabled':'')}${button('validate','验证全部输入与输出契约',false,busy||!draft.objectIds.length||goal.archived?'disabled':'')}${button('tab','编辑输入绑定',false,'data-tab="data"')}${button('tab','编辑输出约定',false,'data-tab="output"')}</div><p>模拟不会产生业务预警，不会替换当前应用，也不等于发布核验。</p></section><section class="studio-panel">${simulationSummary(selected)}${selected?.status==='SUCCEEDED'?`<div class="studio-inline-actions">${button('export-run','导出调试记录',false,`data-run="${selected.id}"`)}${button('open-consumer',['USE','TRIAL'].includes(selected.purpose)?'查看原业务运行':'到业务视图使用发布版本',false,`data-run="${selected.id}"`)}</div>`:''}</section><section class="studio-panel"><h2>构建与模拟记录</h2><div class="studio-table-scroll"><table><thead><tr><th>时间</th><th>用途</th><th>来源版本</th><th>状态</th><th></th></tr></thead><tbody>${runs.slice(0,20).map(run=>`<tr><td>${esc(displayAt(run.at))}</td><td>${run.purpose==='SIMULATION'?'开发模拟':'契约核验'}</td><td>${esc(run.versionName||'工作草稿')}</td><td>${esc(status(run.status))}</td><td><button class="studio-text-button" data-show-run="${run.id}">检查记录</button></td></tr>`).join('')||'<tr><td colspan="5">尚无模拟或核验记录。</td></tr>'}</tbody></table></div><details><summary>下游业务运行引用</summary><p>这里只保留版本与运行入口，企业结果在业务视图查看。</p>${state.runs.filter(r=>r.goalId===goal.id&&['USE','TRIAL'].includes(r.purpose)).slice(0,10).map(r=>`<button class="studio-run-link" data-show-run="${r.id}">${esc(r.versionName)} · ${esc(r.id)} · ${esc(status(r.status))}</button>`).join('')||'暂无下游运行'}</details></section>`;
}
function status(value) { return ({RUNNING:'运行中',SUCCEEDED:'成功',FAILED:'失败',CANCELLED:'已停止'})[value]||value; }
function sourceMarkup() { const baseline=sourceReference.formalBaseline;return `<section class="studio-panel studio-source-reference"><h2>事件引用的历史评分基线</h2><p>${esc(baseline.name)} · ${esc(baseline.modelVersion)}</p><dl class="studio-definition"><dt>模型身份</dt><dd>${esc(baseline.modelId)}</dd><dt>引用版本</dt><dd>${esc(baseline.modelVersionId)}</dd><dt>数据版本</dt><dd>${esc(baseline.dataVersionId)}</dd><dt>评估观察日</dt><dd>${esc(baseline.resultEnvelope?.asOf)}</dd></dl><p>该历史评分版本只读。当前监控目标可以引用历史评分作为输入，其新提示不改写原评分。</p><details><summary>查看发布包与结果证据</summary><ul>${baseline.resultEnvelope?.evidenceRefs.map(ref=>`<li>${esc(ref)}</li>`).join('')}</ul></details></section>`; }
function openDialog(title,body,footer) { dialog.innerHTML=`<header><h2>${esc(title)}</h2>${iconButton('cancel-dialog','关闭','x')}</header><div class="studio-dialog-body">${body}</div><footer>${footer}</footer>`;if(!dialog.open)dialog.showModal();refreshIcons();dialog.querySelector('input,select,button')?.focus(); }
function openGoalForm(edit=false) { const goal=edit?getGoal():null;openDialog(edit?'编辑目标':'创建模型目标',`<form id="goal-form"><label class="studio-field"><span>目标类型</span><select name="type" ${edit?'disabled':''}>${Object.entries(MODEL_TEMPLATES).map(([type,template])=>`<option value="${type}" ${goal?.type===type?'selected':''}>${template.name}</option>`).join('')}</select></label><label class="studio-field"><span>目标名称</span><input name="name" maxlength="70" required value="${esc(goal?.name||'')}" placeholder="例如：2026年度融资成本预测"></label><label class="studio-field"><span>业务问题</span><textarea name="question" rows="3" required>${esc(goal?.question||MODEL_TEMPLATES.cost.question)}</textarea></label><label class="studio-field"><span>负责人</span><input name="owner" required value="${esc(goal?.owner||'')}" placeholder="模型负责人或团队"></label><p class="studio-dialog-error" role="alert"></p></form>`,`${button('cancel-dialog','取消')}${button(edit?'save-goal':'create-goal',edit?'保存目标':'创建并配置数据',true)}`); }
async function saveCurrentDraft() { const goal=getGoal();if(!dirty&&draft.ioBindings&&goal.draft.signature)return goal;draft.ioBindings=workingBindings(studio.read(),goal,draft);const saved=await studio.saveDraft(goal.id,{...draft},draft.revision);draft=structuredClone(saved.draft);dirty=false;return saved; }
function markDirty() { dirty=true;document.querySelector('.studio-dirty')?.removeAttribute('hidden');document.querySelector('[data-studio-action="publish"]')?.setAttribute('disabled',''); }
function download(name,value) { const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000); }
async function perform(action,target) {
  if(busy&&!['cancel-run','cancel-dialog'].includes(action))return;
  if(!['cancel-run','cancel-dialog'].includes(action))error='';
  if(action==='send-decision') {
    const run=studio.read().runs.find(r=>r.id===target.dataset.run);
    openDialog('送入决策中心研判',`<form id="model-task-form"><p>${esc(run.goalDefinition?.name)} · ${esc(resultIdentityLabel(run.resultIdentity))} · ${run.objectIds.length} 家企业。提交后为待研判事项，固定本次运行及依据。</p><label class="studio-field"><span>事项名称</span><input name="title" required value="${esc(run.goalDefinition?.name)} · 结果研判"></label><label class="studio-field"><span>研判负责人</span><input name="owner" required placeholder="负责人或团队"></label><label class="studio-field"><span>目标期限</span><input name="dueDate" type="date" required min="${new Date().toISOString().slice(0,10)}" value="${new Date(Date.now()+7*86400000).toISOString().slice(0,10)}"></label><p class="studio-dialog-error" role="alert"></p></form>`,`${button('cancel-dialog','取消')}${button('confirm-send-decision','形成待研判事项',true,`data-run="${run.id}"`)}`);return;
  }
  if(action==='confirm-send-decision') {
    const form=dialog.querySelector('form');if(!form.reportValidity())return;
    try {const run=studio.read().runs.find(r=>r.id===target.dataset.run),task=taskFromModelRun(run,studio.read().datasets[run.dataKey],Object.fromEntries(new FormData(form)),readWork().tasks);saveWorkTask(task);dialog.close();parent.postMessage({type:'OFW_CASE_OPEN',taskId:task.id},location.origin);}catch(e){dialog.querySelector('.studio-dialog-error').textContent=e.message;}return;
  }
  if(action==='open-input-asset'){parent.postMessage({type:'OFW_FINANCE_ASSET_OPEN',assetId:target.dataset.id},location.origin);return;}
  if(action==='save-input-bindings'||action==='save-output-bindings'){await saveCurrentDraft();render();toast('输入与输出绑定已保存，需重新核验后发布');return;}
  if(action==='reset-output-bindings'){draft.ioBindings=workingBindings(studio.read(),getGoal(),draft);draft.ioBindings.output=defaultIOBindings(studio.read(),getGoal(),draft).output;markDirty();render();return;}
  if(action==='choose-method'){if(dirty)await saveCurrentDraft();const selected=await studio.selectMethod(selectedId,target.dataset.method,getGoal().draft.revision);draft=structuredClone(selected.draft);dirty=false;tab='algorithm';selectedRunId=null;persistView();render();return;}
  if(action==='cancel-dialog'){dialog.close();return;}
  if(action==='cancel-run'){controller?.abort();return;}
  if(busy)return;
  if(action==='archive-goal'){await studio.archiveGoal(selectedId,!getGoal().archived);showArchived=Boolean(getGoal().archived);render();return;}
  if(action==='catalog'){navigate(null);return;}
  if(action==='new-goal'||action==='edit-goal'){if(dirty){toast('请先保存当前修改，再创建或编辑目标信息');return;}openGoalForm(action==='edit-goal');return;}
  if(action==='create-goal'||action==='save-goal'){
    const form=dialog.querySelector('form');if(!form.reportValidity())return;const fields=Object.fromEntries(new FormData(form));
    try{if(action==='create-goal'){let goal=await studio.createGoal(fields,dataKey);goal=await studio.saveDraft(goal.id,{objectIds:data.enterprises.map(c=>c.id)},goal.draft.revision);dialog.close();navigate(goal.id,'data');}else{const saved=await studio.updateGoal(selectedId,fields);draft=structuredClone(saved.draft);dialog.close();render();}}catch(error){dialog.querySelector('.studio-dialog-error').textContent=error.message;}return;
  }
  if(action==='discard-navigate'){dirty=false;dialog.close();pendingNavigation?.();pendingNavigation=null;return;}
  if(action==='save-navigate'){await saveCurrentDraft();dialog.close();pendingNavigation?.();pendingNavigation=null;return;}
  if(action==='next'||action==='tab'){const next=target.dataset.nextTab||target.dataset.tab;if(action==='next'&&next===tab){if(tab==='algorithm')return perform('validate',target);if(tab==='versions')return perform('publish',target);if(tab==='use')return perform('run-use',target);document.querySelector('[data-scope="draft"]')?.focus();return;}navigate(selectedId,next);return;}
  if(action==='save-to-model'){await saveCurrentDraft();navigate(selectedId,'algorithm');return;}
  if(action==='save-draft'){await saveCurrentDraft();render();toast('工作草稿已保存；原发布版本保持固定');return;}
  if(action==='reset-code'){draft.methodId=null;draft.code=defaultCode(getGoal().type);draft.parameters=defaultParameters(getGoal().type);markDirty();render();return;}
  if(action==='copy-version'||action==='maintain-version'){const version=studio.read().versions.find(v=>v.id===(target.dataset.version||selectedVersionId)&&v.goalId===selectedId)||versionFor(getGoal());if(!version)throw Error('当前没有发布版本');Object.assign(draft,{sourceVersionId:version.id,ioBindings:version.ioBindings?structuredClone(version.ioBindings):undefined,methodId:version.methodId||null,code:version.code,parameters:structuredClone(version.parameters),dataKey:version.dataKey,objectIds:[...version.objectIds]});tab='algorithm';markDirty();persistView();render();return;}
  if(action==='validate'||action==='run-use'){
    if(action==='validate'||action==='run-use'&&!simulationVersionId){await saveCurrentDraft();selectedRunId=null;}
    controller=new AbortController();busy=action==='validate'?'正在执行当前算法并核验业务约束…':'正在执行开发模拟…';error='';render();
    try{const run=await studio.run(selectedId,action==='validate'?{signal:controller.signal}:{purpose:'SIMULATION',versionId:simulationVersionId||undefined,objectIds:simulationSample==='first'?(simulationVersionId?studio.read().versions.find(v=>v.id===simulationVersionId).objectIds:draft.objectIds).slice(0,3):[simulationSample],signal:controller.signal});selectedRunId=run.id;persistView();draft=structuredClone(getGoal().draft);dirty=false;toast(action==='validate'?'当前草稿核验通过':'开发模拟已完成，可检查输出结构与调试样例');}catch(caught){error=caught.message;}finally{busy='';controller=null;render();}return;
  }
  if(action==='publish'){
    delete dialog.dataset.candidateId;
    if(dirty)throw Error('当前修改尚未核验，请先保存并运行核验');
    const count=studio.read().versions.filter(version=>version.goalId===selectedId).length;
    openDialog('发布模型版本',`<form id="publish-form"><p>将固定当前算法、参数、企业范围和核验记录。发布后可在企业探索中选择使用。</p><label class="studio-field"><span>版本号</span><input name="name" value="${count?`1.${count}.0`:'1.0.0'}" required pattern="[0-9]+\\.[0-9]+\\.[0-9]+"></label><label class="studio-field"><span>发布说明</span><textarea name="note" rows="3" required placeholder="说明本版本的业务假设和变更"></textarea></label><label class="studio-field"><span>发布人</span><input name="publisher" value="当前原型用户" required></label><label class="studio-check-label"><input type="checkbox" name="activate"> 发布后同时设为当前应用（明确切换）</label><p class="studio-dialog-error" role="alert"></p></form>`,`${button('cancel-dialog','取消')}${button('confirm-publish','发布版本',true)}`);return;
  }
  if(action==='confirm-publish'){const form=dialog.querySelector('form');if(!form.reportValidity())return;try{const fields=Object.fromEntries(new FormData(form));fields.activate=fields.activate==='on';const version=dialog.dataset.candidateId?await studio.promoteCandidate(dialog.dataset.candidateId,fields):await studio.publish(selectedId,fields);selectedVersionId=version.id;persistView();dialog.close();render();toast(`版本 ${version.name} 已发布${fields.activate?'并设为当前应用':'；当前应用未切换'}`);}catch(caught){dialog.querySelector('.studio-dialog-error').textContent=caught.message;}return;}
  if(action==='bind'){await studio.bind(selectedId,target.dataset.version);selectedVersionId=target.dataset.version;render();toast('已切换当前应用版本，历史版本和结果保留');return;}
  if(action==='availability'){await studio.setAvailability(target.dataset.version,target.dataset.enabled==='true');render();return;}
  if(action==='delete-goal'){await studio.removeGoal(selectedId);navigate(null);return;}
  if(action==='export-version'){const version=studio.read().versions.find(version=>version.id===target.dataset.version);download(`${getGoal().name}-${version.name}.json`,{schemaVersion:'ofw.model-package.v1',goal:{id:selectedId,...version.goalDefinition},version,datasetIdentity:{dataVersion:studio.read().datasets[version.dataKey]?.dataVersion,asOf:studio.read().datasets[version.dataKey]?.asOf,ontologyVersion:studio.read().datasets[version.dataKey]?.ontologyVersion}});return;}
  if(action==='export-run'){const run=studio.read().runs.find(run=>run.id===target.dataset.run);download(`${getGoal().name}-${run.id}.json`,run);return;}
  if(action==='open-consumer'){
    const state=studio.read(),run=state.runs.find(r=>r.id===target.dataset.run);
    if(['USE','TRIAL'].includes(run?.purpose)){parent.postMessage(run.methodId?{type:'OFW_OPEN_TEMPORAL',runId:run.id,objectIds:run.objectIds}:{type:'OFW_STUDIO_EXPLORE',goalId:selectedId,runId:run.id,versionId:run.versionId,objectIds:run.objectIds,selectedId:run.objectIds[0]},location.origin);return;}
    const requested=target.dataset.version||run?.versionId||selectedVersionId;
    const version=state.versions.find(v=>v.id===requested&&state.availability[v.id])||state.versions.filter(v=>v.goalId===selectedId&&state.availability[v.id]&&(v.methodId||null)===(draft.methodId||null)).at(-1);
    if(!version)throw Error('请先发布一个可用版本，再到业务视图使用');
    const temporal=Boolean(version.methodId)&&acceptsConsumer(version,'temporal');
    if(!temporal&&!acceptsConsumer(version,'objects'))throw Error('该版本仅输出数据集，尚未绑定业务视图；请维护输出约定后重新发布');
    parent.postMessage(temporal?{type:'OFW_OPEN_TEMPORAL',objectIds:version.objectIds,versionId:version.id}:{type:'OFW_STUDIO_EXPLORE',goalId:selectedId,versionId:version.id,objectIds:version.objectIds,selectedId:version.objectIds[0]},location.origin);return;
  }
  if(action==='open-temporal'){const run=studio.read().runs.find(r=>r.id===target.dataset.run);parent.postMessage({type:'OFW_OPEN_TEMPORAL',runId:run.id,objectIds:run.objectIds},location.origin);return;}
  if(action==='open-exploration'){const run=studio.read().runs.find(run=>run.id===target.dataset.run);parent.postMessage({type:'OFW_STUDIO_EXPLORE',goalId:selectedId,runId:run.id,objectIds:run.objectIds,selectedId:run.objectIds[0]},location.origin);return;}
}
document.addEventListener('submit',event=>{if(event.target.matches('#candidate-form,#candidate-review-form')){event.preventDefault();void candidateView.submit(event.target);}});
document.addEventListener('click',event=>{
  const candidate=event.target.closest('[data-candidate-action]');if(candidate){void candidateView.action(candidate.dataset.candidateAction);return;}
  const goal=event.target.closest('[data-studio-goal]');if(goal){navigate(goal.dataset.studioGoal,goal.dataset.targetTab||'overview');return;}
  const nextTab=event.target.closest('[data-studio-tab]');if(nextTab){navigate(selectedId,nextTab.dataset.studioTab);return;}
  const run=event.target.closest('[data-show-run]');if(run){if(busy)return;if(dirty){error='请先保存或放弃当前修改，再查看运行记录';render();return;}selectedRunId=run.dataset.showRun;const record=studio.read().runs.find(item=>item.id===selectedRunId);selectedVersionId=record?.versionId||selectedVersionId;tab='use';persistView();render();return;}
  const version=event.target.closest('[data-inspect-version]');if(version){if(busy)return;selectedVersionId=version.dataset.inspectVersion;persistView();render();return;}
  const scope=event.target.closest('[data-scope-select]');if(scope){if(busy)return;const values=scope.dataset.value==='all'?[...document.querySelectorAll(`[data-scope="${scope.dataset.scopeSelect}"]`)].map(input=>input.value):[];if(scope.dataset.scopeSelect==='draft'){draft.objectIds=values;markDirty();}else useIds=values;render();return;}
  const target=event.target.closest('[data-studio-action]');if(target)void perform(target.dataset.studioAction,target).catch(caught=>{error=caught.message;render();});
});
document.addEventListener('input',event=>{
  const target=event.target;
  if(target.id==='goal-search'){const start=target.selectionStart;search=target.value;render();const field=document.getElementById('goal-search');field.focus();try{field.setSelectionRange(start,start);}catch(_){}return;}
  if(target.id==='output-name'||target.id==='output-id'||target.dataset.outputField){draft.ioBindings=workingBindings(studio.read(),getGoal(),draft);if(target.id==='output-name')draft.ioBindings.output.name=target.value;else if(target.id==='output-id')draft.ioBindings.output.datasetId=target.value;else draft.ioBindings.output.fields[Number(target.dataset.outputField)].name=target.value;markDirty();return;}
  if(target.id==='algorithm-code'){draft.code=target.value;markDirty();}
  if(target.matches('[data-run-parameter]')){runOverrides[target.dataset.runParameter]=target.valueAsNumber;}
  if(target.matches('[data-parameter]')){draft.parameters[target.dataset.parameter]=parameterValue(target);markDirty();}
});
document.addEventListener('change',event=>{
  const target=event.target;
  if(candidateView.change(target))return;
  if(target.id==='simulation-version'){simulationVersionId=target.value;simulationSample='first';render();return;}
  if(target.id==='simulation-sample'){simulationSample=target.value;return;}
  if(target.dataset.inputAsset){draft.ioBindings=workingBindings(studio.read(),getGoal(),draft);const port=target.dataset.inputAsset,asset=modelAssetCatalog(studio.read()).find(a=>a.ref===target.value);if(asset)draft.ioBindings.inputs[port]={assetRef:asset.ref,assetVersion:asset.version,assetDigest:asset.digest,fields:Object.fromEntries(INPUT_PORTS[port].fields.map(f=>[f.key,f.key]))};else delete draft.ioBindings.inputs[port];markDirty();render();return;}
  if(target.dataset.inputField){draft.ioBindings=workingBindings(studio.read(),getGoal(),draft);draft.ioBindings.inputs[target.dataset.inputField].fields[target.dataset.targetField]=target.value;markDirty();return;}
  if(target.dataset.outputDestination){draft.ioBindings=workingBindings(studio.read(),getGoal(),draft);draft.ioBindings.output.destinations=[...document.querySelectorAll('[data-output-destination]:checked')].map(e=>e.dataset.outputDestination);markDirty();return;}
  if(target.id==='draft-dataset'){draft.dataKey=target.value;const valid=new Set(studio.read().datasets[target.value].enterprises.map(company=>company.id));draft.objectIds=draft.objectIds.filter(id=>valid.has(id));markDirty();render();return;}
  if(target.id==='show-archived'){showArchived=target.checked;render();return;}
  if(target.id==='mobile-goal'){navigate(target.value||null);return;}
  if(target.name==='type'&&target.closest('#goal-form')){dialog.querySelector('[name="question"]').value=MODEL_TEMPLATES[target.value].question;return;}
  if(target.matches('[data-scope]')){const values=[...document.querySelectorAll(`[data-scope="${target.dataset.scope}"]:checked`)].map(input=>input.value);if(target.dataset.scope==='draft'){draft.objectIds=values;markDirty();}else useIds=values;document.querySelector(`[data-scope-count="${target.dataset.scope}"]`).textContent=values.length;const run=document.querySelector('[data-studio-action="run-use"]');if(run)run.disabled=!values.length||Boolean(getGoal()?.archived)||!studio.read().availability[selectedVersionId]||Boolean(busy);return;}
  if(target.id==='use-version'){selectedVersionId=target.value;useIds=initialUseIds();render();}
});
function applyHostRoute(rawUrl){
  const url=new URL(rawUrl,location.href);if(url.origin!==location.origin||url.pathname!==location.pathname)return;
  const parts=url.hash.replace(/^#\/?/,'').split('/'),goalId=parts[0]==='goal'?decodeURIComponent(parts[1]):url.searchParams.get('goal')||(url.searchParams.get('focusModel')?'builtin-risk':null),nextTab=parts[0]==='goal'&&tabs.some(([id])=>id===parts[2])?parts[2]:url.searchParams.get('run')?'use':url.searchParams.get('version')?'versions':'overview';
  if(goalId&&!studio.read().goals.some(g=>g.id===goalId)){error='目标不存在';render();return;}
  if(busy){toast('请先停止当前模拟再切换目标');announce();return;}
  const requestedRun=url.searchParams.get('run'),requestedVersion=url.searchParams.get('version'),edit=url.searchParams.get('editVersion');
  if(selectedId===goalId&&tab===nextTab&&!edit&&(!requestedRun||requestedRun===selectedRunId)&&(!requestedVersion||requestedVersion===selectedVersionId)){announce();return;}
  const apply=async()=>{const changed=goalId!==selectedId;selectedId=goalId;tab=nextTab;selectedRunId=requestedRun;selectedVersionId=requestedVersion||(goalId?studio.read().bindings[goalId]:null);draft=goalId?structuredClone(getGoal().draft):null;dirty=false;error='';if(changed){simulationVersionId='';simulationSample='first';}if(edit&&draft){const source=studio.read().versions.find(v=>v.id===edit&&v.goalId===goalId);if(source){Object.assign(draft,{sourceVersionId:source.id,methodId:source.methodId||null,code:source.code,parameters:structuredClone(source.parameters),dataKey:source.dataKey,objectIds:[...source.objectIds],ioBindings:source.ioBindings?structuredClone(source.ioBindings):undefined});tab='algorithm';dirty=true;}}if(url.searchParams.get('focusModel')){const response=await fetch('/model-api/v1/model-management/context?scenarioId=S003');if(response.ok)sourceReference=(await response.json()).state;}useIds=initialUseIds();persistView();render();};
  if(dirty){pendingNavigation=apply;openDialog('保留当前工作副本','<p>输入绑定、算法或输出约定尚未保存。</p>',`${button('cancel-dialog','继续编辑')}${button('discard-navigate','放弃修改')}${button('save-navigate','保存后切换',true)}`);}else void apply();
}
window.addEventListener('message',event=>{if(event.source===parent&&event.origin===location.origin&&event.data?.type==='OFW_MODEL_STUDIO_NAVIGATE')applyHostRoute(event.data.url);});
window.addEventListener('popstate',()=>{if(busy){controller?.abort();}selectedRunId=new URLSearchParams(location.search).get('run');selectedVersionId=new URLSearchParams(location.search).get('version');route();draft=getGoal()?structuredClone(getGoal().draft):null;dirty=false;useIds=initialUseIds();render();});
window.addEventListener('storage',event=>{if(event.key===MODEL_STORE_KEY&&!dirty&&!busy){draft=getGoal()?structuredClone(getGoal().draft):null;render();}});
window.addEventListener('message',event=>{if(event.source!==parent||event.origin!==location.origin)return;if(event.data?.type==='OFW_WORKSPACE_CONTEXT'){const context=event.data.context||{};if(JSON.stringify(context)===JSON.stringify(businessContext))return;businessContext=context;hostIds=[...new Set(context.activeObjectRef?.id?[context.activeObjectRef.id]:context.objectSetRef?.objectIds||[])].map(id=>id.replace(/^S003-/,''));if(!dirty&&!busy){if(tab==='use')useIds=initialUseIds();render();}}});
window.addEventListener('pagehide',()=>{controller?.abort();candidateView.destroy();},{once:true});
async function start() {
  root.innerHTML='<div class="studio-loading" role="status">正在准备模型目标与参考算法…</div>';
  try{const response=await fetch('/data/portfolio.json');if(!response.ok)throw Error('模型数据读取失败');data=await response.json();dataKey=await studio.initialize(data);await loadFinanceHistory(studio);await studio.initializeForecastMethods(dataKey);await loadFinanceContracts(studio);await studio.initializeFinancingMethods(dataKey);route();if(selectedId&&!getGoal())selectedId=null;draft=getGoal()?structuredClone(getGoal().draft):null;selectedVersionId=selectedVersionId||getGoal()&&studio.read().bindings[selectedId];if(query.get('editVersion')){const source=studio.read().versions.find(v=>v.id===query.get('editVersion')&&v.goalId===selectedId);if(source){Object.assign(draft,{methodId:source.methodId||null,sourceVersionId:source.id,ioBindings:source.ioBindings?structuredClone(source.ioBindings):undefined,code:source.code,parameters:structuredClone(source.parameters),dataKey:source.dataKey,objectIds:[...source.objectIds]});dirty=true;tab='algorithm';persistView();}}useIds=initialUseIds();if(query.get('focusModel')){const response=await fetch('/model-api/v1/model-management/context?scenarioId=S003');if(response.ok)sourceReference=(await response.json()).state;}initialized=true;render();announce();window.__MODEL_STUDIO_DEBUG__={read:()=>studio.read(),current:()=>({selectedId,tab,dirty,busy})};}catch(caught){root.innerHTML=`<section class="studio-panel"><h1>模型与算法</h1><p role="alert">${esc(caught.message)}</p><button class="studio-button" onclick="location.reload()">重新读取</button></section>`;}
}
void start();
